export const INTL_ASIAN_RECIPES = [
  // ─── JAPANESE (12) ──────────────────────────────────────────────────────────
  {
    name: "日式親子丼",
    description: "雞肉滑嫩，蛋液半熟呈流質狀，醬汁微甜香濃，配白飯一流，係最溫暖嘅日式家庭料理。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "日式",
    ingredients: [
      { name: "雞腿肉", quantity: "200", unit: "克", category: "肉類" },
      { name: "雞蛋", quantity: "3", unit: "隻", category: "其他" },
      { name: "洋蔥", quantity: "1/2", unit: "個", category: "蔬菜" },
      { name: "日式醬油", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "味醂", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "白糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "昆布柴魚高湯（或水）", quantity: "100", unit: "毫升", category: "其他" },
      { name: "白飯", quantity: "2", unit: "碗", category: "其他" },
    ],
    steps: [
      { instruction: "雞肉切一口大小，洋蔥切細絲，雞蛋稍微打散（保留蛋白蛋黃層次，唔使攪得太勻）。", duration: 5 },
      { instruction: "平底小鍋中加入高湯、日式醬油、味醂同糖煮滾，放入洋蔥絲中火煮2分鐘至稍微軟化。", duration: 3 },
      { instruction: "加入雞肉件鋪平，蓋蓋中火煮5分鐘至雞肉熟透。", duration: 5 },
      { instruction: "均勻淋入2/3蛋液，蓋蓋煮30秒，再淋入餘下蛋液，關火蓋蓋悶20秒，倒在白飯上即成。", duration: 2 },
    ],
    tags: ["簡單", "快手", "15 分鐘內", "小朋友", "下飯"],
  },
  {
    name: "日式照燒雞",
    description: "經典日式Teriyaki風味！雞髀肉煎至皮脆肉嫩，裹上濃郁鹹甜嘅照燒醬汁，閃亮誘人。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "日式",
    ingredients: [
      { name: "無骨雞髀肉", quantity: "400", unit: "克", category: "肉類" },
      { name: "日式生抽", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "味醂", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "日本清酒", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "砂糖", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "白芝麻", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "雞髀肉用叉在雞皮上戳幾個小孔防止縮水。調照燒汁：醬油、味醂、清酒同砂糖攪勻。", duration: 5 },
      { instruction: "熱平底鑊（唔使落油），雞皮向下放入，中火慢煎5分鐘至雞皮金黃酥脆，逼出雞油。", duration: 5 },
      { instruction: "翻面繼續煎4分鐘至八成熟，用廚房紙吸去鑊中多餘油分。", duration: 4 },
      { instruction: "倒入照燒汁，小火一邊煮一邊用勺子將汁澆在雞肉上，至汁液濃稠、雞肉熟透，取出切件淋汁，撒白芝麻。", duration: 6 },
    ],
    tags: ["30 分鐘內", "簡單", "下飯", "家常", "小朋友"],
  },
  {
    name: "日式咖喱豬扒飯",
    description: "金黃酥脆嘅吉列炸豬扒，淋上濃郁芬芳、帶有蔬果甜味嘅日式咖喱汁，大飽口福。",
    cookTime: 40,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "日式",
    ingredients: [
      { name: "炸好嘅吉列豬扒", quantity: "3", unit: "塊", category: "肉類" },
      { name: "日式咖喱磚", quantity: "4", unit: "塊", category: "調味料" },
      { name: "薯仔/胡蘿蔔/洋蔥", quantity: "各1", unit: "個", category: "蔬菜" },
      { name: "白飯", quantity: "3", unit: "碗", category: "其他" },
      { name: "水", quantity: "600", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "薯仔、胡蘿蔔去皮切小塊。洋蔥切細丁。準備好吉列豬扒。", duration: 15 },
      { instruction: "熱鍋落油炒香洋蔥丁至微金黃，加入薯仔、胡蘿蔔塊大火炒2分鐘。", duration: 5 },
      { instruction: "加入水，大火燒開轉小火，蓋蓋煮15分鐘至蔬菜變軟。關火，放入咖喱磚攪拌至完全融化。", duration: 15 },
      { instruction: "重新開小火燉煮5分鐘至汁濃稠。大盤中裝白飯、放上切條嘅炸豬扒，均勻淋上熱咖喱汁即可。", duration: 5 },
    ],
    tags: ["香脆", "香濃", "30 分鐘以上", "宴客", "進階"],
  },
  {
    name: "日式味噌湯",
    description: "日本每餐必備嘅靈魂湯水！昆布柴魚高湯作底，拌入香濃味噌、豆腐同海帶芽，清甜暖胃。",
    cookTime: 15,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "日式",
    ingredients: [
      { name: "日式嫩豆腐", quantity: "1", unit: "盒", category: "豆腐" },
      { name: "乾燥海帶芽", quantity: "1", unit: "湯匙", category: "其他" },
      { name: "日式味噌（信州味噌）", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "昆布柴魚高湯（Dashi）", quantity: "600", unit: "毫升", category: "湯" },
      { name: "蔥花", quantity: "少許", unit: "", category: "蔬菜" },
    ],
    steps: [
      { instruction: "豆腐切成1厘米小方塊。海帶芽用水泡軟瀝乾。蔥切花。", duration: 5 },
      { instruction: "高湯倒入鍋中煮滾，放入豆腐塊同海帶芽，小火煮2分鐘。", duration: 3 },
      { instruction: "關火（味噌不能大火滾煮，會流失香氣），用濾網將味噌放入湯中，用筷子攪拌至完全溶化。", duration: 3 },
      { instruction: "重新開微火加熱（不燒滾），撒上蔥花即可盛碗。", duration: 2 },
    ],
    tags: ["清淡", "暖胃", "簡單", "快手", "15 分鐘內"],
  },
  {
    name: "日式大根燉五花肉",
    description: "新鮮大根（白蘿蔔）與肥美五花肉慢火同燉，白蘿蔔吸收咗肉汁油香，軟爛多汁，甘甜可口。",
    cookTime: 90,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "日式",
    ingredients: [
      { name: "五花肉塊", quantity: "500", unit: "克", category: "肉類" },
      { name: "白蘿蔔（大根）", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "日式生抽", quantity: "4", unit: "湯匙", category: "調味料" },
      { name: "味醂/日本清酒", quantity: "各3", unit: "湯匙", category: "調味料" },
      { name: "砂糖", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "生薑片", quantity: "4", unit: "片", category: "調味料" },
    ],
    steps: [
      { instruction: "五花肉切大厚塊飛水。蘿蔔去皮切厚圓輪狀（邊緣削圓防煮爛），中火預煮10分鐘去澀味。", duration: 20 },
      { instruction: "鍋中倒入五花肉、蘿蔔、薑片同清酒、生抽、味醂、糖，加入沒過食材嘅熱水，大火燒開撇去浮沫。", duration: 10 },
      { instruction: "轉小火蓋上落蓋（紙蓋或輕蓋）慢火燉煮60分鐘，至豬肉及大根完全軟嫩入味。", duration: 60 },
    ],
    tags: ["慢煮", "香濃", "清甜", "60 分鐘以上", "中等"],
  },
  {
    name: "豚汁",
    description: "《深夜食堂》靈魂小菜！豬肉薄片與多種根莖類蔬菜、冬菇慢火熬煮嘅味噌湯，營養極其豐富。",
    cookTime: 30,
    servings: 4,
    difficulty: "簡單",
    recipeCategory: "日式",
    ingredients: [
      { name: "豬肉薄片（肥牛或五花薄片）", quantity: "150", unit: "克", category: "肉類" },
      { name: "白蘿蔔/胡蘿蔔/牛蒡", quantity: "各50", unit: "克", category: "蔬菜" },
      { name: "板豆腐/蒟蒻/冬菇", quantity: "適量", unit: "", category: "其他" },
      { name: "日式味噌", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "柴魚高湯", quantity: "800", unit: "毫升", category: "湯" },
    ],
    steps: [
      { instruction: "所有蔬菜去皮切薄片。蒟蒻用手撕小塊飛水。豬肉片切段。", duration: 12 },
      { instruction: "熱鍋落少許油下豬肉片炒至變色，加入所有蔬菜同蒟蒻塊大火翻炒2分鐘。", duration: 5 },
      { instruction: "倒入高湯煮滾，轉小火煮15-20分鐘至蔬菜完全熟透。關火拌入味噌至溶，撒蔥花即可。", duration: 15 },
    ],
    tags: ["蔬菜", "家常", "簡單", "30 分鐘內"],
  },
  {
    name: "日式生薑燒肉",
    description: "最經典嘅日式便當菜！生薑蓉、醬油調製嘅秘汁爆炒肥美豬肉片，生薑微辣解膩，無敵落飯。",
    cookTime: 15,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "日式",
    ingredients: [
      { name: "五花肉薄片或梅頭肉片", quantity: "250", unit: "克", category: "肉類" },
      { name: "新鮮生薑（磨蓉）", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "日式生抽", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "味醂/日本清酒", quantity: "各1", unit: "湯匙", category: "調味料" },
      { name: "白糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "椰菜（高麗菜，切極細絲）", quantity: "適量", unit: "", category: "蔬菜" },
    ],
    steps: [
      { instruction: "調生薑燒肉汁：薑蓉、生抽、味醂、清酒、砂糖混勻。椰菜切細絲泡冰水瀝乾擺盤底。", duration: 8 },
      { instruction: "熱平底鑊下油，平鋪豬肉片中大火煎炒至雙面變色熟透。", duration: 4 },
      { instruction: "倒入生薑燒肉汁，大火快速爆炒勻，至醬汁濃稠緊裹肉片即可起鍋，鋪在椰菜絲上。", duration: 3 },
    ],
    tags: ["快手", "簡單", "15 分鐘內", "下飯"],
  },
  {
    name: "日式壽喜燒",
    description: "高級牛肉、蒟蒻絲、豆腐同鮮菇，在甜美嘅壽喜燒醬油（割下）中微滾，蘸上新鮮生蛋液，滑嫩甘美。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "日式",
    ingredients: [
      { name: "高級肥牛薄片", quantity: "300", unit: "克", category: "肉類" },
      { name: "板豆腐（烤焦黃表面）/大蔥", quantity: "適量", unit: "", category: "其他" },
      { name: "金針菇/香菇/蒟蒻絲/茼蒿菜", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "日式生抽/味醂", quantity: "各100", unit: "毫升", category: "調味料" },
      { name: "日本清酒/糖", quantity: "各50", unit: "毫升/克", category: "調味料" },
      { name: "新鮮無菌雞蛋", quantity: "3", unit: "隻", category: "其他" },
    ],
    steps: [
      { instruction: "調割下汁：醬油、味醂、清酒同糖在鍋中煮溶放涼。豆腐、大蔥、鮮菇切好切段。", duration: 10 },
      { instruction: "熱鑄鐵平底淺鍋（或壽喜燒鍋），抹上牛油（或沙拉油），爆香大蔥段同少許牛肉片片。", duration: 5 },
      { instruction: "倒入部分割下汁，整齊排入豆腐塊、鮮菇、蒟蒻絲及茼蒿菜，中火煮滾。", duration: 5 },
      { instruction: "將肥牛肉片燙至剛剛熟，取出蘸勻打散嘅生蛋液食用，陸續添加食材同汁水。", duration: 5 },
    ],
    tags: ["宴客", "簡單", "30 分鐘內"],
  },
  {
    name: "天婦羅炸大蝦",
    description: "裹上極其輕盈、薄脆嘅天婦羅粉漿炸透，大蝦肉質爽口，外皮呈金黃雪花狀，蘸上天婦羅汁，不油不膩。",
    cookTime: 30,
    servings: 3,
    difficulty: "困難",
    recipeCategory: "日式",
    ingredients: [
      { name: "大鮮蝦", quantity: "8", unit: "隻", category: "海鮮" },
      { name: "天婦羅粉", quantity: "1", unit: "杯", category: "其他" },
      { name: "冰水", quantity: "1", unit: "杯", category: "其他" },
      { name: "天婦羅沾汁（日式生抽/味醂/柴魚湯）", quantity: "適量", unit: "", category: "調味料" },
      { name: "食油（炸油）", quantity: "大量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "鮮蝦去殼留尾，背部切幾刀，按壓腹部筋絡拉直（防止炸時彎曲）。用廚房紙徹底抹乾。", duration: 15 },
      { instruction: "調天婦羅漿：天婦羅粉加冰水（必須是極冷冰水，可產生鬆脆感）粗略攪拌，保留粉粒，不可過度攪拌。", duration: 5 },
      { instruction: "大火將油溫燒至170-180度。蝦均勻裹上薄乾粉，再裹天婦羅漿，迅速滑入油中，炸至外皮剛硬呈金黃（約2-3分鐘），捞出瀝乾。", duration: 8 },
    ],
    tags: ["海鮮", "香脆", "宴客", "進階"],
  },
  {
    name: "日式章魚小丸子",
    description: "經典日本街頭小食！外脆內軟嘅小丸子裹住Q彈章魚肉，淋上特調章魚燒醬、蛋黃醬同舞動嘅柴魚片。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "日式",
    ingredients: [
      { name: "已煮熟章魚肉（切粒）", quantity: "80", unit: "克", category: "海鮮" },
      { name: "章魚燒預拌粉", quantity: "100", unit: "克", category: "其他" },
      { name: "雞蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "水", quantity: "300", unit: "毫升", category: "其他" },
      { name: "椰菜碎/天婦羅酥/紅薑碎", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "章魚燒醬/蛋黃醬/柴魚片", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "章魚燒粉、水同雞蛋混合調成稀粉漿。章魚、椰菜切碎。需要準備章魚燒模具烤盤。", duration: 10 },
      { instruction: "模具大火燒熱抹足量油，倒入粉漿沒過模孔，撒入章魚粒、椰菜碎、天婦羅酥同紅薑碎。", duration: 8 },
      { instruction: "粉漿稍微凝固時，用竹籤把丸子轉90度，把邊緣多餘粉漿塞入孔中，陸續翻轉呈球形，大火翻轉煎至外皮金黃酥脆（約8-10分鐘）。", duration: 10 },
      { instruction: "裝碟，淋章魚燒醬、蛋黃醬，撒海苔粉同大量柴魚片（熱氣使柴魚片舞動）即可。", duration: 2 },
    ],
    tags: ["海鮮", "香脆", "特色", "小朋友", "進階"],
  },
  {
    name: "日式玉子燒",
    description: "層層捲疊嘅金黃煎蛋，質地細緻綿密如海綿蛋糕，帶有淡淡嘅甜味同昆布高湯鮮甜，玉子燒專用鍋製作。",
    cookTime: 20,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "日式",
    ingredients: [
      { name: "雞蛋", quantity: "4", unit: "隻", category: "其他" },
      { name: "昆布柴魚高湯", quantity: "3", unit: "湯匙", category: "湯" },
      { name: "砂糖", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "日式生抽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "鹽", quantity: "少許", unit: "", category: "調味料" },
      { name: "食油", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "雞蛋、高湯、糖、生抽、鹽混合輕輕攪勻，過篩使蛋液極度細膩。", duration: 8 },
      { instruction: "玉子燒方形專用鍋燒熱，抹薄油。倒入1/3蛋液鋪平，中火慢煎至半熟，由上往下捲起，推至最上方。", duration: 4 },
      { instruction: "再次抹油，倒入剩餘半數蛋液，抬起上方蛋捲讓蛋液流入其下方，半熟時再次捲起，重複步驟至蛋液用完。", duration: 6 },
      { instruction: "取出，用竹簾稍微整型壓緊成漂亮方形，切厚片享用。", duration: 2 },
    ],
    tags: ["30 分鐘內", "小朋友", "清淡", "進階"],
  },
  {
    name: "日式漢堡排",
    description: "日式洋食經典！牛免治與豬免治混合加入洋蔥，拍打出極具彈性同多汁嘅肉餅，配黑椒紅酒淋醬，美味驚人。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "日式",
    ingredients: [
      { name: "免治牛肉", quantity: "200", unit: "克", category: "肉類" },
      { name: "免治豬肉", quantity: "100", unit: "克", category: "肉類" },
      { name: "洋蔥", quantity: "1/2", unit: "個", category: "蔬菜" },
      { name: "麵包糠/牛奶", quantity: "3湯匙/2湯匙", unit: "", category: "其他" },
      { name: "雞蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "日式生抽/紅酒/茄汁", quantity: "適量（淋醬調配）", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "洋蔥切極細碎炒至焦黃放涼。麵包糠用牛奶泡軟。將牛肉、豬肉、洋蔥碎、泡軟麵包糠、雞蛋、鹽胡椒放入碗中用力攪拌上勁，雙手來回摔打肉團20次排除空氣，塑形成橢圓厚餅。", duration: 15 },
      { instruction: "熱鑊下油，中小火放入漢堡肉，兩面各煎2分鐘至焦黃定型。", duration: 4 },
      { instruction: "灒少許紅酒（或水），蓋蓋小火蒸焗5分鐘至中心熟透，盛起。", duration: 5 },
      { instruction: "同一鑊倒入紅酒、茄汁、生抽同少許糖煮至濃稠淋醬，均勻澆在漢堡排上即可。", duration: 6 },
    ],
    tags: ["小朋友", "宴客", "進階"],
  },

  // ─── KOREAN (12) ───────────────────────────────────────────────────────────
  {
    name: "韓式拌飯",
    description: "經典Bibimbap！白飯上鋪滿色彩繽紛嘅時令配菜、香煎牛肉同太陽蛋，拌入香辣甜美嘅韓式辣醬，大滿足。",
    cookTime: 25,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "牛肉薄片", quantity: "100", unit: "克", category: "肉類" },
      { name: "菠菜/豆芽/胡蘿蔔/香菇", quantity: "各50", unit: "克", category: "蔬菜" },
      { name: "白飯", quantity: "2", unit: "碗", category: "其他" },
      { name: "雞蛋", quantity: "2", unit: "隻", category: "其他" },
      { name: "韓式辣椒醬", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "麻油/熟白芝麻", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "蔬菜洗淨，胡蘿蔔、香菇切絲。牛肉用少許生抽醃。菠菜同豆芽汆水，拌入少許鹽同麻油。", duration: 12 },
      { instruction: "熱鑊炒熟胡蘿蔔絲、香菇絲及牛肉片，盛起。煎兩隻太陽蛋（蛋黃半熟）。", duration: 8 },
      { instruction: "大碗裝入白飯，均勻將所有蔬菜、肉類呈放射狀排在白飯表面，正中間放太陽蛋。", duration: 3 },
      { instruction: "放上大匙韓式辣椒醬，淋一圈麻油，撒芝麻。食時完全拌勻即可。", duration: 2 },
    ],
    tags: ["蔬菜", "香辣", "開胃", "簡單", "30 分鐘內"],
  },
  {
    name: "韓式泡菜豆腐湯",
    description: "酸辣刺激嘅韓國泡菜，與嫩滑豆腐、五花肉慢火同煲。湯汁紅潤微辣，滾燙暖胃，最適合冷天飲用。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "韓國老泡菜（連泡菜汁）", quantity: "200", unit: "克", category: "蔬菜" },
      { name: "嫩豆腐/洋蔥/蔥", quantity: "適量", unit: "", category: "其他" },
      { name: "五花肉薄片", quantity: "100", unit: "克", category: "肉類" },
      { name: "韓式辣椒粉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蒜泥/生抽", quantity: "各1", unit: "茶匙", category: "調味料" },
      { name: "淘米水或水", quantity: "500", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "泡菜切段，豆腐切厚塊，洋蔥切絲，蔥切段。五花肉片切小段。", duration: 5 },
      { instruction: "石鍋（或小砂鍋）落少許油下五花肉片，中火煸炒至出油，加入泡菜、洋蔥絲同辣椒粉大火翻炒2分鐘。", duration: 5 },
      { instruction: "倒入淘米水（使湯汁濃郁），加入泡菜汁、蒜泥、生抽，大火燒開轉小火煮8分鐘。", duration: 8 },
      { instruction: "放入豆腐塊，繼續小火煮2分鐘，最後撒上蔥段即可滾燙整鍋上桌。", duration: 2 },
    ],
    tags: ["暖胃", "快手", "簡單", "30 分鐘內"],
  },
  {
    name: "韓式炸雞",
    description: "風靡全港嘅邪惡小食！雞髀肉炸至雙重極致酥脆，外面緊緊裹上均勻嘅甜辣醬（洋釀）或蒜香醬，配啤酒極品。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "韓式",
    ingredients: [
      { name: "無骨去皮雞髀肉（切塊）", quantity: "400", unit: "克", category: "肉類" },
      { name: "牛奶（浸泡去腥）", quantity: "1/2", unit: "杯", category: "其他" },
      { name: "炸粉（或生粉/麵粉）", quantity: "適量", unit: "", category: "其他" },
      { name: "韓式辣椒醬/茄汁", quantity: "各1.5", unit: "湯匙", category: "調味料" },
      { name: "糖稀或蜂蜜/水/蒜茸", quantity: "適量", unit: "", category: "調味料" },
      { name: "食油", quantity: "大量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "雞塊用牛奶、少許鹽和胡椒粉浸泡20分鐘去腥，抹乾，沾上一層薄薄嘅炸粉漿。", duration: 20 },
      { instruction: "熱油燒至中溫下雞肉，中火炸5分鐘熟透撈起。大火燒至高溫，重炸30秒至外表金黃硬脆，撈出。", duration: 6 },
      { instruction: "調甜辣醬：韓式辣醬、茄汁、蜂蜜、水、蒜茸混合。落鑊小火煮至滾起泡泡。", duration: 2 },
      { instruction: "立刻倒入炸雞塊，快速翻炒讓醬汁均勻黏附在每一塊雞肉上，出鍋撒白芝麻即可。", duration: 2 },
    ],
    tags: ["香脆", "特色", "送酒", "中等", "30 分鐘內"],
  },
  {
    name: "韓式海鮮煎餅",
    description: "脆皮麵糊拌入大量鮮蝦、魷魚同大蔥段，煎至兩面焦黃香酥，蘸上特調醬油醋，外酥內軟，鮮美無比。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "蝦仁/鮮魷魚粒", quantity: "各80", unit: "克", category: "海鮮" },
      { name: "大蔥或小蔥（切長段）", quantity: "1", unit: "大束", category: "蔬菜" },
      { name: "韓式煎餅粉", quantity: "150", unit: "克", category: "其他" },
      { name: "冰水", quantity: "200", unit: "毫升", category: "其他" },
      { name: "雞蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "食油/生抽/白醋", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "海鮮切小粒抹乾。煎餅粉、冰水同雞蛋混合調成略稀嘅麵糊。大蔥切成約5厘米長段。", duration: 10 },
      { instruction: "平底鍋倒多啲油燒熱，先排入大蔥段，再均勻排入海鮮粒，最後均勻淋入麵糊蓋住食材。", duration: 4 },
      { instruction: "中小火煎3-4分鐘至底部金黃。翻面（需要一點技巧），沿邊補少許油，煎熟另一面並至香脆（約3分鐘）。", duration: 4 },
      { instruction: "切塊，佐以生抽、醋調成嘅煎餅沾汁食用。", duration: 2 },
    ],
    tags: ["海鮮", "香脆", "簡單", "30 分鐘內"],
  },
  {
    name: "韓式泡菜炒飯",
    description: "最快手、最香濃嘅快餐小炒！酸辣泡菜與香濃五花肉粒、隔夜飯高溫爆炒，蓋上太陽蛋，完美落飯。",
    cookTime: 15,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "隔夜白飯", quantity: "2", unit: "碗", category: "其他" },
      { name: "韓式泡菜", quantity: "120", unit: "克", category: "蔬菜" },
      { name: "五花肉或午餐肉丁", quantity: "50", unit: "克", category: "肉類" },
      { name: "太陽蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "韓式辣椒醬/生抽", quantity: "各1", unit: "茶匙", category: "調味料" },
      { name: "麻油/紫菜絲/熟芝麻", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "泡菜切碎。肉切細丁。準備好隔夜白飯（壓散）。", duration: 5 },
      { instruction: "熱鑊下油，煸香五花肉丁，下泡菜碎炒出香氣（約2分鐘）。", duration: 3 },
      { instruction: "倒入白飯、韓式辣醬、生抽快速大火翻炒勻，使白飯完全沾滿泡菜紅色醬汁。", duration: 4 },
      { instruction: "灒麻油撒芝麻。盛起，蓋上單面煎好嘅太陽蛋同紫菜絲即成。", duration: 3 },
    ],
    tags: ["炒飯", "快手", "15 分鐘內", "簡單"],
  },
  {
    name: "韓式人參雞湯",
    description: "韓國傳統高檔補身老湯（Samgyetang）！整隻嫩童子雞空腔填滿糯米、人參、紅棗與大蒜慢火熬燉，雞肉軟爛脫骨，湯汁濃郁清甜。",
    cookTime: 120,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "韓式",
    ingredients: [
      { name: "新鮮童子雞", quantity: "1", unit: "隻", category: "肉類" },
      { name: "圓糯米（浸泡2小時）", quantity: "50", unit: "克", category: "其他" },
      { name: "新鮮高麗參或乾參", quantity: "1", unit: "支", category: "調味料" },
      { name: "紅棗/大蒜（去皮整瓣）", quantity: "適量", unit: "", category: "其他" },
      { name: "鹽/白胡椒粉", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "童子雞洗淨掏空內臟。圓糯米提前浸泡。將糯米、人參、數瓣大蒜同紅棗塞入雞腹腔中，用棉線或雞腿交叉封口（防糯米流出）。", duration: 20 },
      { instruction: "大深煲加入足量水，放入雞同餘下嘅人參大蒜紅棗，大火燒開，撇去血沫。", duration: 10 },
      { instruction: "轉小火，蓋蓋慢火燉煮90分鐘，直至雞肉極其軟爛脫骨、糯米熟透膨脹。", duration: 90 },
      { instruction: "食用時撒蔥花，在碗中自行加鹽和白胡椒粉調味。", duration: 2 },
    ],
    tags: ["慢煮", "滋補", "60 分鐘以上", "中等"],
  },
  {
    name: "韓式大醬湯",
    description: "韓國家庭每餐必備！醇厚微甜鹹香嘅韓式大醬，配上牛肉、豆腐、西葫蘆同鮮菇滾煮，醬香滿溢。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "韓式大醬（Doenjang）", quantity: "2.5", unit: "湯匙", category: "調味料" },
      { name: "牛肉薄片", quantity: "80", unit: "克", category: "肉類" },
      { name: "嫩豆腐/西葫蘆（切片）/金針菇", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "淘米水或柴魚高湯", quantity: "600", unit: "毫升", category: "湯" },
      { name: "蒜泥/青辣椒片", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "豆腐西葫蘆切塊。牛肉片切小段。金針菇去根。", duration: 5 },
      { instruction: "石鍋中倒入淘米水與大醬攪拌勻，大火燒開。", duration: 3 },
      { instruction: "排入西葫蘆、金針菇、牛肉同豆腐，中火滾煮10分鐘至熟。", duration: 10 },
      { instruction: "加入蒜泥、青辣椒片，再滾2分鐘，滾燙呈上。", duration: 2 },
    ],
    tags: ["暖胃", "家常", "簡單", "30 分鐘內", "快手"],
  },
  {
    name: "韓式炒年糕",
    description: "大受歡迎嘅韓國街頭名物（Tteokbokki）！Q彈有嚼勁嘅年糕條、韓式魚糕在紅油甜辣醬汁中慢火收汁，邪惡誘人。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "韓式中空或實心年糕條", quantity: "200", unit: "克", category: "其他" },
      { name: "韓國魚糕（扁形切塊）", quantity: "1", unit: "張", category: "其他" },
      { name: "洋蔥絲/高麗菜/大蔥段", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "韓式辣椒醬", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "辣椒粉/白糖", quantity: "適量", unit: "", category: "調味料" },
      { name: "昆布高湯或水", quantity: "300", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "年糕冷水浸軟。魚糕切三角形。調辣醬：韓式辣醬、辣椒粉、糖混合。", duration: 5 },
      { instruction: "鍋中倒入高湯、調好嘅辣醬煮滾，放入年糕條中火煮5分鐘至軟。", duration: 5 },
      { instruction: "放入魚糕、高麗菜同洋蔥絲，中大火煮5-8分鐘至湯汁變得極其濃稠、紅潤黏稠裹住年糕。", duration: 8 },
      { instruction: "起鍋前撒入大蔥段，撒熟芝麻即成。", duration: 2 },
    ],
    tags: ["簡單", "30 分鐘內"],
  },
  {
    name: "韓式部隊鍋",
    description: "融匯西方與韓式食材！泡麵、午餐肉、香腸、豆腐、泡菜與大量芝士片在紅油甜辣湯底中熱滾，大滿足。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "韓國辛拉麵（連調味包）", quantity: "1", unit: "包", category: "其他" },
      { name: "罐頭午餐肉/美式香腸（切片）", quantity: "各80", unit: "克", category: "肉類" },
      { name: "嫩豆腐/洋蔥絲/泡菜", quantity: "適量", unit: "", category: "其他" },
      { name: "金針菇/芝士片（起司片）", quantity: "1包/2張", unit: "", category: "其他" },
      { name: "韓式辣椒醬", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "水", quantity: "700", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "午餐肉、香腸切厚片。豆腐切片，金針菇去根。調醬汁：韓式辣醬同辛拉麵調味粉混合。", duration: 8 },
      { instruction: "在火鍋淺平鍋中整齊排好午餐肉、香腸、泡菜、洋蔥、金針菇同豆腐塊，中間放調醬。", duration: 5 },
      { instruction: "倒入熱水大火燒開，轉中火滾5分鐘至食材熟透。放上辛拉麵餅，面上鋪芝士片。", duration: 8 },
      { instruction: "中火滾3-4分鐘至麵條變軟、芝士溶化即可整鍋上桌，邊煮邊食最正。", duration: 4 },
    ],
    tags: ["香辣", "簡單", "30 分鐘內"],
  },
  {
    name: "韓式烤牛肉",
    description: "經典Bulgogi！極薄嘅牛肉片用洋蔥泥、梨汁、醬油同香油醃至滑嫩，大火快炒焦香，甜香滑溜。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "牛肉薄片（肥牛或沙朗薄片）", quantity: "300", unit: "克", category: "肉類" },
      { name: "洋蔥絲", quantity: "1/2", unit: "個", category: "蔬菜" },
      { name: "蒜泥/蔥花", quantity: "適量", unit: "", category: "調味料" },
      { name: "生抽", quantity: "2.5", unit: "湯匙", category: "調味料" },
      { name: "白糖/蜂蜜", quantity: "各1", unit: "湯匙", category: "調味料" },
      { name: "麻油/熟白芝麻", quantity: "適量", unit: "", category: "調味料" },
      { name: "新鮮水梨汁（或蘋果泥）", quantity: "3", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "牛肉薄片加入生抽、糖、蜂蜜、蒜泥、梨汁（天然酵素使肉滑嫩）同麻油醃製至少30分鐘。拌入洋蔥絲。", duration: 10 },
      { instruction: "平底鍋（不粘鍋最佳）燒得極熱，落少許油，將醃好嘅牛肉同洋蔥絲整批下鍋。", duration: 5 },
      { instruction: "大火猛火極速爆炒2-3分鐘至牛肉片剛熟變焦黃，鎖緊肉汁。", duration: 3 },
      { instruction: "出鑊撒大量芝麻同蔥花，可包以生菜葉同吃。", duration: 2 },
    ],
    tags: ["滑嫩", "快手", "簡單", "30 分鐘內"],
  },
  {
    name: "韓式安東燉雞",
    description: "源自安東地區！大件雞髀肉、薯仔、胡蘿蔔與韓式寬冬粉（粉條）以微甜香辣醬油汁慢火燉煮，極致入味。",
    cookTime: 45,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "韓式",
    ingredients: [
      { name: "大雞髀肉件", quantity: "500", unit: "克", category: "肉類" },
      { name: "韓式寬冬粉", quantity: "80", unit: "克", category: "乾貨" },
      { name: "薯仔/胡蘿蔔/洋蔥", quantity: "各1", unit: "個", category: "蔬菜" },
      { name: "乾紅辣椒/大蔥", quantity: "適量", unit: "", category: "調味料" },
      { name: "生抽", quantity: "4", unit: "湯匙", category: "調味料" },
      { name: "白糖/黑糖", quantity: "各1.5", unit: "湯匙", category: "調味料" },
      { name: "水", quantity: "500", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "冬粉用熱水浸泡軟化。雞件飛水。薯仔胡蘿蔔切大塊，洋蔥切塊。", duration: 15 },
      { instruction: "大鍋爆香乾辣椒、大蔥段，下雞件大火炒金黃。下薯仔胡蘿蔔塊翻炒。", duration: 5 },
      { instruction: "倒入生抽、糖、黑糖（調出深琥珀色）同水，大火燒開轉小火燉煮20分鐘。", duration: 20 },
      { instruction: "加入寬冬粉同洋蔥塊，繼續燉煮5-8分鐘至冬粉吸乾汁水、薯仔粉綿，大火收稠裝盤。", duration: 5 },
    ],
    tags: ["香辣", "慢煮", "中等", "30 分鐘以上"],
  },
  {
    name: "韓式辣豆腐湯",
    description: "經典Soondubu Jjigae！極其軟嫩如布丁嘅嫩豆腐，加入鮮蝦、蛤蜊同香辣紅油滾煲，打入生雞蛋，極致滑嫩鮮辣。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "韓式嫩豆腐或超軟豆腐", quantity: "1", unit: "條", category: "豆腐" },
      { name: "鮮蝦仁/蛤蜊", quantity: "各60", unit: "克", category: "海鮮" },
      { name: "韓式辣粉/辣椒油", quantity: "適量", unit: "", category: "調味料" },
      { name: "生雞蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "蒜泥/大蔥花/高湯", quantity: "適量", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "蛤蜊吐沙洗淨。海鮮洗淨。嫩豆腐切大厚片。", duration: 8 },
      { instruction: "石鍋爆香蒜泥大蔥，下辣椒油同韓式辣粉小火煸出紅油，倒入高湯煮滾。", duration: 4 },
      { instruction: "下蛤蜊、蝦仁同整塊軟豆腐，中火煮滾6分鐘至蛤蜊開口。加入少許鹽調味。", duration: 6 },
      { instruction: "關火前打入一隻新鮮生雞蛋在正中，撒蔥花，上桌時蛋隨餘溫半熟，極其滑嫩。", duration: 2 },
    ],
    tags: ["海鮮", "滑嫩", "暖胃", "簡單", "快手", "30 分鐘內"],
  },

  // ─── SOUTHEAST ASIAN (12) ──────────────────────────────────────────────────
  {
    name: "泰式青咖喱雞",
    description: "清香微辛辣！自製青咖喱膏爆香加入濃郁椰奶，配泰式矮瓜、鮮嫩雞件與新鮮九層塔，泰爽滋味。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "雞髀肉件", quantity: "300", unit: "克", category: "肉類" },
      { name: "泰式青咖喱醬", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "濃椰奶（椰漿）", quantity: "200", unit: "毫升", category: "其他" },
      { name: "泰式小茄子/筍肉", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "泰式魚露", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "椰糖/泰式檸檬葉", quantity: "適量", unit: "", category: "調味料" },
      { name: "水", quantity: "100", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "雞件洗淨，茄子切半。檸檬葉撕碎。", duration: 5 },
      { instruction: "熱鍋中火倒入一半椰奶，慢火炒至椰油分離起泡。加入青咖喱醬炒出濃烈香氣。", duration: 5 },
      { instruction: "倒入雞件、茄子大火翻炒勻。加入剩餘椰奶、水、魚露、椰糖同檸檬葉煮滾。", duration: 5 },
      { instruction: "轉中火燉煮10分鐘至雞肉軟輭，出鍋前下泰式九層塔葉拌勻即可。", duration: 10 },
    ],
    tags: ["香辣", "鮮味", "下飯", "簡單", "30 分鐘內"],
  },
  {
    name: "泰式冬蔭功湯",
    description: "泰國國寶湯（Tom Yum Goong）！新鮮大蝦與香茅、南薑、檸檬葉及泰式辣椒膏同滾，酸辣刺激，鮮甜撲鼻。",
    cookTime: 20,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "新鮮大蝦（帶頭最佳）", quantity: "8", unit: "隻", category: "海鮮" },
      { name: "香茅（拍扁切段）/南薑片", quantity: "適量", unit: "", category: "調味料" },
      { name: "泰式檸檬葉/青檸", quantity: "適量", unit: "", category: "調味料" },
      { name: "草菇/番茄塊", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "泰式酸辣膏/魚露/椰糖", quantity: "適量", unit: "", category: "調味料" },
      { name: "水或雞湯", quantity: "800", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "蝦剪鬚剔腸，蝦頭可留着熬油。香茅拍扁斜切，南薑切片，檸檬葉撕碎。", duration: 8 },
      { instruction: "熱鍋下少許油，慢火把大蝦頭煎出紅紅嘅蝦油，盛起。倒入高湯，加入香茅、南薑、檸檬葉、番茄塊大火煮滾5分鐘出香氣。", duration: 5 },
      { instruction: "放入草菇同大蝦，加酸辣膏、魚露、少許椰糖，中大火煮3分鐘至蝦熟透。", duration: 3 },
      { instruction: "關火，淋入新鮮青檸汁拌勻即成（青檸汁不宜久滾，會變苦）。", duration: 4 },
    ],
    tags: ["海鮮", "鮮味", "宴客", "中等"],
  },
  {
    name: "越式牛肉河粉",
    description: "經典Pho Bo！牛骨、洋蔥同多種香料慢火熬煮十幾小時出清澈甜美嘅湯底。湯粉鋪上薄肥牛，淋上滾湯燙熟，極致鮮美。",
    cookTime: 40,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "越式新鮮或乾河粉", quantity: "150", unit: "克", category: "其他" },
      { name: "高級肥牛薄片", quantity: "150", unit: "克", category: "肉類" },
      { name: "牛骨清湯底", quantity: "800", unit: "毫升", category: "湯" },
      { name: "大沙薑/肉桂/八角", quantity: "少許（熬湯底用）", unit: "", category: "調味料" },
      { name: "洋蔥絲/生豆芽/九層塔/青檸", quantity: "適量（伴碟）", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "乾香料（八角、肉桂）微火烘香放入牛骨高湯中慢火煮出香氣。河粉煮熟瀝乾分裝入兩個大碗。", duration: 15 },
      { instruction: "大碗河粉上排好生牛肉薄片、洋蔥絲同洗淨嘅生豆芽。", duration: 5 },
      { instruction: "牛骨高湯中加魚露、鹽調好味，大火燒至大滾冒煙。", duration: 5 },
      { instruction: "立刻將大滾嘅高湯均勻淋在牛肉片同河粉上（高溫高湯會燙熟牛肉至絕佳粉紅色），佐以九層塔、青檸食用。", duration: 15 },
    ],
    tags: ["清淡", "暖胃", "經典", "30 分鐘以上"],
  },
  {
    name: "泰式炒金邊粉",
    description: "經典Pad Thai！金邊粉與鮮蝦、豆腐乾、菜脯碎在甜酸、微辣嘅羅望子（酸子）醬汁中大火爆炒，撒上碎花生，泰式美味。",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "泰式金邊粉（浸軟）", quantity: "200", unit: "克", category: "其他" },
      { name: "鮮蝦仁/豆腐乾粒", quantity: "各80", unit: "克", category: "其他" },
      { name: "雞蛋", quantity: "2", unit: "隻", category: "其他" },
      { name: "羅望子醬（酸子汁）", quantity: "2.5", unit: "湯匙", category: "調味料" },
      { name: "魚露/椰糖", quantity: "各1.5", unit: "湯匙", category: "調味料" },
      { name: "韭菜段/生豆芽/花生碎", quantity: "適量", unit: "", category: "蔬菜" },
    ],
    steps: [
      { instruction: "金邊粉熱水浸15分鐘至軟瀝乾。調汁：羅望子醬、魚露、椰糖煮溶攪勻。", duration: 15 },
      { instruction: "熱鑊下油爆香蝦仁、豆腐乾粒同菜脯，盛起。倒入蛋液快速炒碎。", duration: 3 },
      { instruction: "放入金邊粉、調好嘅醬汁，轉大火猛火快速翻炒，使金邊粉完全吸乾醬汁。", duration: 4 },
      { instruction: "倒回蝦仁，下韭菜段同生豆芽炒幾下，出鍋，表面撒大量炸花生碎及附上青檸角。", duration: 3 },
    ],
    tags: ["海鮮", "酸甜", "特色", "下飯", "中等"],
  },
  {
    name: "印尼炒飯",
    description: "經典Nasi Goreng！雞肉、蝦米與甜醬油、蝦醬大火爆炒，飯粒呈現迷人黑紅色，配上沙嗲肉串同太陽蛋，極具風味。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "隔夜冷飯", quantity: "2", unit: "碗", category: "其他" },
      { name: "雞肉丁/鮮蝦仁", quantity: "各60", unit: "克", category: "海鮮" },
      { name: "印尼甜醬油（Kecap Manis）", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "印尼蝦醬（Terasi）/蒜泥", quantity: "適量", unit: "", category: "調味料" },
      { name: "太陽蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "蝦片（炸好伴碟）", quantity: "適量", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "蝦仁、雞肉切丁，冷飯壓散。蝦片炸好。", duration: 5 },
      { instruction: "熱鑊下油，爆香蒜泥、少許乾辣椒同蝦醬（小火防止焦），下雞丁蝦仁炒熟。", duration: 5 },
      { instruction: "倒入白飯，淋入印尼甜醬油，轉大火極速翻炒，炒至白飯粒粒均勻黑紅、帶有焦香（約4分鐘）。", duration: 5 },
      { instruction: "盛起裝盤，排上炸蝦片、番茄片、小黃瓜片，蓋上單面煎好嘅太陽蛋即可。", duration: 5 },
    ],
    tags: ["炒飯", "海鮮", "15 分鐘內", "簡單", "快手"],
  },
  {
    name: "新加坡海南雞飯",
    description: "雞肉嫩滑、皮爽肉嫩。米飯先以雞油、蒜蓉、香茅炒香，再以鮮雞湯煮熟，飯粒油潤充滿雞香，完美演繹。",
    cookTime: 40,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "三黃雞（浸白切雞法）", quantity: "1/2", unit: "隻", category: "肉類" },
      { name: "茉莉香米", quantity: "2", unit: "杯", category: "其他" },
      { name: "自製新鮮雞油（或黃油）", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "蒜蓉/香茅/斑蘭葉", quantity: "適量", unit: "", category: "調味料" },
      { name: "浸雞鮮湯", quantity: "2", unit: "杯", category: "湯" },
      { name: "海南雞三色沾醬（黑醬油/薑蓉/酸辣醬）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "首先浸熟半隻白切雞，撈出泡冰水去骨切件。保留浸雞嘅鮮高湯。", duration: 25 },
      { instruction: "洗淨米。熱鍋下雞油，小火爆香蒜蓉、拍扁香茅段同斑蘭葉，倒入香米大火翻炒2分鐘至米粒呈半透明吸飽雞油。", duration: 5 },
      { instruction: "將米倒入電飯煲，加入等量浸雞高湯、少許鹽，蓋上正常煲飯。", duration: 5 },
      { instruction: "煲好後去除香茅斑蘭葉，盛一碗雞油飯，鋪上去骨海南雞件，附上三色沾醬即可奢華享用。", duration: 5 },
    ],
    tags: ["鮮味", "經典", "宴客", "進階"],
  },
  {
    name: "泰式香葉肉碎炒飯",
    description: "經典打拋豬炒飯！微辣酸甜嘅打拋豬肉碎，與泰式香米、新鮮九層塔、魚露大火爆炒，鑊氣十足，開胃解膩。",
    cookTime: 15,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "隔夜泰式香米飯", quantity: "2", unit: "碗", category: "其他" },
      { name: "免治豬肉（肉碎）", quantity: "120", unit: "克", category: "肉類" },
      { name: "泰式打拋葉（或九層塔葉）", quantity: "1", unit: "大束", category: "蔬菜" },
      { name: "蒜片/紅天椒粒", quantity: "適量", unit: "", category: "調味料" },
      { name: "泰式魚露/生抽", quantity: "各1", unit: "湯匙", category: "調味料" },
      { name: "糖/青檸汁", quantity: "各1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "免治豬肉加少許生抽醃。準備好米飯。九層塔摘葉。蒜蓉辣椒切碎。", duration: 5 },
      { instruction: "熱鑊下油爆香蒜茸辣椒碎，下免治豬肉大火快速炒散至變色熟透。", duration: 3 },
      { instruction: "倒入米飯，加入魚露、生抽、糖，大火猛火翻炒3分鐘使飯粒爽口焦香。", duration: 4 },
      { instruction: "倒入九層塔葉同青檸汁，快速翻炒數秒至九層塔變軟起鑊即成。", duration: 3 },
    ],
    tags: ["炒飯", "香辣", "15 分鐘內", "簡單", "快手"],
  },
  {
    name: "肉骨茶",
    description: "新馬南洋代表！排骨、大蒜與胡椒、歸、川芎等多種中藥材慢火熬製，湯汁濃郁暖胃，有強烈白胡椒香（新加坡式）。",
    cookTime: 90,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "優質一字腩排/肉骨", quantity: "500", unit: "克", category: "肉類" },
      { name: "白胡椒粒（拍裂）", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "整頭大蒜（連皮）", quantity: "2", unit: "頭", category: "調味料" },
      { name: "中藥包（當歸/玉竹/川芎/黨參等）", quantity: "1", unit: "包", category: "調味料" },
      { name: "生抽/老抽/黑醬油", quantity: "適量", unit: "", category: "調味料" },
      { name: "油條（切段伴食）", quantity: "適量", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "肉骨切長段，冷水飛水5分鐘洗淨。整頭大蒜去泥洗乾淨（不要去皮，去皮煲湯會溶混濁）。", duration: 15 },
      { instruction: "大煲中倒入足量水，放入拍裂嘅白胡椒粒（新加坡白胡椒風味）、整頭大蒜、中藥包大火燒滾10分鐘至香氣散發。", duration: 10 },
      { instruction: "放入排骨，大火燒開轉小火，蓋蓋慢火燉煮60-90分鐘至排骨肉質鬆軟。", duration: 60 },
      { instruction: "加生抽、老抽同少許鹽調味。熱騰騰盛起，佐以切段油條及黑醬油食用。", duration: 5 },
    ],
    tags: ["慢煮", "滋補", "暖胃", "60 分鐘以上", "中等"],
  },
  {
    name: "越式春卷",
    description: "輕透薄脆！透明米紙（Rice paper）包裹鮮蝦、米粉、生菜與清涼薄荷葉，點花生醬或魚露酸辣汁，清爽極致。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "越南米紙", quantity: "10", unit: "張", category: "其他" },
      { name: "鮮熟蝦仁（切半）", quantity: "10", unit: "隻", category: "海鮮" },
      { name: "米粉（煮熟放涼）", quantity: "50", unit: "克", category: "其他" },
      { name: "生菜葉/青瓜條/薄荷葉", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "越式沾汁（魚露/檸檬汁/糖/蒜茸辣椒）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "蝦仁燙熟剖半。米粉煮熟過冷河。蔬菜切細長條。準備一大盤溫水。", duration: 10 },
      { instruction: "取一張米紙，在溫水中浸泡3-5秒使其變軟，輕輕平鋪在乾淨砧板上。", duration: 2 },
      { instruction: "先在米紙中下方排入生菜葉、米粉、青瓜條同薄荷葉，折起兩側向上捲一圈。在前方排入三瓣蝦仁（紅色皮朝下），繼續捲緊米紙呈長卷狀。", duration: 5 },
      { instruction: "重複步驟做好所有春卷，佐以調好嘅越式酸辣魚露沾汁食用。", duration: 3 },
    ],
    tags: ["海鮮", "蔬菜", "健康", "低卡", "簡單", "30 分鐘內"],
  },
  {
    name: "新加坡叻沙湯麵",
    description: "新加坡靈魂湯麵（Laksa）！油麵與粗米粉雙拼，濃郁椰奶同叻沙醬慢燉豆卜、鮮蝦同魚餅，椰香滿溢，極其道地。",
    cookTime: 25,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "粗米粉", quantity: "75", unit: "克", category: "其他" },
      { name: "油麵", quantity: "75", unit: "克", category: "其他" },
      { name: "鮮蝦", quantity: "4", unit: "隻", category: "海鮮" },
      { name: "魚餅/魚片", quantity: "80", unit: "克", category: "海鮮" },
      { name: "油豆腐/豆卜（切半）", quantity: "6", unit: "個", category: "其他" },
      { name: "水煮蛋（切半）", quantity: "1", unit: "隻", category: "其他" },
      { name: "生豆芽", quantity: "50", unit: "克", category: "蔬菜" },
      { name: "叻沙醬膏（Laksa Paste）", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "濃椰奶", quantity: "150", unit: "毫升", category: "其他" },
      { name: "雞湯或水", quantity: "500", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "粗米粉同油麵分別汆水煮熟，瀝乾盛入大碗備用。豆卜切半（方便吸汁），魚餅切片，水煮蛋去殼切半。", duration: 10 },
      { instruction: "熱鑊下油小火炒香叻沙醬，倒入雞湯同豆卜煮滾，轉小火慢火滾煮5分鐘，讓豆卜充分吸收湯汁。", duration: 5 },
      { instruction: "倒入椰奶攪勻，放入鮮蝦、魚餅片同豆芽，中火煮3分鐘至鮮蝦變紅、海鮮熟透，加少許鹽調味。", duration: 5 },
      { instruction: "將鮮滾的叻沙椰奶湯、鮮蝦、魚餅、豆卜及豆芽均勻澆在裝有米粉與油麵的大碗中，最後在表面整齊擺上切半的水煮蛋即成。", duration: 5 },
    ],
    tags: ["海鮮", "香辣", "中等", "30 分鐘內", "經典"],
  },
  {
    name: "馬來沙嗲雞肉串",
    description: "雞肉切小塊用黃薑粉、香茅、大蒜醃製，串起烤至焦香，蘸上濃郁甜美、帶有碎花生嘅沙嗲醬，南洋街頭必食。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "無骨雞髀肉", quantity: "350", unit: "克", category: "肉類" },
      { name: "黃薑粉/香茅粉/蒜泥", quantity: "各1", unit: "茶匙", category: "調味料" },
      { name: "砂糖/生抽/蜂蜜", quantity: "適量", unit: "", category: "調味料" },
      { name: "現成沙嗲醬", quantity: "4", unit: "湯匙", category: "調味料" },
      { name: "烤竹籤", quantity: "適量", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "雞髀肉切長條或一口塊。加入黃薑粉、香茅粉、蒜泥、生抽、蜂蜜醃至少1小時（竹籤用溫水浸泡防烤焦）。", duration: 15 },
      { instruction: "用竹籤將雞肉塊折疊串緊。焗爐預熱200度，或用燒烤鐵盤燒熱抹油。", duration: 5 },
      { instruction: "將雞肉串放入，高溫烤或煎烤8-10分鐘，期間翻面，至兩面帶焦焦色且熟透。", duration: 8 },
      { instruction: "趁熱上碟，佐以小黃瓜片、洋蔥塊同溫熱嘅香濃沙嗲醬（帶碎花生）沾用。", duration: 2 },
    ],
    tags: ["香脆", "特色", "送酒", "中等"],
  },
  {
    name: "泰式芒果糯米飯",
    description: "椰香甜滑！泰國香糯米浸透椰奶、椰糖蒸熟，配上清甜多汁嘅泰國芒果，淋上濃郁鹹甜椰漿，泰地道甜品。",
    cookTime: 40,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "東南亞",
    ingredients: [
      { name: "泰國長糯米（浸泡4小時）", quantity: "150", unit: "克", category: "其他" },
      { name: "新鮮清甜熟芒果", quantity: "2", unit: "個", category: "蔬菜" },
      { name: "濃椰奶（椰漿）", quantity: "200", unit: "毫升", category: "其他" },
      { name: "椰糖或白糖", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "綠豆仁（炸熟）/斑蘭葉", quantity: "少許", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "糯米浸足4小時，瀝乾。糯米拌入斑蘭葉在大火蒸鍋中蒸25-30分鐘至熟透軟糯。", duration: 30 },
      { instruction: "調椰漿汁：椰奶、糖、鹽小火煮熱至糖溶（保留一半做面醬，其餘倒入大碗）。", duration: 5 },
      { instruction: "將熱糯米飯倒入裝有椰漿汁嘅大碗中拌勻，蓋蓋燜15分鐘使糯米飯完全吸飽椰奶。", duration: 15 },
      { instruction: "芒果削皮切厚片排盤，盛起一團椰香糯米飯在旁，淋上餘下嘅濃稠面椰漿，撒熟綠豆仁（或芝麻）即成。", duration: 5 },
    ],
    tags: ["清甜", "簡單", "30 分鐘以上"],
  },
];
