export const HK_STIRFRY_RECIPES = [
  {
    name: "西芹炒雞柳",
    description: "爽脆嘅西芹配上滑溜雞柳，爽口清淡，極具家庭風味嘅快手健康餸。",
    cookTime: 15,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "西芹", quantity: "200", unit: "克", category: "蔬菜" },
      { name: "雞胸肉或雞髀肉", quantity: "200", unit: "克", category: "肉類" },
      { name: "胡蘿蔔片/薑片", quantity: "少許", unit: "", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "西芹去老筋切斜片，雞肉切條用生抽、生粉醃15分鐘。", duration: 15 },
      { instruction: "燒熱油，落雞柳大火快速炒至變色熟透，盛起。", duration: 3 },
      { instruction: "同一鑊，爆香薑片，放入西芹同胡蘿蔔片大火翻炒2分鐘。", duration: 2 },
      { instruction: "倒回雞柳，加鹽調味，快速翻炒勻即可上碟。", duration: 1 },
    ],
    tags: ["港式", "家常菜", "炒", "清淡", "健康", "15 分鐘內", "快手", "簡單"],
  },
  {
    name: "西芹炒牛肉",
    description: "牛肉嫩滑、西芹爽脆，兩者味道互相烘托，鑊氣十足，健康又香濃。",
    cookTime: 15,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "西芹", quantity: "200", unit: "克", category: "蔬菜" },
      { name: "牛肉片", quantity: "200", unit: "克", category: "肉類" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "蠔油", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "西芹去筋切斜段。牛肉片用生抽、糖、生粉、1茶匙油醃15分鐘。", duration: 15 },
      { instruction: "大火燒熱鑊，落油，放入牛肉片快速爆炒至八成熟，盛起備用。", duration: 2 },
      { instruction: "落少許油爆香薑蒜，加入西芹大火炒2分鐘至爽脆。", duration: 2 },
      { instruction: "倒回牛肉，加入蠔油快速翻炒均勻，一分鐘內出碟，保持牛肉滑嫩。", duration: 1 },
    ],
    tags: ["港式", "家常菜", "炒", "15 分鐘內", "快手", "簡單", "滑嫩", "下飯"],
  },
  {
    name: "腰果炒雞丁",
    description: "香脆嘅油炸腰果，配上軟滑雞丁同五彩椒塊，色彩豐富，口感豐富，係廣東宴席名餸。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞髀肉（切丁）", quantity: "250", unit: "克", category: "肉類" },
      { name: "熟腰果", quantity: "50", unit: "克", category: "乾貨" },
      { name: "青椒/紅椒（切丁）", quantity: "各1/2", unit: "個", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "雞丁用生抽、糖同生粉醃15分鐘。彩椒切小塊。", duration: 15 },
      { instruction: "燒熱油，落雞丁中小火炒至表面微黃、熟透，盛起。", duration: 5 },
      { instruction: "爆香少許蔥薑，放彩椒丁翻炒一分鐘。", duration: 1 },
      { instruction: "倒入雞丁同腰果，落少許鹽同蠔油大火快速炒勻即可出鑊。", duration: 2 },
    ],
    tags: ["港式", "經典", "炒", "香脆", "宴客", "簡單", "30 分鐘內"],
  },
  {
    name: "中式牛柳",
    description: "傳統港式西餐與中餐嘅結晶！牛柳厚切極致滑嫩，裹滿酸甜香濃嘅橙紅色醬汁，極具風味。",
    cookTime: 20,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "牛柳肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "洋蔥", quantity: "1/2", unit: "個", category: "蔬菜" },
      { name: "喼汁（Worcestershire sauce）", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "茄汁", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "3", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "牛柳橫紋切厚片，用刀背輕拍。用生抽、生粉、少許水醃製20分鐘。洋蔥切絲。", duration: 20 },
      { instruction: "調醬汁：喼汁、茄汁、糖同2湯匙水攪勻。", duration: 2 },
      { instruction: "大火熱油，落牛柳片快速煎炒至五成熟（表面微黃，內裡微紅），盛起。", duration: 2 },
      { instruction: "爆香洋蔥絲至軟，倒入醬汁煮滾，倒回牛柳，大火翻炒15秒使醬汁掛滿牛肉即可出碟。", duration: 2 },
    ],
    tags: ["港式", "經典", "炒", "酸甜", "滑嫩", "宴客", "中等", "30 分鐘內"],
  },
  {
    name: "黑椒牛仔骨",
    description: "茶餐廳同大牌檔經典，牛仔骨肥美帶油香，配上微辣刺激嘅黑椒碎，鑊氣逼人，香濃無比。",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮牛仔骨", quantity: "350", unit: "克", category: "肉類" },
      { name: "洋蔥", quantity: "1/2", unit: "個", category: "蔬菜" },
      { name: "黑胡椒碎", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蒜蓉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蠔油", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "牛仔骨切件，用生抽、糖同少許生粉醃15分鐘。洋蔥切塊。", duration: 15 },
      { instruction: "熱鑊下油，將牛仔骨平鋪，大火煎香兩面至八成熟，灒入紹興酒，盛起。", duration: 5 },
      { instruction: "爆香蒜蓉、洋蔥塊同大量黑胡椒碎，倒入蠔油同少許水煮滾。", duration: 3 },
      { instruction: "倒回牛仔骨快速大火翻炒，讓黑椒汁掛滿牛仔骨即可。", duration: 2 },
    ],
    tags: ["港式", "經典", "大牌檔", "炒", "香濃", "送酒", "中等"],
  },
  {
    name: "豉汁炒蜆",
    description: "大牌檔必點靈魂小炒！豆豉、蒜頭同辣椒爆發出極限香氣，蜆肉鮮嫩吸汁，下酒一流。",
    cookTime: 20,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮蜆或沙白", quantity: "500", unit: "克", category: "海鮮" },
      { name: "陽江豆豉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蒜頭", quantity: "3", unit: "瓣", category: "調味料" },
      { name: "紅椒（切絲）", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "蔥段", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "生抽/蠔油", quantity: "各1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉水", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "蜆吐沙乾淨，滾水下鍋汆水至剛好張口，立刻撈起瀝乾（防縮水變老）。", duration: 8 },
      { instruction: "豆豉蒜頭剁碎。燒熱油爆香豉蒜蓉、紅椒絲同蔥段。", duration: 3 },
      { instruction: "下蜆肉，轉大火快速翻炒，加入生抽、蠔油、糖調味。", duration: 2 },
      { instruction: "倒入生粉水勾芡，使濃郁豉汁緊緊包裹住蜆殼，即可上碟。", duration: 2 },
    ],
    tags: ["港式", "經典", "大牌檔", "炒", "海鮮", "鮮味", "送酒", "中等"],
  },
  {
    name: "豉椒炒牛肉",
    description: "濃郁豆豉同清脆青椒與嫩滑牛肉爆炒，醬汁微辣鹹香，鑊氣蒸騰，下飯第一名。",
    cookTime: 15,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "牛肉片", quantity: "200", unit: "克", category: "肉類" },
      { name: "青椒", quantity: "1", unit: "個", category: "蔬菜" },
      { name: "豆豉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蒜蓉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "牛肉加生抽、糖、生粉醃15分鐘。青椒切塊。豆豉蒜頭拍碎。", duration: 15 },
      { instruction: "大火熱油，落牛肉片爆炒至六成熟，盛起。", duration: 2 },
      { instruction: "鑊中落少許油爆香豆豉蒜蓉，下青椒塊大火炒至斷生。", duration: 2 },
      { instruction: "倒回牛肉，灒少許水同生抽，大火爆炒勻即可出碟。", duration: 1 },
    ],
    tags: ["港式", "家常菜", "炒", "鹹香", "15 分鐘內", "快手", "下飯"],
  },
  {
    name: "豉椒苦瓜炒牛肉",
    description: "甘苦清熱嘅苦瓜，經過豆豉蒜蓉爆炒，帶出牛肉嘅鮮甜，苦中帶甘，極具層次。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "苦瓜", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "牛肉片", quantity: "200", unit: "克", category: "肉類" },
      { name: "豆豉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蒜蓉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "苦瓜去籽切薄片，用少許鹽醃5分鐘洗淨去苦味。牛肉加生抽生粉醃15分鐘。", duration: 15 },
      { instruction: "牛肉落鑊爆炒至八成熟盛起。苦瓜入沸水汆水10秒撈起。", duration: 3 },
      { instruction: "鑊中落油爆香豆豉蒜蓉，落苦瓜大火快炒。", duration: 2 },
      { instruction: "倒入牛肉，加糖、生抽，大火快速炒勻即可。", duration: 2 },
    ],
    tags: ["港式", "家常菜", "炒", "蔬菜", "滋補", "簡單", "30 分鐘內"],
  },
  {
    name: "菜脯炒蛋",
    description: "潮州風味家常菜，鹹香清脆嘅菜脯碎融入香軟煎蛋中，成本低廉卻美味無比。",
    cookTime: 10,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞蛋", quantity: "4", unit: "隻", category: "其他" },
      { name: "甜菜脯或鹹菜脯", quantity: "50", unit: "克", category: "蔬菜" },
      { name: "蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "鹽", quantity: "少許", unit: "", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "菜脯反覆清洗去沙並切細碎。雞蛋打散拌入蔥花、糖同少許鹽。", duration: 5 },
      { instruction: "白鑊（不放油）下菜脯碎慢火烘乾炒香，盛起放入蛋液中攪勻。", duration: 3 },
      { instruction: "燒熱油鑊，倒入菜脯蛋液，中小火慢煎至兩面金黃熟透即可切塊上碟。", duration: 5 },
    ],
    tags: ["港式", "家常菜", "炒", "鹹香", "15 分鐘內", "快手", "簡單", "新手"],
  },
  {
    name: "韭黃炒蛋",
    description: "韭黃比普通韭菜更清甜細嫩，蛋香與韭黃嘅清香完美融合，滑軟無比，家常清爽餸。",
    cookTime: 10,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞蛋", quantity: "4", unit: "隻", category: "其他" },
      { name: "韭黃", quantity: "100", unit: "克", category: "蔬菜" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "韭黃洗淨切段。雞蛋打散加少許鹽調味。", duration: 5 },
      { instruction: "燒熱1湯匙油，下韭黃大火快炒10秒至剛軟，盛起，瀝乾水分放入蛋液中攪勻。", duration: 2 },
      { instruction: "重新燒熱鑊，下1.5湯匙油，倒入蛋液韭黃，快速用筷子撥動至雞蛋半熟，呈嫩滑狀立刻出碟。", duration: 3 },
    ],
    tags: ["港式", "家常菜", "炒", "蔬菜", "清淡", "15 分鐘內", "快手", "簡單"],
  },
  {
    name: "韭菜花炒豬頸肉",
    description: "爽脆多汁嘅韭菜花，搭配爽滑帶油香嘅豬頸肉（松阪肉），爆炒出強烈嘅鑊氣與香氣。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮豬頸肉", quantity: "200", unit: "克", category: "肉類" },
      { name: "韭菜花", quantity: "150", unit: "克", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "蠔油", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "1.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "豬頸肉切薄片，用生抽、糖同生粉醃15分鐘。韭菜花洗淨切段。", duration: 15 },
      { instruction: "熱油爆香蒜片，下豬頸肉片大火炒至兩面微焦黃且熟透，盛起。", duration: 5 },
      { instruction: "下韭菜花大火翻炒1分鐘，倒回豬頸肉，落蠔油快速大火爆炒均勻即可。", duration: 2 },
    ],
    tags: ["港式", "家常菜", "炒", "30 分鐘內", "下飯", "香濃", "簡單"],
  },
  {
    name: "蝦醬炒鮮魷",
    description: "大牌檔漁家風味，鹹香濃郁嘅大澳蝦醬與爽脆彈牙嘅鮮魷魚爆炒，味道震撼，香氣飄街。",
    cookTime: 15,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮魷魚", quantity: "300", unit: "克", category: "海鮮" },
      { name: "大澳蝦醬", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蒜茸/薑片", quantity: "適量", unit: "", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "魷魚去皮切圈，飛水5秒鐘洗去多餘黏液瀝乾。蝦醬與糖、紹興酒混勻。", duration: 8 },
      { instruction: "燒熱油，爆香蒜茸薑片，落蝦醬炒香至起沙。", duration: 2 },
      { instruction: "倒入鮮魷魚圈，轉大火極速翻炒30秒，讓蝦醬緊裹魷魚即可出碟。", duration: 2 },
    ],
    tags: ["港式", "經典", "大牌檔", "炒", "海鮮", "鹹香", "送酒", "中等"],
  },
  {
    name: "九層塔炒蜆",
    description: "九層塔（羅勒）香氣強烈誘人，配上鮮甜多汁嘅蜆肉，大火爆炒，異國香草與中式鑊氣嘅結合。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮蜆或沙白", quantity: "500", unit: "克", category: "海鮮" },
      { name: "九層塔（羅勒葉）", quantity: "1", unit: "大束", category: "蔬菜" },
      { name: "蒜頭", quantity: "3", unit: "瓣", category: "調味料" },
      { name: "紅辣椒", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "蜆汆水至半張口撈出。九層塔洗淨摘葉。蒜頭切片辣椒切斜片。", duration: 10 },
      { instruction: "大火熱油，爆香蒜片辣椒，下蜆肉翻炒幾下。", duration: 2 },
      { instruction: "加入生抽、糖及九層塔葉，大火猛火翻炒至九層塔變軟、蜆殼全開即可。", duration: 3 },
    ],
    tags: ["港式", "大牌檔", "炒", "海鮮", "香草", "鮮味", "送酒", "簡單", "30 分鐘內"],
  },
  {
    name: "炒三鮮",
    description: "蝦仁、帶子、鮮魷合稱三鮮，口感爽口、鮮甜、彈牙互補，精緻高檔嘅港式海鮮小炒。",
    cookTime: 20,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "鮮蝦仁", quantity: "120", unit: "克", category: "海鮮" },
      { name: "鮮帶子", quantity: "120", unit: "克", category: "海鮮" },
      { name: "鮮魷魚（切塊）", quantity: "120", unit: "克", category: "海鮮" },
      { name: "荷蘭豆", quantity: "50", unit: "克", category: "蔬菜" },
      { name: "鹽/生粉", quantity: "適量", unit: "", category: "調味料" },
      { name: "薑汁/紹興酒", quantity: "適量", unit: "", category: "調味料" },
      { name: "食油", quantity: "2.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "三鮮洗淨抹乾，用少許鹽、生粉、紹興酒醃10分鐘。荷蘭豆撕去老筋。", duration: 10 },
      { instruction: "將三鮮分別下油鑊快速過油至六成熟，盛起瀝乾。", duration: 4 },
      { instruction: "爆香薑片，入荷蘭豆炒1分鐘，倒入三鮮，加少許鹽、水勾薄芡，大火兜勻即可。", duration: 3 },
    ],
    tags: ["港式", "經典", "炒", "海鮮", "鮮味", "宴客", "進階"],
  },
  {
    name: "生炒芥蘭",
    description: "大牌檔極限火候！芥蘭經高溫猛火生炒，灒入紹興酒同少許糖，爽脆無比，帶有獨特焦香。",
    cookTime: 15,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "芥蘭", quantity: "300", unit: "克", category: "蔬菜" },
      { name: "薑片", quantity: "3", unit: "片", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "芥蘭洗淨，粗梗削去外皮刨絲或切片，保持易熟爽脆。", duration: 5 },
      { instruction: "大火熱鑊，落多啲油，爆香薑片。放入芥蘭大火極速翻炒2分鐘。", duration: 3 },
      { instruction: "加入鹽同糖，沿着鑊邊灒入紹興酒（激發酒香與鑊氣），快速翻炒幾下起碟。", duration: 2 },
    ],
    tags: ["港式", "家常菜", "大牌檔", "炒", "蔬菜", "簡單", "15 分鐘內", "快手"],
  },
  {
    name: "椒絲腐乳炒通菜",
    description: "大牌檔素菜之王！腐乳嘅鹹香、紅椒絲嘅微辣，配合大火生炒極其清脆嘅通菜，絕配！",
    cookTime: 10,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "空心菜（通菜）", quantity: "350", unit: "克", category: "蔬菜" },
      { name: "白腐乳", quantity: "2", unit: "塊", category: "調味料" },
      { name: "紅辣椒（切絲）", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "蒜頭", quantity: "3", unit: "瓣", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "通菜洗淨摘段瀝乾。腐乳壓泥與糖、少許水攪勻。蒜頭切碎。", duration: 5 },
      { instruction: "猛火燒熱油，爆香蒜頭同辣椒絲，倒入腐乳泥炒出香氣。", duration: 2 },
      { instruction: "倒入通菜，立刻轉大火極速翻炒至通菜剛變軟，隨即出碟（防通菜出水變黑）。", duration: 3 },
    ],
    tags: ["港式", "家常菜", "大牌檔", "炒", "蔬菜", "鹹香", "15 分鐘內", "簡單"],
  },
  {
    name: "蔥爆牛肉",
    description: "大量大蔥、小蔥與嫩滑牛肉爆炒，蔥香深入肉絲，肉質香滑，經典北方風味在港嘅大牌檔演變。",
    cookTime: 15,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "牛肉片", quantity: "250", unit: "克", category: "肉類" },
      { name: "京蔥（大蔥）", quantity: "1", unit: "棵", category: "蔬菜" },
      { name: "生抽/老抽", quantity: "各1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "牛肉加生抽、老抽、糖、生粉、水醃製15分鐘。京蔥斜切厚片。", duration: 15 },
      { instruction: "大火熱油，落牛肉片極速爆炒20秒至微變色盛起。", duration: 1 },
      { instruction: "下京蔥片大火炒出濃烈蔥香（約1分鐘）。", duration: 2 },
      { instruction: "倒入牛肉大火翻炒兜勻即可上碟。", duration: 1 },
    ],
    tags: ["港式", "大牌檔", "炒", "滑嫩", "簡單", "15 分鐘內", "下飯"],
  },
  {
    name: "金沙鹹蛋黃炒蝦仁",
    description: "鹹蛋黃炒至起沙呈金黃色，緊緊包裹住爽脆嘅鮮蝦仁，金沙油香，極致邪惡惹味。",
    cookTime: 20,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "鮮蝦仁", quantity: "200", unit: "克", category: "海鮮" },
      { name: "鹹蛋黃", quantity: "3", unit: "個", category: "其他" },
      { name: "生粉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖/鹽", quantity: "少許", unit: "", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "鹹蛋黃蒸熟壓成泥。蝦仁用少許鹽同生粉醃10分鐘，下鍋煎至變色剛熟，盛起。", duration: 12 },
      { instruction: "熱鑊落油，小火下鹹蛋黃泥慢火煸炒，至蛋黃冒出大量泡泡「起沙」。", duration: 3 },
      { instruction: "立刻倒入蝦仁，落少許糖，快速顛鑊使金黃蛋黃金沙均勻沾滿蝦仁表面即可。", duration: 2 },
    ],
    tags: ["港式", "經典", "炒", "海鮮", "鹹香", "特色", "中等", "30 分鐘內"],
  },
  {
    name: "薑蔥炒蟹",
    description: "香港海鮮酒家必點大餸！肉質鮮嫩肥美嘅螃蟹，與大量老薑、蔥段爆炒，鮮甜中帶微辣薑香。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮肉蟹或花蟹", quantity: "1", unit: "隻", category: "海鮮" },
      { name: "老薑（切片）", quantity: "8", unit: "片", category: "調味料" },
      { name: "蔥段", quantity: "2", unit: "棵", category: "蔬菜" },
      { name: "生粉", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "蠔油", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "3", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "螃蟹洗淨斬件，蟹螯拍裂（方便入味同咬開）。切口處沾上生粉鎖住肉汁。", duration: 15 },
      { instruction: "熱油落蟹件大火煎炸至變紅、肉質凝固，盛起。", duration: 5 },
      { instruction: "爆香大量薑片、拍扁蒜頭同部分蔥段，倒回蟹件，灒入紹興酒爆炒。", duration: 3 },
      { instruction: "加入蠔油、少許水同剩餘蔥段，蓋蓋小火燜2分鐘，最後大火收汁裝碟。", duration: 4 },
    ],
    tags: ["港式", "經典", "海鮮", "薑蔥", "鮮味", "宴客", "進階", "送酒"],
  },
  {
    name: "避風塘炒蟹",
    description: "避風塘海鮮代表作！極香嘅金黃炸蒜酥（避風塘蒜酥）配上紅辣椒爆炒巨蟹，酥香辣味直衝靈魂。",
    cookTime: 35,
    servings: 4,
    difficulty: "困難",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮肉蟹", quantity: "1", unit: "隻", category: "海鮮" },
      { name: "蒜蓉（大量，作炸蒜）", quantity: "1", unit: "碗", category: "調味料" },
      { name: "乾辣椒/豆豉", quantity: "適量", unit: "", category: "調味料" },
      { name: "麵包糠", quantity: "3", unit: "湯匙", category: "其他" },
      { name: "椒鹽粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "肉蟹斬件拍裂蟹螯。蒜蓉用中小火炸至金黃酥脆（金蒜），撈起瀝乾防焦。麵包糠亦炒乾香。", duration: 15 },
      { instruction: "蟹件切口沾生粉，下高溫油中大火炸5分鐘至酥脆，撈起。", duration: 5 },
      { instruction: "鑊留底油，炒香豆豉同乾辣椒碎，倒入炸蟹、炸蒜酥、麵包糠及椒鹽粉。", duration: 3 },
      { instruction: "大火猛火顛鑊翻炒均勻，使蒜酥與香辣味裹滿蟹身即可堆高上碟。", duration: 2 },
    ],
    tags: ["港式", "經典", "炒", "海鮮", "香辣", "宴客"],
  },
];
