export const INTL_WESTERN_DESSERT_RECIPES = [
  // ─── WESTERN CLASSICS (12) ──────────────────────────────────────────────────
  {
    name: "番茄肉醬意粉",
    description: "最受歡迎嘅西餐家庭料理！牛肉豬肉與多種香草、番茄慢火燉煮出極致香濃嘅 Bolognese 醬汁。",
    cookTime: 45,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "意大利粉", quantity: "250", unit: "克", category: "其他" },
      { name: "免治牛肉", quantity: "150", unit: "克", category: "肉類" },
      { name: "免治豬肉", quantity: "100", unit: "克", category: "肉類" },
      { name: "番茄膏/番茄罐頭", quantity: "各2", unit: "湯匙/罐", category: "調味料" },
      { name: "洋蔥/胡蘿蔔/西芹（切極細碎）", quantity: "各1/2", unit: "個", category: "蔬菜" },
      { name: "蒜頭", quantity: "2", unit: "瓣", category: "調味料" },
      { name: "紅酒", quantity: "50", unit: "毫升", category: "調味料" },
    ],
    steps: [
      { instruction: "洋蔥、胡蘿蔔、西芹切極細碎。熱鍋下油爆香蒜頭、洋蔥碎炒香。", duration: 8 },
      { instruction: "倒入免治牛肉及豬肉，大火炒散至水分乾身微黃。加入紅酒大火揮發酒精。", duration: 5 },
      { instruction: "加入胡蘿蔔、西芹碎同番茄罐頭、番茄膏，加入香草及少許水煮滾，轉小火蓋蓋慢火燜煮30分鐘。", duration: 30 },
      { instruction: "意粉煮熟瀝乾。將意粉倒入肉醬鑊中，快速大火翻炒兜勻即可上碟，撒芝士粉。", duration: 2 },
    ],
    tags: ["西餐", "經典", "意粉", "肉醬", "番茄", "家庭料理", "小朋友", "簡單", "30 分鐘以上"],
  },
  {
    name: "凱撒沙律",
    description: "經典輕食！爽脆羅馬生菜淋上香濃凱撒沙律醬，鋪上香脆麵包丁同香煎煙肉碎，清爽惹味。",
    cookTime: 15,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "羅馬生菜", quantity: "1", unit: "棵", category: "蔬菜" },
      { name: "煙肉（培根，切碎）", quantity: "2", unit: "片", category: "肉類" },
      { name: "吐司麵包（切丁）", quantity: "1", unit: "片", category: "其他" },
      { name: "凱撒沙律醬", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "帕馬森芝士碎", quantity: "少許", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "生菜洗淨徹底瀝乾（沙律爽脆關鍵），切大段。煙肉片切碎，烘乾至焦脆脆。", duration: 8 },
      { instruction: "吐司切丁用少許牛油或橄欖油在平底鍋上煎烤至金黃香脆（麵包丁）。", duration: 4 },
      { instruction: "大碗中放入生菜，淋入凱撒沙律醬輕輕抓拌均勻。", duration: 2 },
      { instruction: "表面排上香脆麵包丁、煙肉碎同帕馬森芝士碎即可裝盤。", duration: 1 },
    ],
    tags: ["西餐", "沙律", "健康", "低卡", "清爽", "快手", "簡單", "15 分鐘內", "輕食"],
  },
  {
    name: "香煎三文魚配檸檬牛油汁",
    description: "三文魚皮煎至極致酥脆，肉質保持粉紅粉嫩，淋上微酸開胃、黃澄澄嘅檸檬牛油汁，高雅精緻。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "新鮮三文魚扒", quantity: "2", unit: "塊", category: "海鮮" },
      { name: "牛油", quantity: "30", unit: "克", category: "調味料" },
      { name: "新鮮檸檬汁", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "鹽/黑胡椒", quantity: "少許", unit: "", category: "調味料" },
      { name: "蘆筍（伴碟）", quantity: "適量", unit: "", category: "蔬菜" },
    ],
    steps: [
      { instruction: "三文魚用廚房紙徹底印乾，魚皮上抹少許鹽同黑胡椒醃10分鐘。蘆筍汆水煎熟。", duration: 10 },
      { instruction: "熱鑊下少許橄欖油，魚皮向下放入三文魚，中火慢煎3-4分鐘至魚皮金黃極硬脆。", duration: 4 },
      { instruction: "翻面，繼續煎2-3分鐘至八成熟，取出擺盤。", duration: 3 },
      { instruction: "同一鑊倒入牛油小火熔化，加檸檬汁同少許鹽煮滾起泡泡（檸檬牛油汁），淋在三文魚表面即成。", duration: 3 },
    ],
    tags: ["西餐", "海鮮", "魚", "三文魚", "香脆", "精緻", "宴客", "簡單", "30 分鐘內", "高蛋白"],
  },
  {
    name: "經典西冷牛排",
    description: "美式扒房風味！厚切西冷牛扒高溫香煎，表面焦黃、帶有迷人梅納香氣，牛油百里香香氣入裡。",
    cookTime: 20,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "西餐",
    ingredients: [
      { name: "厚切西冷牛排", quantity: "1", unit: "塊", category: "肉類" },
      { name: "牛油", quantity: "20", unit: "克", category: "調味料" },
      { name: "蒜頭（拍扁連皮）", quantity: "2", unit: "瓣", category: "調味料" },
      { name: "新鮮百里香/迷迭香", quantity: "少許", unit: "", category: "調味料" },
      { name: "粗鹽/粗黑胡椒碎", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "牛排提前30分鐘從冰箱取出，完全回溫（關鍵）。表面均勻撒上粗鹽同黑胡椒壓實。", duration: 10 },
      { instruction: "鐵平底鑊（條紋鑊最佳）燒至極高溫（冒青煙），下少許油，放入牛排大火每面各煎1.5分鐘（五成熟）。", duration: 3 },
      { instruction: "轉中小火，下牛油、百里香、蒜頭，傾斜鐵鑊，用勺子不斷將融化嘅牛油澆在牛排表面（Arrosé），兩面澆1分鐘。", duration: 3 },
      { instruction: "取出，放在溫熱盤上靜置（Rest）5分鐘（鎖緊肉汁），切厚片即可享用。", duration: 4 },
    ],
    tags: ["西餐", "經典", "牛排", "牛肉", "高級", "多汁", "送酒", "宴客", "中等", "30 分鐘內"],
  },
  {
    name: "白汁煙肉意粉",
    description: "經典 Carbonara！不加忌廉，僅用生蛋黃、帕馬森芝士碎同焦脆煙肉汁乳化成無敵香濃嘅白汁，意大利正宗做法。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "意大利粉", quantity: "200", unit: "克", category: "其他" },
      { name: "煙肉片（培根）", quantity: "3", unit: "片", category: "肉類" },
      { name: "生蛋黃", quantity: "2", unit: "隻", category: "其他" },
      { name: "全蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "帕馬森芝士粉/黑胡椒碎", quantity: "3湯匙/適量", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "意粉大滾水加鹽煮至八成熟。煙肉切碎。蛋黃、全蛋同大量芝士粉在碗中攪勻成蛋黃芝士糊。", duration: 10 },
      { instruction: "熱平底鑊（不放油）慢火將煙肉碎煸炒出多餘油脂，至煙肉焦黃。關火。", duration: 4 },
      { instruction: "將煮好嘅熱意粉倒入煙肉油中拌勻，加入2湯匙煮意粉嘅熱水。", duration: 2 },
      { instruction: "稍微降溫（關鍵，太熱蛋黃會變蛋花），倒入蛋黃芝士糊，快速翻拌，利用餘溫融化芝士、蛋黃乳化呈濃稠醬汁，撒大量黑胡椒即可。", duration: 4 },
    ],
    tags: ["西餐", "經典", "意粉", "白汁", "芝士", "簡單", "30 分鐘內", "家常", "小朋友", "一人食"],
  },
  {
    name: "蒜香橄欖油大蝦意粉",
    description: "經典 Spaghetti Aglio e Olio！頂級橄欖油、金黃蒜片同辣椒絲爆香，配上爽口海大蝦，清爽辛辣，鑊氣十足。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "意大利粉", quantity: "180", unit: "克", category: "其他" },
      { name: "大鮮蝦仁", quantity: "8", unit: "隻", category: "海鮮" },
      { name: "特級初榨橄欖油", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "蒜頭（切薄片）", quantity: "4", unit: "瓣", category: "調味料" },
      { name: "乾紅椒碎/香菜碎", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "意粉煮至八成軟。蝦仁洗淨抹乾。蒜頭切成均勻薄片。", duration: 10 },
      { instruction: "冷鑊下大量橄欖油同蒜片，極小火慢煎至蒜片邊緣微呈金黃（激發蒜油香氣，不可燒焦），下紅椒碎。", duration: 5 },
      { instruction: "放入蝦仁轉中火煎熟。倒入煮好嘅意粉，灒入2湯匙意粉水大火搖動平底鑊使油水乳化黏附在麵條上。", duration: 3 },
      { instruction: "撒香菜碎快速翻勻盛盤即可。", duration: 2 },
    ],
    tags: ["西餐", "意粉", "橄欖油", "海鮮", "大蝦", "蒜香", "微辣", "快手", "簡單", "30 分鐘內"],
  },
  {
    name: "法式白汁燉雞",
    description: "法式名菜 Fricassee！雞脾肉煎香，與白蘑菇在濃郁香滑嘅白醋忌廉白汁中慢火細燉，滑嫩醇厚。",
    cookTime: 45,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "西餐",
    ingredients: [
      { name: "無骨雞髀肉件", quantity: "400", unit: "克", category: "肉類" },
      { name: "白蘑菇", quantity: "100", unit: "克", category: "蔬菜" },
      { name: "淡忌廉（鮮奶油）", quantity: "100", unit: "毫升", category: "其他" },
      { name: "白葡萄酒/雞湯", quantity: "50毫升/200毫升", unit: "", category: "其他" },
      { name: "洋蔥碎/牛油", quantity: "適量", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "雞件用鹽胡椒略醃。蘑菇切厚片，洋蔥切碎。", duration: 10 },
      { instruction: "熱鍋融化牛油，下雞件大火煎至皮金黃（約5分鐘），盛起。爆香洋蔥、白蘑菇片。", duration: 8 },
      { instruction: "倒入白葡萄酒大火揮發，加入雞湯同雞件，中火燒開轉小火，蓋蓋燉20分鐘至雞肉熟透。", duration: 20 },
      { instruction: "倒入淡忌廉攪拌均勻，小火慢煮5分鐘至白汁濃稠，落少許鹽和黑胡椒調味即成。", duration: 7 },
    ],
    tags: ["西餐", "法式", "燉雞", "白汁", "蘑菇", "忌廉", "香濃", "慢煮", "30 分鐘以上", "中等"],
  },
  {
    name: "經典芝士漢堡",
    description: "手打 100% 免治牛肉餅高溫香煎鎖汁，蓋上融化嘅車打芝士片，夾入香烤小餐包，經典美式風味。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "手打純牛肉漢堡肉餅", quantity: "2", unit: "塊", category: "肉類" },
      { name: "車打芝士片", quantity: "2", unit: "張", category: "其他" },
      { name: "漢堡小餐包（Bun）", quantity: "2", unit: "個", category: "其他" },
      { name: "酸黃瓜片/番茄片/生菜", quantity: "少許", unit: "", category: "蔬菜" },
      { name: "漢堡醬/千島醬", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "漢堡肉餅抹上鹽黑胡椒。餐包橫切面用牛油略煎至金黃焦香。", duration: 8 },
      { instruction: "熱平底鑊大火，下肉餅每面各煎2分鐘鎖汁。翻面時立刻蓋上車打芝士片，蓋蓋小火焗30秒讓芝士融化。", duration: 5 },
      { instruction: "餐包底塗漢堡醬，依次鋪生菜、番茄片、芝士牛肉餅、酸黃瓜片，蓋上餐包蓋即可趁熱咬食。", duration: 7 },
    ],
    tags: ["西餐", "漢堡", "牛肉", "芝士", "美式", "香脆", "多汁", "小朋友", "簡單", "30 分鐘內"],
  },
  {
    name: "美式BBQ烤豬肋骨",
    description: "厚實豬肋骨抹上秘製美式乾醃料慢火烤熟，反覆刷上濃郁鹹甜、帶煙燻焦香嘅BBQ醬，肉質軟爛脫骨。",
    cookTime: 120,
    servings: 4,
    difficulty: "困難",
    recipeCategory: "西餐",
    ingredients: [
      { name: "優質整排豬肋排", quantity: "800", unit: "克", category: "肉類" },
      { name: "美式BBQ燒烤醬", quantity: "1/2", unit: "瓶", category: "調味料" },
      { name: "美式乾醃料（辣椒粉/洋蔥粉/黑糖）", quantity: "適量", unit: "", category: "調味料" },
      { name: "白醋/蘋果汁", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "豬肋骨撕去背面薄膜（肉質軟嫩關鍵），均勻塗抹上乾醃料，用錫紙包裹密封醃製2小時。", duration: 15 },
      { instruction: "焗爐預熱150度。錫紙包裹嘅豬肋骨放入，低溫慢火焗烤1.5小時至肉質軟爛脫骨。", duration: 90 },
      { instruction: "取出，打開錫紙。表面均勻刷上厚厚一層美式BBQ燒烤醬。", duration: 5 },
      { instruction: "焗爐調至200度，敞開錫紙烤烤10分鐘，翻面刷醬再烤5分鐘至表面焦黃、醬汁起泡起微焦即可切開上碟。", duration: 10 },
    ],
    tags: ["西餐", "經典", "烤肉", "豬排", "BBQ", "香濃", "慢煮", "宴客", "60 分鐘以上", "困難"],
  },
  {
    name: "焗芝士菠菜",
    description: "清甜菠菜與香軟白汁、大量馬蘇里拉芝士一同焗烤，外皮呈現金黃拉絲，香氣濃郁，經典美味配菜。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "新鮮菠菜", quantity: "300", unit: "克", category: "蔬菜" },
      { name: "白汁醬（牛油/麵粉/牛奶）", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "馬蘇里拉芝士碎（Mozzarella）", quantity: "1/2", unit: "杯", category: "其他" },
      { name: "蒜蓉/鹽/黑胡椒", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "菠菜洗淨大滾水飛水30秒，撈起立刻過冷水，用雙手極度用力捏乾水分（關鍵，防焗時出水變淡），切碎。爆香蒜蓉下菠菜略炒加少許鹽。", duration: 10 },
      { instruction: "焗盤底部鋪上炒好嘅菠菜，淋入滑順白汁攪勻拌平。", duration: 3 },
      { instruction: "表面鋪滿厚厚一層馬蘇里拉芝士碎。", duration: 2 },
      { instruction: "放入預熱200度嘅焗爐中，焗烤8-10分鐘至表面芝士融化呈金黃斑點起微焦即可。", duration: 5 },
    ],
    tags: ["西餐", "芝士", "焗", "蔬菜", "菠菜", "拉絲", "清甜", "簡單", "30 分鐘內", "小朋友"],
  },
  {
    name: "經典瑪格麗特薄餅",
    description: "意式 Pizza 靈魂！煙韌手工餅底塗上香濃番茄醬，放上新鮮馬蘇里拉芝士與羅勒葉，高溫烘烤，清爽醇厚。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "西餐",
    ingredients: [
      { name: "手工或現成薄餅底", quantity: "1", unit: "張", category: "其他" },
      { name: "意式番茄醬/罐頭番茄泥", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "新鮮馬蘇里拉芝士球（切片）", quantity: "100", unit: "克", category: "其他" },
      { name: "新鮮羅勒葉/特級初榨橄欖油", quantity: "適量", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "現成薄餅底攤平。番茄泥加少許鹽、胡椒粉調味。芝士球切厚片。", duration: 10 },
      { instruction: "薄餅底均勻塗上一層番茄醬。排上馬蘇里拉芝士片、灑上幾片羅勒葉。", duration: 5 },
      { instruction: "高溫220度焗爐烤烤8-10分鐘，至餅底酥脆、芝士完全熔化呈焦黃斑點。", duration: 10 },
      { instruction: "出爐撒新鮮羅勒葉，淋一圈頂級橄欖油切塊享用。", duration: 5 },
    ],
    tags: ["西餐", "意式", "薄餅", "Pizza", "芝士", "番茄", "香脆", "宴客", "中等", "30 分鐘內"],
  },
  {
    name: "牧羊人派",
    description: "英式傳統家庭菜 Shepherd's Pie！香濃免治羊肉或牛肉與多種蔬菜燴煮，鋪上細緻軟滑嘅薯蓉焗烤至微黃焦皮。",
    cookTime: 45,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "西餐",
    ingredients: [
      { name: "免治牛肉或羊肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "薯仔（做薯蓉）", quantity: "2", unit: "個", category: "蔬菜" },
      { name: "洋蔥碎/青豆/胡蘿蔔丁", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "牛油/牛奶", quantity: "各2", unit: "湯匙", category: "其他" },
      { name: "番茄膏/蠔油/生粉水", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "薯仔去皮切大塊蒸熟，用叉壓成泥，加入牛油、牛奶及少許鹽胡椒攪拌成細滑薯蓉。肉碎炒熟與蔬菜丁燴煮成香濃肉醬。", duration: 20 },
      { instruction: "將燴好嘅肉醬鋪在焗盤底層，抹平。", duration: 3 },
      { instruction: "在肉醬上層平鋪上細滑薯蓉，用叉子劃出條紋（焗時更易起脆焦皮）。", duration: 7 },
      { instruction: "放入200度焗爐焗烤15分鐘，至表面薯蓉呈現誘人嘅金黃微焦色即成。", duration: 15 },
    ],
    tags: ["西餐", "英式", "肉醬", "薯蓉", "焗", "香濃", "慢煮", "長者", "中等", "30 分鐘以上"],
  },

  // ─── CANTONESE & GLOBAL DESSERTS (12) ───────────────────────────────────────
  {
    name: "楊枝甘露",
    description: "享譽中外嘅港式甜品巔峰！清甜多汁嘅芒果肉與甘苦解膩嘅柚子肉，融入順滑椰奶同Q彈西米，消暑極品。",
    cookTime: 25,
    servings: 4,
    difficulty: "簡單",
    recipeCategory: "甜品",
    ingredients: [
      { name: "新鮮熟芒果", quantity: "3", unit: "個", category: "蔬菜" },
      { name: "新鮮沙田柚或紅肉西柚", quantity: "2", unit: "瓣", category: "蔬菜" },
      { name: "西米", quantity: "80", unit: "克", category: "其他" },
      { name: "椰奶/淡奶/椰糖水", quantity: "各100", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "大滾水下西米中火煮12分鐘至僅剩一點白心，關火燜15分鐘至全透明，撈出沖冰水瀝乾。", duration: 15 },
      { instruction: "兩個芒果取肉，用攪拌機打成順滑芒果泥。另一個芒果切成漂亮小方塊。柚子取肉拆成散瓣絲。", duration: 5 },
      { instruction: "大盤中倒入芒果泥、椰奶、淡奶同糖水攪勻，放入西米、芒果塊同柚子肉絲拌勻。", duration: 3 },
      { instruction: "放入冰箱冷藏2小時後享用，清甜順滑、椰香滿溢。", duration: 2 },
    ],
    tags: ["甜品", "港式", "經典", "楊枝甘露", "芒果", "西米", "消暑", "清甜", "簡單", "30 分鐘內"],
  },
  {
    name: "經典紅豆沙",
    description: "傳統粵式糖水！紅豆慢火熬煮至軟爛起沙，融入陳皮淡淡嘅芬芳同老冰糖嘅清甜，溫潤暖胃，經典永恆。",
    cookTime: 90,
    servings: 4,
    difficulty: "簡單",
    recipeCategory: "甜品",
    ingredients: [
      { name: "優質紅豆", quantity: "200", unit: "克", category: "乾貨" },
      { name: "老陳皮", quantity: "1/4", unit: "個", category: "調味料" },
      { name: "老冰糖", quantity: "80", unit: "克", category: "調味料" },
      { name: "水", quantity: "1200", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "紅豆洗淨，熱水浸泡2小時（容易起沙）。陳皮浸軟刮去內膜白囊。", duration: 15 },
      { instruction: "大煲中倒入水、浸泡好嘅紅豆同陳皮大火燒開，轉小火慢火煲60分鐘。", duration: 60 },
      { instruction: "開蓋加入老冰糖。用勺子反覆大力順時針朝一個方向磨壓紅豆（起沙關鍵），至湯汁變得黏稠呈沙狀，再煮10分鐘即可溫熱享用。", duration: 15 },
    ],
    tags: ["甜品", "港式", "經典", "紅豆沙", "陳皮", "清甜", "暖身", "滋補", "簡單", "60 分鐘以上"],
  },
  {
    name: "香滑芝麻糊",
    description: "手炒黑芝麻、白米慢火研磨，煮出極致香濃、烏黑閃亮嘅芝麻糊，滑如絲綢，溫補養顏。",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "甜品",
    ingredients: [
      { name: "黑芝麻", quantity: "150", unit: "克", category: "乾貨" },
      { name: "白米（泡水2小時）", quantity: "30", unit: "克", category: "其他" },
      { name: "老冰糖", quantity: "50", unit: "克", category: "調味料" },
      { name: "水", quantity: "800", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "白米泡水軟化。黑芝麻洗淨。白鑊（不放油）慢火翻炒黑芝麻，至芝麻爆開散發濃烈香氣，盛起放涼。", duration: 10 },
      { instruction: "將炒好嘅芝麻、泡軟嘅白米與400毫升水放入破壁機中，磨煮或打成極細嘅芝麻米漿，用極細濾網過濾一次（滑軟關鍵）。", duration: 5 },
      { instruction: "過濾好嘅芝麻米漿倒入鍋中，加入餘下水同冰糖，中小火一邊加熱一邊用木勺反覆攪拌，防止黏底焦化，煮至滾沸、濃稠呈絲滑狀即可。", duration: 10 },
    ],
    tags: ["甜品", "港式", "經典", "芝麻糊", "香濃", "滋補", "養顏", "慢煮", "中等", "30 分鐘內"],
  },
  {
    name: "順德雙皮奶",
    description: "傳統雙皮奶呈豆腐狀，外層覆有獨特薄奶皮，內裡細緻滑軟，充滿濃郁奶香與蛋甜味。",
    cookTime: 25,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "甜品",
    ingredients: [
      { name: "全脂水牛奶（或高脂牛奶）", quantity: "400", unit: "毫升", category: "其他" },
      { name: "雞蛋白", quantity: "2", unit: "隻", category: "其他" },
      { name: "白糖", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "全脂牛奶倒入碗中蒸熱（不燒滾），放涼後碗面會自然結出一層厚厚嘅奶皮（第一層皮）。", duration: 10 },
      { instruction: "用小刀輕撥奶皮一角，輕輕將碗中牛奶倒出，將奶皮留在碗底。倒出嘅牛奶加白糖、蛋白攪拌勻過濾。", duration: 5 },
      { instruction: "將攪勻嘅蛋奶液重新沿着原碗角倒回碗中（此時原本留在底層嘅奶皮會自然浮在最上層）。", duration: 3 },
      { instruction: "碗面封保鮮膜，大火隔水蒸10分鐘至凝固。放涼後會結出第二層奶皮（雙皮奶），冷藏後食極佳。", duration: 12 },
    ],
    tags: ["甜品", "港式", "經典", "雙皮奶", "牛奶", "滑嫩", "滋補", "中等", "30 分鐘內", "小朋友"],
  },
  {
    name: "芒果西米露",
    description: "夏天必食港式經典！椰香順滑嘅椰奶，配上香甜芒果肉泥同Q彈西米，清涼解暑，人人喜愛。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "甜品",
    ingredients: [
      { name: "新鮮芒果", quantity: "2", unit: "個", category: "蔬菜" },
      { name: "西米", quantity: "80", unit: "克", category: "其他" },
      { name: "濃椰奶", quantity: "150", unit: "毫升", category: "其他" },
      { name: "老冰糖水", quantity: "50", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "滾水下西米煮12分鐘至外透明、內微白心，關火蓋蓋燜15分鐘至全透，沖冷水瀝乾。", duration: 10 },
      { instruction: "一個半芒果切肉打成泥，半個芒果切小塊擺面。", duration: 5 },
      { instruction: "大碗中倒入西米、芒果泥、椰奶同糖水攪勻。", duration: 3 },
      { instruction: "放上芒果塊，冰鎮1小時食最佳。", duration: 2 },
    ],
    tags: ["甜品", "港式", "經典", "西米露", "芒果", "椰奶", "清甜", "簡單", "30 分鐘內", "快手"],
  },
  {
    name: "港式街頭雞蛋仔",
    description: "香港街頭小食嘅代名詞！雞蛋仔外皮焦脆呈金黃球狀，內裡香軟呈中空，帶有濃厚蛋香同奶香。",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "甜品",
    ingredients: [
      { name: "低筋麵粉", quantity: "140", unit: "克", category: "其他" },
      { name: "雞蛋", quantity: "2", unit: "隻", category: "其他" },
      { name: "吉士粉（卡士達粉）", quantity: "1", unit: "湯匙", category: "其他" },
      { name: "泡打粉/白糖", quantity: "1茶匙/60克", unit: "", category: "其他" },
      { name: "水/無鹽牛油（熔化）", quantity: "100毫升/25克", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "雞蛋、糖、水同牛油攪拌勻。篩入低筋粉、吉士粉及泡打粉，攪至無粉粒麵糊，靜置20分鐘（起酥脆關鍵）。", duration: 15 },
      { instruction: "雞蛋仔專用模具雙面燒熱，抹薄油。倒入麵糊，蓋好模具，立刻快速翻轉180度，使麵糊充滿球孔。", duration: 3 },
      { instruction: "中小火每面各烤烤2分鐘，至雙面呈現金黃焦香、硬皮。", duration: 5 },
      { instruction: "取出，用風扇或扇子輕輕吹風30秒（吹去水氣會迅速變硬脆），趁熱折起享用，外脆內軟。", duration: 2 },
    ],
    tags: ["甜品", "港式", "經典", "街頭小食", "雞蛋仔", "香脆", "特色", "小朋友", "進階", "下午茶"],
  },
  {
    name: "法式焦糖燉蛋",
    description: "法式 Crème Brûlée 港式茶餐廳下午茶經典！極度香軟細緻嘅蛋黃布丁表面，覆有一層用噴槍燒成嘅焦脆玻璃焦糖，美味至極。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "甜品",
    ingredients: [
      { name: "新鮮蛋黃", quantity: "4", unit: "隻", category: "其他" },
      { name: "淡忌廉（鮮奶油）", quantity: "250", unit: "毫升", category: "其他" },
      { name: "白糖/香草精", quantity: "35克/少許", unit: "", category: "調味料" },
      { name: "黃糖（灑面燒焦糖用）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "蛋黃加糖攪勻。淡忌廉小火加熱（不滾），加香草精，徐徐倒入蛋黃中攪勻（要慢防蛋白熟），過濾兩次去泡沫。", duration: 15 },
      { instruction: "蛋奶液倒入烤杯。烤盤注入溫水沒過1/2烤杯（水浴法烤，保持極致嫩滑）。", duration: 3 },
      { instruction: "放入預熱160度焗爐焗烤25-30分鐘至凝固。取出完全放涼放入冰箱冷藏2小時。", duration: 10 },
      { instruction: "食用前，在表面均勻灑上一層薄薄嘅黃糖，用火槍高溫燒成金黃焦脆焦糖玻璃，放涼30秒開吃。", duration: 2 },
    ],
    tags: ["甜品", "法式", "茶餐廳", "焦糖燉蛋", "蛋黃", "香濃", "香脆", "滑嫩", "進階", "30 分鐘內"],
  },
  {
    name: "朱古力心太軟",
    description: "朱古力熔岩蛋糕！外皮是扎實嘅朱古力蛋糕，切開一角，熱騰騰、極其濃郁嘅朱古力流沙如熔岩般流出，配雪糕絕配。",
    cookTime: 25,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "甜品",
    ingredients: [
      { name: "黑朱古力（55%以上）", quantity: "80", unit: "克", category: "其他" },
      { name: "無鹽牛油", quantity: "50", unit: "克", category: "調味料" },
      { name: "雞蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "雞蛋黃", quantity: "1", unit: "隻", category: "其他" },
      { name: "白糖/低筋麵粉", quantity: "30克/30克", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "黑朱古力與牛油一同隔水加熱熔化，攪拌均勻放涼。雞蛋、蛋黃及白糖大碗中打發至淡黃色、微稠。", duration: 10 },
      { instruction: "將熔化朱古力倒入蛋液中輕輕攪勻，篩入低筋粉，用刮刀翻拌均勻。模具抹油撒粉，倒入麵糊八成滿。", duration: 5 },
      { instruction: "放入預熱200度嘅焗爐中，大火高溫焗烤8-10分鐘（極其關鍵，時間長了裡面會熟透不流沙，短了外面未熟崩塌）。", duration: 8 },
      { instruction: "出爐放涼1分鐘，小心倒扣在碟中，撒糖霜，放一球香草雪糕即可，完美享受流沙朱古力。", duration: 2 },
    ],
    tags: ["甜品", "經典", "西式", "心太軟", "朱古力", "流沙", "高級", "進階", "30 分鐘內"],
  },
  {
    name: "意式提拉米蘇",
    description: "Classic Tiramisu！浸透香濃意式濃縮咖啡與咖啡酒嘅手指餅乾，層層疊上香軟如絲絨嘅馬斯卡彭乳酪（Mascarpone），撒上微苦朱古力粉，意式傳奇。",
    cookTime: 30,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "甜品",
    ingredients: [
      { name: "馬斯卡彭芝士", quantity: "250", unit: "克", category: "其他" },
      { name: "手指餅乾（Savoiardi）", quantity: "12", unit: "片", category: "其他" },
      { name: "新鮮生蛋黃", quantity: "2", unit: "隻", category: "其他" },
      { name: "白糖/淡油忌廉", quantity: "50克/150毫升", unit: "", category: "其他" },
      { name: "意式濃縮咖啡/咖啡甜酒", quantity: "各100", unit: "毫升", category: "調味料" },
      { name: "無糖朱古力粉", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "蛋黃加糖打發至發白。馬斯卡彭芝士攪至滑，混合打發蛋黃。淡忌廉打發至起紋路，兩者用刮刀輕輕翻拌均勻成芝士糊。咖啡同咖啡酒混合。", duration: 15 },
      { instruction: "手指餅乾在咖啡酒中迅速浸1秒（防過濕軟爛），整齊排在容器底層。", duration: 5 },
      { instruction: "鋪上一半芝士糊抹平。再鋪一層浸過咖啡酒嘅手指餅，再鋪上剩餘芝士糊抹平。", duration: 8 },
      { instruction: "放入冰箱冷藏4小時以上或過夜。食用前表面厚厚篩上一層無糖朱古力粉即成。", duration: 2 },
    ],
    tags: ["甜品", "意式", "經典", "提拉米蘇", "芝士", "咖啡", "香濃", "免焗", "進階", "下午茶"],
  },
  {
    name: "芒果班戟",
    description: "港式甜品舖無敵人氣王！嫩綠Q彈、透亮薄嘅班戟皮，包裹極度輕盈嘅打發忌廉同清甜芒果大塊，啖啖驚喜。",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "甜品",
    ingredients: [
      { name: "新鮮甜芒果（切大條）", quantity: "2", unit: "個", category: "蔬菜" },
      { name: "淡油忌廉（打發）", quantity: "150", unit: "毫升", category: "其他" },
      { name: "低筋麵粉/雞蛋", quantity: "80克/2隻", unit: "", category: "其他" },
      { name: "牛奶/斑蘭精（或食用色素）", quantity: "200毫升/少許", unit: "", category: "其他" },
      { name: "糖粉/無鹽油（熔化）", quantity: "各20", unit: "克", category: "其他" },
    ],
    steps: [
      { instruction: "雞蛋、糖粉、牛奶、熔化油同斑蘭精攪拌勻。篩入低筋粉攪拌至無粉粒，過濾兩次，靜置20分鐘。", duration: 15 },
      { instruction: "不粘平底鍋小火燒微熱（不落油），倒入一湯匙蛋漿迅速轉動攤成大圓薄皮。小火煎熟（只煎單面），取出放涼（班戟皮）。", duration: 5 },
      { instruction: "淡忌廉加15克糖打發至堅硬。放一片班戟皮（煎面朝上，包在裡面更漂亮），放上一大勺打發忌廉，放一塊厚芒果條，再蓋少許忌廉。", duration: 3 },
      { instruction: "將班戟皮四折折起成枕頭狀包緊，翻面擺盤，放入冰箱冷藏1小時切開享用，極其誘人。", duration: 2 },
    ],
    tags: ["甜品", "港式", "經典", "班戟", "芒果", "忌廉", "滑嫩", "免焗", "進階", "下午茶"],
  },
  {
    name: "薑汁撞奶",
    description: "傳統懷舊港式甜品。新鮮老薑汁中富含蛋白酶，在特定溫度下與熱全脂牛奶產生化學撞擊，瞬間凝固成滑溜如布丁嘅溫補甜品。",
    cookTime: 15,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "甜品",
    ingredients: [
      { name: "全脂牛奶（或高脂鮮奶）", quantity: "300", unit: "毫升", category: "其他" },
      { name: "新鮮老薑（去皮磨汁）", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "砂糖", quantity: "1.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "老薑去皮磨碎，用紗布用力捏榨出鮮薑汁，分裝在兩個大碗底（每碗1湯匙，必須是現榨，放久了酵素失效）。", duration: 8 },
      { instruction: "全脂牛奶加入砂糖放鍋中中火加熱至75-80度（邊緣微起細泡泡，不可燒大滾，溫度過高或過低均會撞奶失敗）。", duration: 4 },
      { instruction: "迅速把薑汁重新攪勻（防沉澱）。手提高熱牛奶鍋，高溫朝碗正中「高沖」撞入薑汁中，不要攪拌。", duration: 1 },
      { instruction: "蓋上碟子靜置5分鐘（切忌移動或震動），牛奶會神奇地凝固呈滑溜豆花布丁狀，溫熱暖胃解寒極佳。", duration: 2 },
    ],
    tags: ["甜品", "港式", "經典", "薑汁撞奶", "牛奶", "滑嫩", "暖胃", "驅寒", "特色", "進階"],
  },
  {
    name: "雙皮大良鮮奶",
    description: "廣東名產！以極度香濃、細膩嘅順德鮮奶混蛋清，慢火隔水蒸出，面頭有滑皮，香甜如絲綢。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "甜品",
    ingredients: [
      { name: "全脂鮮牛奶", quantity: "300", unit: "毫升", category: "其他" },
      { name: "雞蛋白", quantity: "2", unit: "隻", category: "其他" },
      { name: "白糖", quantity: "1.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "鮮牛奶加白糖用小火微加熱至糖熔，稍微放涼。加入打散嘅蛋白徹底攪拌均勻。", duration: 5 },
      { instruction: "將混合好嘅蛋奶液用極細篩網過濾兩次，徹底去除泡沫同雜質（細滑關鍵）。", duration: 5 },
      { instruction: "均勻倒入兩個大碗中，封上保鮮膜防止蒸氣滴入。", duration: 2 },
      { instruction: "水大滾，中火隔水蒸10-12分鐘至凝固。放涼冷藏更佳，乳香濃郁。", duration: 8 },
    ],
    tags: ["甜品", "經典", "大良鮮奶", "牛奶", "蛋白", "滑嫩", "滋補", "簡單", "30 分鐘內", "小朋友"],
  },

  // ─── GLOBAL SOUPS (10) ──────────────────────────────────────────────────────
  {
    name: "法式洋蔥湯",
    description: "法式料理必點！洋蔥絲慢火焦糖化炒足半小時呈深琥珀色，注入濃香牛肉湯，蓋上法包與拉絲芝士焗至焦香。",
    cookTime: 60,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "西餐",
    ingredients: [
      { name: "黃洋蔥", quantity: "3", unit: "個", category: "蔬菜" },
      { name: "牛油", quantity: "30", unit: "克", category: "調味料" },
      { name: "牛肉高湯", quantity: "800", unit: "毫升", category: "湯" },
      { name: "法國長麵包（法包）", quantity: "3", unit: "片", category: "其他" },
      { name: "葛瑞爾芝士碎（Gruyere）", quantity: "1/2", unit: "杯", category: "其他" },
      { name: "白葡萄酒/生抽", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "洋蔥去皮切細絲。熱深鍋融化牛油，下洋蔥絲，中火慢翻炒30分鐘（必須慢炒，直到洋蔥縮水焦糖化呈琥珀黃，這是湯底甘甜嘅來源，不可炒焦）。", duration: 30 },
      { instruction: "下白葡萄酒大火收汁，倒入牛肉高湯、少許生抽調色，大火燒開轉小火，蓋蓋燉煮15分鐘。", duration: 15 },
      { instruction: "將洋蔥湯倒入三個耐高溫烤碗。每碗頂鋪一片微煎嘅法包，法包上鋪滿厚厚嘅芝士碎。", duration: 5 },
      { instruction: "放入焗爐高溫200度焗烤5-8分鐘，至芝士熔化拉絲起金黃微焦，滾燙呈上。", duration: 10 },
    ],
    tags: ["西餐", "法式", "洋蔥湯", "焦糖化", "芝士", "焗", "香濃", "慢煮", "60 分鐘以上", "中等"],
  },
  {
    name: "忌廉南瓜湯",
    description: "香甜順滑！新鲜南瓜肉慢火燉熟，打成極其滑潤嘅南瓜泥，融入淡忌廉同牛油，金黃芳香，小朋友最愛。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "黃金南瓜肉", quantity: "400", unit: "克", category: "蔬菜" },
      { name: "洋蔥碎", quantity: "50", unit: "克", category: "蔬菜" },
      { name: "牛油", quantity: "20", unit: "克", category: "調味料" },
      { name: "淡忌廉", quantity: "50", unit: "毫升", category: "其他" },
      { name: "高湯或水", quantity: "400", unit: "毫升", category: "其他" },
    ],
    steps: [
      { instruction: "南瓜去皮切塊，洋蔥切碎。熱鍋融化牛油，炒香洋蔥，下南瓜塊翻炒2分鐘。", duration: 5 },
      { instruction: "倒入高湯煮滾，轉小火蓋蓋煮10-12分鐘至南瓜熟爛。", duration: 10 },
      { instruction: "關火，用手持料理棒或破壁機將南瓜湯打成極細滑、無顆粒嘅南瓜泥湯。", duration: 2 },
      { instruction: "重新開小火，倒入淡忌廉攪勻，加少許鹽、胡椒粉調味，微熱即可盛碗，淋少許忌廉花拉花。", duration: 3 },
    ],
    tags: ["西餐", "南瓜湯", "南瓜", "忌廉", "清甜", "滑嫩", "簡單", "快手", "30 分鐘內", "小朋友"],
  },
  {
    name: "俄式羅宋湯",
    description: "傳統紅菜頭羅宋湯（Borscht）！紅菜頭（甜菜根）、牛肉塊、高麗菜與多種蔬菜慢火煲煮，湯色絳紅，酸甜開胃，點酸忌廉絕配。",
    cookTime: 90,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "西餐",
    ingredients: [
      { name: "新鮮牛腩或牛腱肉塊", quantity: "300", unit: "克", category: "肉類" },
      { name: "新鮮紅菜頭（甜菜根）", quantity: "200", unit: "克", category: "蔬菜" },
      { name: "高麗菜/洋蔥/胡蘿蔔/薯仔", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "番茄膏/白醋/糖/鹽", quantity: "適量", unit: "", category: "調味料" },
      { name: "酸忌廉（Sour Cream，裝飾用）", quantity: "少許", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "牛肉切塊飛水。紅菜頭刨絲，其他蔬菜切塊。熱鍋下油炒香洋蔥、胡蘿蔔、紅菜頭絲同番茄膏。", duration: 15 },
      { instruction: "倒入牛肉塊同大量熱水，大火燒滾轉小火，蓋蓋慢火燉煮60分鐘。", duration: 60 },
      { instruction: "加入高麗菜絲同薯仔塊，再煮15分鐘至熟軟。落鹽、糖、少許白醋（調出地道酸甜口味同亮紅湯色）。", duration: 12 },
      { instruction: "盛碗，頂部放一大勺酸忌廉，撒上蒔蘿草即可。", duration: 3 },
    ],
    tags: ["西餐", "羅宋湯", "紅菜頭", "牛肉", "酸甜", "開胃", "豐富", "慢煮", "60 分鐘以上", "中等"],
  },
  {
    name: "忌廉蘑菇湯",
    description: "濃香無敵！新鮮白蘑菇、褐蘑菇同香菇爆香打碎，配以法式麵糊、牛油與鮮忌廉，蘑菇碎有咬勁，湯濃滑香。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "新鮮白蘑菇/褐蘑菇/香菇", quantity: "300", unit: "克", category: "蔬菜" },
      { name: "牛油", quantity: "30", unit: "克", category: "調味料" },
      { name: "洋蔥碎/蒜蓉", quantity: "適量", unit: "", category: "調味料" },
      { name: "雞高湯", quantity: "500", unit: "毫升", category: "湯" },
      { name: "淡忌廉", quantity: "80", unit: "毫升", category: "其他" },
      { name: "麵粉", quantity: "1.5", unit: "湯匙", category: "其他" },
    ],
    steps: [
      { instruction: "蘑菇切片，保留幾片漂亮嘅裝飾。熱鍋落牛油，炒香洋蔥碎、蒜蓉，下所有蘑菇片大火炒軟並出香氣（約5分鐘）。", duration: 8 },
      { instruction: "篩入麵粉小火翻炒均勻。倒入雞高湯大火燒開，轉小火蓋蓋煮10分鐘。", duration: 10 },
      { instruction: "關火用手持料理棒打碎（保留少許蘑菇顆粒更有口感）。重新開小火倒入淡忌廉攪拌勻。", duration: 4 },
      { instruction: "加鹽黑胡椒調味。裝飾煎香嘅蘑菇片即可上桌，芳香四溢。", duration: 3 },
    ],
    tags: ["西餐", "經典", "蘑菇湯", "忌廉", "香濃", "簡單", "快手", "30 分鐘內", "家常"],
  },
  {
    name: "意大利蔬菜湯",
    description: "經典 Minestrone！大白菜、番茄、西芹、鷹嘴豆與意大利通心粉慢火滾煮，帶有羅勒葉與番茄嘅清新，健康少油，高纖消脂。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "新鮮番茄塊/番茄罐頭", quantity: "各1", unit: "個/罐", category: "蔬菜" },
      { name: "西葫蘆/西芹/胡蘿蔔/洋蔥", quantity: "各50", unit: "克", category: "蔬菜" },
      { name: "熟鷹嘴豆/紅腰豆罐頭", quantity: "50", unit: "克", category: "乾貨" },
      { name: "意大利通心粉或碎意粉", quantity: "50", unit: "克", category: "其他" },
      { name: "蔬菜高湯/鹽/黑胡椒", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "所有蔬菜去皮切小丁。熱鍋下橄欖油，爆香洋蔥、胡蘿蔔、西芹丁大火炒3分鐘。", duration: 5 },
      { instruction: "加入番茄塊、番茄罐頭、西葫蘆丁與蔬菜高湯，大火燒開轉小火煮10分鐘。", duration: 10 },
      { instruction: "下鷹嘴豆、紅腰豆同通心粉，繼續小火煮10分鐘至通心粉軟嫩熟透。", duration: 8 },
      { instruction: "加鹽、黑胡椒及少許香草碎調味，非常高纖、解膩。", duration: 2 },
    ],
    tags: ["西餐", "意式", "蔬菜湯", "通心粉", "高纖", "健康", "低卡", "清淡", "簡單", "30 分鐘內"],
  },
  {
    name: "忌廉周打蜆湯",
    description: "經典美式 Clam Chowder！鮮甜肥美嘅蜆肉、薯仔丁、洋蔥與煙肉碎慢火熬煮，融入牛油與忌廉，極其濃稠滑軟，海洋風味滿滿。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "西餐",
    ingredients: [
      { name: "罐頭蜆肉（連蜆汁）", quantity: "1", unit: "罐", category: "海鮮" },
      { name: "煙肉碎/薯仔（切細丁）", quantity: "適量", unit: "", category: "其他" },
      { name: "牛油/麵粉/鮮忌廉", quantity: "適量", unit: "", category: "其他" },
      { name: "洋蔥碎/西芹丁", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "雞湯", quantity: "300", unit: "毫升", category: "湯" },
    ],
    steps: [
      { instruction: "薯仔、洋蔥、西芹切均勻細丁。熱鍋煸香煙肉碎炒出油，下洋蔥西芹丁炒香。", duration: 8 },
      { instruction: "下牛油熔化，篩入麵粉攪拌勻呈糊狀。緩緩倒入雞湯、罐頭蜆汁與薯仔丁，大火煮滾小火燉煮15分鐘至薯仔軟爛、自然濃稠。", duration: 15 },
      { instruction: "加入罐頭蜆肉，倒入鮮忌廉，小火滾2分鐘（蜆肉不宜久煮，會變老縮水）。", duration: 5 },
      { instruction: "加鹽黑胡椒，撒少許香菜碎即可，滑軟鹹香，極具美式風味。", duration: 2 },
    ],
    tags: ["西餐", "美式", "蜆湯", "周打湯", "海鮮", "忌廉", "薯仔", "香濃", "中等", "30 分鐘內"],
  },
  {
    name: "西式番茄濃湯",
    description: "番茄高溫烤至微焦起皮，與洋蔥、大蒜打成濃郁番茄泥，配百里香、鮮忌廉慢煮，酸甜順滑，佐以烤芝士多士極佳。",
    cookTime: 25,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "西餐",
    ingredients: [
      { name: "新鮮大番茄", quantity: "4", unit: "個", category: "蔬菜" },
      { name: "蒜頭", quantity: "4", unit: "瓣", category: "調味料" },
      { name: "洋蔥", quantity: "1/2", unit: "個", category: "蔬菜" },
      { name: "淡忌廉", quantity: "50", unit: "毫升", category: "其他" },
      { name: "蔬菜高湯", quantity: "300", unit: "毫升", category: "湯" },
      { name: "橄欖油", quantity: "1.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "大番茄切四瓣，與整瓣大蒜、洋蔥塊混合淋上橄欖油、鹽胡椒，放入200度焗爐烤20分鐘至表面微焦黄（烤過番茄甜味加倍）。", duration: 10 },
      { instruction: "將烤好嘅番茄、洋蔥大蒜倒入深鍋，加入蔬菜高湯大火燒開，轉小火煮5分鐘。", duration: 5 },
      { instruction: "關火用手持料理棒打成極其均勻絲滑、無紅皮顆粒嘅番茄濃湯泥。", duration: 3 },
      { instruction: "倒入淡忌廉攪拌勻，小火微熱，撒少許黑胡椒，配焦脆烤麵包片極品。", duration: 7 },
    ],
    tags: ["西餐", "番茄湯", "番茄", "忌廉", "酸甜", "香濃", "健康", "簡單", "30 分鐘內", "小朋友"],
  },
  {
    name: "匈牙利牛肉湯",
    description: "經典 Goulash！大塊牛腩、薯仔、紅椒與大量匈牙利紅椒粉（Paprika）、番茄慢火燉煮出深紅色濃湯，肉質香軟，微辛辛香。",
    cookTime: 120,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "西餐",
    ingredients: [
      { name: "牛腩肉塊", quantity: "500", unit: "克", category: "肉類" },
      { name: "洋蔥碎/紅尖椒塊/薯仔", quantity: "各1", unit: "個", category: "蔬菜" },
      { name: "匈牙利紅椒粉（Paprika）", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "番茄膏/牛肉高湯", quantity: "2湯匙/800毫升", unit: "", category: "調味料" },
      { name: "蒜泥/葛香草（Caraway seeds）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "牛肉切方塊飛水。薯仔去皮切塊。熱大深鍋下牛油，爆香洋蔥、蒜泥、紅椒塊。", duration: 15 },
      { instruction: "倒入紅椒粉、葛香草同番茄膏小火炒出亮紅油。倒入牛肉塊翻炒上色。", duration: 5 },
      { instruction: "倒入牛肉高湯，大火燒滾撇去浮沫，轉小火蓋蓋慢火燉煮90分鐘。", duration: 90 },
      { instruction: "加入薯仔塊，繼續小火慢燉20分鐘至牛腩軟輭、湯汁紅潤濃稠即可。", duration: 20 },
    ],
    tags: ["西餐", "經典", "牛肉湯", "匈牙利", "紅椒粉", "辛香", "慢煮", "60 分鐘以上", "中等"],
  },
  {
    name: "希臘檸檬雞湯",
    description: "希臘傳統家庭湯（Avgolemono）！鮮雞湯底融入香滑蛋液、新鮮檸檬汁與嫩雞絲、米粒，酸甜開胃，細滑無比，清胃首選。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "西餐",
    ingredients: [
      { name: "雞肉絲", quantity: "150", unit: "克", category: "肉類" },
      { name: "新鮮檸檬汁", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "雞蛋", quantity: "2", unit: "隻", category: "其他" },
      { name: "米粒或碎短意粉（Orzo）", quantity: "50", unit: "克", category: "其他" },
      { name: "雞高湯", quantity: "800", unit: "毫升", category: "湯" },
    ],
    steps: [
      { instruction: "雞高湯倒入鍋中煮滾，下米粒（或Orzo意粉）中火煮15分鐘至軟爛。加入煮熟嘅雞絲。", duration: 15 },
      { instruction: "大碗中將雞蛋用力打發至起泡膨脹，慢慢倒入新鮮檸檬汁繼續打發成白黃色檸檬蛋液。", duration: 5 },
      { instruction: "將1杯熱雞湯緩緩慢慢地注入檸檬蛋液中一邊倒一邊快速打發（關鍵，防止熱湯使蛋液變蛋花，要調溫乳化）。", duration: 5 },
      { instruction: "將調好嘅檸檬蛋液徐徐倒回鍋中，關小火（不可滾起，否則會變蛋花），不斷攪拌至湯汁呈現細緻、如絲綢般嘅濃稠白色，即可出鍋。", duration: 5 },
    ],
    tags: ["西餐", "希臘", "雞湯", "檸檬", "雞肉", "雞蛋", "酸甜", "滑嫩", "中等", "30 分鐘內"],
  },
  {
    name: "波蘭酸黑麥湯",
    description: "波蘭國寶湯 Zurek！特製黑麥發酵水（Sour rye starter）熬煮煙燻香腸、薯仔與大蒜，湯頭帶有天然麥香同迷人微酸，蓋上水煮蛋，地道東歐風。",
    cookTime: 40,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "其他",
    ingredients: [
      { name: "波蘭煙燻白香腸（切片）", quantity: "200", unit: "克", category: "肉類" },
      { name: "酸黑麥發酵水（Zurek starter）", quantity: "1", unit: "杯", category: "調味料" },
      { name: "薯仔（切方塊）", quantity: "1.5", unit: "個", category: "蔬菜" },
      { name: "熟水煮蛋（切半）", quantity: "2", unit: "隻", category: "其他" },
      { name: "大蒜/馬鬱蘭草（Majoram）", quantity: "適量", unit: "", category: "調味料" },
      { name: "蔬菜高湯", quantity: "600", unit: "毫升", category: "湯" },
    ],
    steps: [
      { instruction: "香腸切片。薯仔切丁。熱深鍋煸香香腸片，炒出香味，下大蒜蓉、薯仔丁同高湯煮滾。", duration: 12 },
      { instruction: "中火慢煮15-20分鐘至薯仔軟熟。", duration: 15 },
      { instruction: "將酸黑麥發酵水充分攪勻，徐徐倒入鍋中攪拌均勻，湯汁會立刻呈現漂亮白色、散發獨特麥香微酸，繼續慢火煮5分鐘至微稠，撒馬鬱蘭草。", duration: 10 },
      { instruction: "盛碗，每碗排上半個熟水煮蛋切面朝上，趁熱享用。", duration: 3 },
    ],
    tags: ["其他", "波蘭", "酸湯", "香腸", "黑麥", "微酸", "慢煮", "特色", "中等", "30 分鐘以上"],
  },

  // ─── GLOBAL NOODLES & RICE (9) ──────────────────────────────────────────────
  {
    name: "意大利牛肝菌燉飯",
    description: "經典 Risotto！頂級意米（Arborio）在牛肝菌、雞高湯中不斷攪拌慢燉，米粒吸飽菌香與牛油芝士精華，中心帶骨（Al Dente），滑軟黏稠。",
    cookTime: 35,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "西餐",
    ingredients: [
      { name: "意大利米（Arborio）", quantity: "150", unit: "克", category: "其他" },
      { name: "乾燥牛肝菌", quantity: "20", unit: "克", category: "乾貨" },
      { name: "白蘑菇片/洋蔥碎", quantity: "各50", unit: "克", category: "蔬菜" },
      { name: "熱雞高湯", quantity: "500", unit: "毫升", category: "湯" },
      { name: "帕馬森芝士碎/牛油", quantity: "適量", unit: "", category: "其他" },
      { name: "白葡萄酒", quantity: "50", unit: "毫升", category: "調味料" },
    ],
    steps: [
      { instruction: "牛肝菌用熱水浸泡軟化，泡出嘅黑水留用。洋蔥切極細碎。高湯與牛肝菌水混合保持微滾。", duration: 15 },
      { instruction: "熱鑊下油與洋蔥碎炒香，下白米（不洗）翻炒2分鐘至米粒邊緣透明。下白葡萄酒大火收乾。", duration: 5 },
      { instruction: "轉中火，倒入浸軟切碎嘅牛肝菌同白蘑菇片。開始分次倒入1大勺熱高湯，不斷用木勺溫柔攪拌白米（激發澱粉使Risotto濃稠）。", duration: 5 },
      { instruction: "等高湯完全吸乾後，再次加入一勺高湯，重複此步驟攪拌煮18-20分鐘。最後關火加入牛油同大量芝士粉快速攪勻乳化（Mantecatura），蓋蓋燜2分鐘。", duration: 10 },
    ],
    tags: ["西餐", "意式", "燉飯", "Risotto", "牛肝菌", "芝士", "香濃", "宴客", "中等", "30 分鐘以上"],
  },
  {
    name: "韓式水冷麵",
    description: "夏天必吃涼意！冰透甚至帶微冰沙嘅牛肉酸甜湯底，配上極具煙韌嚼勁嘅韓國蕎麥麵，鋪上雪梨片、牛肉與熟蛋，清涼解暑。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "韓國蕎麥冷麵條", quantity: "200", unit: "克", category: "其他" },
      { name: "特製韓式冷麵冰湯底（牛肉醋湯）", quantity: "2", unit: "包", category: "湯" },
      { name: "熟牛肉片/水煮蛋/熟泡菜", quantity: "少許", unit: "", category: "其他" },
      { name: "新鮮雪梨片/青瓜絲", quantity: "少許", unit: "", category: "蔬菜" },
      { name: "黃芥末醬/白醋", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "冷麵湯底提前放冰箱冷凍至微起冰沙狀態（極其爽脆）。青瓜切絲，雪梨切片。", duration: 10 },
      { instruction: "蕎麥麵下大滾水煮煮3-4分鐘至剛熟，立刻撈起，在冰水中大力反覆搓洗去除表面澱粉質（彈牙關鍵），瀝乾盤在碗底。", duration: 5 },
      { instruction: "在麵上排好熟牛肉片、熟蛋切半、青瓜絲、雪梨片同少許泡菜。", duration: 3 },
      { instruction: "倒入帶有冰沙嘅酸甜牛肉冷麵湯，佐以白醋同黃芥末醬食用，冰爽直衝顳顬。", duration: 2 },
    ],
    tags: ["韓式", "冷麵", "蕎麥麵", "酸甜", "冰爽", "消暑", "夏天", "簡單", "30 分鐘內", "快手"],
  },
  {
    name: "日式叉燒豬骨拉麵",
    description: "經典 Ramen！濃郁奶白嘅日式豬骨濃湯，配上煙韌日式拉麵、極其軟嫩嘅日式卷叉燒、溏心蛋同紫菜，拉麵之魂。",
    cookTime: 30,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "日式",
    ingredients: [
      { name: "日式新鮮拉麵", quantity: "2", unit: "人份", category: "其他" },
      { name: "日式熟叉燒肉片", quantity: "4", unit: "片", category: "肉類" },
      { name: "濃郁日式豬骨拉麵高湯", quantity: "600", unit: "毫升", category: "湯" },
      { name: "日式溏心蛋/紫菜/筍片", quantity: "適量", unit: "", category: "其他" },
      { name: "黑麻油/蔥花", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "拉麵高湯在深鍋中煮得滾燙。溏心蛋切半。叉燒肉片用火槍噴槍或平底鍋略煎熱逼出油香。", duration: 15 },
      { instruction: "拉麵下大滾水煮煮1.5-2分鐘至帶硬身口感（Al Dente），撈起充分瀝乾水分（防沖淡湯底）。", duration: 5 },
      { instruction: "將滾熱嘅豬骨湯倒入大拉麵碗中，放入瀝乾嘅拉麵，用筷子整理麵條。", duration: 5 },
      { instruction: "表面排上炙燒叉燒片、半個溏心蛋、筍片、紫菜，灑蔥花，淋幾滴黑油即成。", duration: 5 },
    ],
    tags: ["日式", "和風", "拉麵", "豬骨湯", "叉燒", "溏心蛋", "香濃", "經典", "中等", "30 分鐘內"],
  },
  {
    name: "港式乾炒牛河",
    description: "考驗大牌檔廚師鑊氣功底嘅終極代表！河粉條條紅潤、均勻沾滿生抽老抽，牛肉片厚實滑嫩，韭黃芽菜爽口，乾身無多餘油分。",
    cookTime: 15,
    servings: 2,
    difficulty: "困難",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮河粉", quantity: "350", unit: "克", category: "其他" },
      { name: "牛肉片", quantity: "150", unit: "克", category: "肉類" },
      { name: "韭黃段/芽菜/蔥段", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "生抽", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "老抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "3", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "牛肉片加少許生抽、糖同生粉醃15分鐘。河粉手撕開成條（防黏連）。芽菜韭黃洗淨瀝乾。", duration: 10 },
      { instruction: "大火熱鑊落2湯匙油，下牛肉快速爆炒至七成熟，盛起瀝乾油。", duration: 2 },
      { instruction: "鑊中補1湯匙油，放入河粉，用筷子輕輕撥鬆（切忌用鐵鏟大力攪翻防碎），大火乾炒2分鐘至微焦香。", duration: 2 },
      { instruction: "倒入生抽、老抽、糖，雙手顛鑊或用筷子快速把醬色抹勻。倒入牛肉、芽菜、韭黃及蔥段，大火極速翻炒30秒至芽菜剛斷生、乾身無底油即可大氣上碟。", duration: 1 },
    ],
    tags: ["中菜", "港式", "經典", "大牌檔", "炒", "牛肉", "河粉", "鑊氣", "快手", "15 分鐘內", "困難"],
  },
  {
    name: "港式星洲炒米",
    description: "茶餐廳黃金之最！米粉經高溫大火爆炒呈亮黃色，充滿微辣黃薑咖喱香，配料有叉燒絲、鮮蝦與韭黃，鑊氣十足，鹹香開胃。",
    cookTime: 20,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "米粉（浸軟瀝乾）", quantity: "200", unit: "克", category: "其他" },
      { name: "叉燒絲/鮮蝦仁", quantity: "各60", unit: "克", category: "其他" },
      { name: "黃咖喱粉/黃薑粉", quantity: "1.5湯匙/1/2茶匙", unit: "", category: "調味料" },
      { name: "洋蔥絲/紅椒絲/青椒絲/韭黃", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "雞蛋液", quantity: "1", unit: "隻", category: "其他" },
      { name: "食油", quantity: "2.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "米粉用熱水浸泡5分鐘，蓋蓋焗軟，撈起徹底瀝乾。蝦仁爆香，叉燒切細絲，彩椒切細絲。蛋液炒碎盛起。", duration: 10 },
      { instruction: "熱鑊下油爆香洋蔥彩椒絲，下咖喱粉、黃薑粉小火煸炒出強烈咖喱油香。", duration: 2 },
      { instruction: "放入米粉，轉大火，用筷子快速撥散、抖動，使咖喱粉均勻沾在米粉上，炒至乾身、焦香。", duration: 5 },
      { instruction: "倒入叉燒絲、蝦仁、蛋碎同韭黃段，撒少許鹽，轉大火爆炒均勻即成，黃金奪目。", duration: 3 },
    ],
    tags: ["中菜", "港式", "茶餐廳", "經典", "炒", "米粉", "咖喱", "蝦", "叉燒", "鑊氣", "中等"],
  },
  {
    name: "西班牙海鮮鐵鍋飯",
    description: "經典 Paella！西班牙短米在特製平鐵鐵鍋中，吸滿番紅花（Saffron）、海鮮高湯與大蝦、青口、魷魚嘅鮮美精華，底部結出一層香脆黃金鍋巴（Socarrat）。",
    cookTime: 45,
    servings: 4,
    difficulty: "困難",
    recipeCategory: "西餐",
    ingredients: [
      { name: "西班牙短米（Bomba）", quantity: "200", unit: "克", category: "其他" },
      { name: "大鮮蝦/新鮮青口/鮮魷魚圈", quantity: "適量", unit: "", category: "海鮮" },
      { name: "珍貴番紅花（Saffron）", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "海鮮高湯", quantity: "500", unit: "毫升", category: "湯" },
      { name: "洋蔥丁/紅椒丁/蒜蓉", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "白葡萄酒/番茄膏", quantity: "50毫升/1湯匙", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "番紅花浸泡在熱海鮮高湯中。海鮮洗淨。平雙耳鐵鐵鍋（Paella pan）熱油煎香蝦仁魷魚取出。爆香洋蔥、紅椒丁同番茄膏。", duration: 15 },
      { instruction: "倒入西班牙米（不洗）炒勻上色。倒入番紅花海鮮高湯同白酒攪勻鋪平，大火燒開轉中火，蓋上落蓋或敞開煮15分鐘，期間絕對不可攪拌（攪拌會破壞Socarrat鍋巴形成）。", duration: 15 },
      { instruction: "將蝦、青口、魷魚圈整齊排入米飯表面，蓋蓋小火继续燜煮8-10分鐘至海鮮熟透、水分吸乾。最後大火高溫烤30秒聽見噼啪聲（Socarrat黃金鍋巴成形）。", duration: 10 },
      { instruction: "出爐撒香菜、排上新鮮檸檬角，趁熱整鐵鍋端上桌。", duration: 5 },
    ],
    tags: ["西餐", "西班牙", "海鮮飯", "Paella", "海鮮", "蝦", "青口", "鍋巴", "宴客", "廚神挑戰"],
  },
  {
    name: "韓式炸醬麵",
    description: "韓國中華料理之魂 Jajangmyeon！特製黑春醬（Chunjang）與五花肉丁、大量洋蔥碎慢火炒成極其烏黑、甘甜香濃嘅炸醬，淋在煙韌手擀麵上。",
    cookTime: 25,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "韓式",
    ingredients: [
      { name: "韓式新鮮手擀麵或拉麵", quantity: "2", unit: "人份", category: "其他" },
      { name: "韓式黑春醬", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "五花豬肉（切細丁）", quantity: "100", unit: "克", category: "肉類" },
      { name: "黃金洋蔥/西葫蘆/馬鈴薯", quantity: "各1/2", unit: "個/個/個", category: "蔬菜" },
      { name: "白糖/生粉水", quantity: "1.5湯匙/適量", unit: "", category: "調味料" },
      { name: "新鮮青瓜絲（裝飾）", quantity: "少許", unit: "", category: "蔬菜" },
    ],
    steps: [
      { instruction: "所有蔬菜同五花肉切成1厘米小丁。熱鑊落多啲油，小火將黑春醬反覆煸炒2-3分鐘（炒出香味、去除苦澀味），盛起醬，保留油。", duration: 8 },
      { instruction: "用原油大火爆炒五花肉丁至出油，加入洋蔥丁、西葫蘆丁同薯仔丁大火翻炒3分鐘。", duration: 5 },
      { instruction: "倒入炒好嘅黑春醬、白糖同一小杯水煮滾，中火蓋蓋煮8分鐘至蔬菜軟熟。倒入生粉水勾芡使炸醬烏黑濃稠（炸醬）。", duration: 7 },
      { instruction: "手擀麵煮熟過溫水瀝乾，盛碗。淋上厚厚一層滾熱炸醬，放上青瓜絲即成，拌勻食用，醬香甜美。", duration: 5 },
    ],
    tags: ["韓式", "炸醬麵", "黑春醬", "豬肉", "洋蔥", "中華料理", "甜香", "簡單", "30 分鐘內", "落飯"],
  },
  {
    name: "日式炒烏冬",
    description: "經典 Yaki Udon！Q彈有嚼勁嘅烏冬麵，與豬肉薄片、高麗菜絲在大火高溫中，以柴魚高湯、日式生抽爆炒，鑊氣十足。",
    cookTime: 15,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "日式",
    ingredients: [
      { name: "日式真空或冷凍烏冬麵", quantity: "2", unit: "包", category: "其他" },
      { name: "豬肉薄片", quantity: "100", unit: "克", category: "肉類" },
      { name: "椰菜（高麗菜）/洋蔥/胡蘿蔔（切絲）", quantity: "各50", unit: "克", category: "蔬菜" },
      { name: "日式生抽/味醂", quantity: "各1.5", unit: "湯匙", category: "調味料" },
      { name: "柴魚片（鰹魚花）", quantity: "少許", unit: "", category: "其他" },
      { name: "食油", quantity: "1.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "烏冬下滾水燙1分鐘撥散，撈起瀝乾。蔬菜切細絲。肉片切小段。", duration: 5 },
      { instruction: "大火熱平底鑊落油，爆香洋蔥胡蘿蔔絲，下豬肉片快速炒變色。下椰菜絲大火炒1分鐘。", duration: 5 },
      { instruction: "倒入烏冬麵，淋入日式醬油、味醂與少許鹽，轉大火猛火極速翻炒2分鐘，使麵條完全吸收醬汁焦香。", duration: 3 },
      { instruction: "出鑊盛盤，撒上大量柴魚片，趁熱看柴魚在麵上跳舞即可享用。", duration: 2 },
    ],
    tags: ["日式", "和風", "炒烏冬", "烏冬", "豬肉", "蔬菜", "鑊氣", "15 分鐘內", "簡單", "快手"],
  },
  {
    name: "意大利千層麵",
    description: "經典 Lasagna！千層麵皮（Pasta sheets）層層堆疊上無敵濃郁嘅番茄牛肉肉醬、香軟細緻嘅羅馬白汁（Bechamel）同拉絲馬蘇里拉芝士，焗烤至焦黃，層次絕美。",
    cookTime: 60,
    servings: 4,
    difficulty: "困難",
    recipeCategory: "西餐",
    ingredients: [
      { name: "意大利千層麵皮（免煮）", quantity: "8", unit: "張", category: "其他" },
      { name: "香濃番茄牛肉肉醬（Bolognese）", quantity: "2", unit: "杯", category: "肉類" },
      { name: "法式白汁（Bechamel）", quantity: "1.5", unit: "杯", category: "調味料" },
      { name: "馬蘇里拉芝士碎", quantity: "1", unit: "杯", category: "其他" },
      { name: "帕馬森芝士粉", quantity: "3", unit: "湯匙", category: "其他" },
    ],
    steps: [
      { instruction: "準備好肉醬與Bechamel白汁（牛油炒麵粉，加牛奶煮成濃稠奶白色汁）。焗爐預熱180度。", duration: 15 },
      { instruction: "在長方形深焗盤底，先抹上一層薄肉醬。鋪上一層千層麵皮，抹上一層Bechamel白汁，鋪上一層厚肉醬，撒上芝士碎。", duration: 10 },
      { instruction: "重複此「麵皮-白汁-肉醬-芝士」疊加結構共3-4層。最頂層均勻覆蓋上滿滿嘅馬蘇里拉芝士碎與帕馬森芝士粉。", duration: 15 },
      { instruction: "蓋上錫紙烤25分鐘，掀開錫紙继续焗15分鐘，至表面芝士融化呈金黃焦黃斑點、氣泡起微焦。稍微放置10分鐘切大塊即享層次分明嘅美味。", duration: 20 },
    ],
    tags: ["西餐", "意式", "千層麵", "Lasagna", "肉醬", "白汁", "芝士", "拉絲", "焗", "慢煮", "困難"],
  },
  {
    name: "英式下午茶鬆餅",
    description: "經典 Scone！烘烤至金黃、外皮焦香、中間自然橫向裂開嘅傳統鬆餅，散發濃厚乳香，點上鮮忌廉同草莓醬，英式下午茶之極。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "甜品",
    ingredients: [
      { name: "自發麵粉（或低筋粉加泡打粉）", quantity: "200", unit: "克", category: "其他" },
      { name: "冷無鹽牛油（切小方塊）", quantity: "50", unit: "克", category: "調味料" },
      { name: "白糖/牛奶", quantity: "30克/100毫升", unit: "", category: "其他" },
      { name: "雞蛋液（刷表面）", quantity: "1", unit: "隻", category: "其他" },
      { name: "英式凝脂奶油（Clotted Cream）/草莓醬", quantity: "適量", unit: "", category: "其他" },
    ],
    steps: [
      { instruction: "麵粉與糖混合。將冰冷硬牛油粒放入麵粉，用指尖迅速將牛油與麵粉搓捏成均勻嘅細沙粒狀（切忌牛油融化）。", duration: 10 },
      { instruction: "倒入牛奶，用刮刀迅速聚合成麵團（不可過度揉捏防出筋，鬆軟秘訣）。用擀麵杖壓成2.5厘米厚片，用圓形模具壓出6個圓鬆餅。", duration: 5 },
      { instruction: "排入烤盤，表面刷一層薄薄嘅蛋液（只刷頂部，防阻礙其橫向膨脹裂開）。", duration: 3 },
      { instruction: "放入預熱200度嘅焗爐中烤烤12-15分鐘，至鬆餅膨脹長高一倍、表面金黃。切開點忌廉和果醬食用。", duration: 12 },
    ],
    tags: ["甜品", "英式", "下午茶", "鬆餅", "Scone", "牛油", "香脆", "簡單", "30 分鐘內"],
  },
];
