export const HK_COLD_SOUP_RECIPES = [
  {
    name: "口水雞",
    description: "川式名菜在港大受歡迎！嫩滑雞肉淋上香辣刺激、帶有花生芝麻香嘅紅油醬汁，冷盤惹味至極。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "鮮雞髀肉", quantity: "400", unit: "克", category: "肉類" },
      { name: "自製或現成紅油", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "蒜泥/薑末", quantity: "各1", unit: "湯匙", category: "調味料" },
      { name: "炸花生碎/白芝麻", quantity: "少許", unit: "", category: "調味料" },
      { name: "生抽/花椒油", quantity: "各1", unit: "湯匙", category: "調味料" },
      { name: "糖/香醋", quantity: "各1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "雞髀肉與薑蔥酒一同冷水下鍋，煮15分鐘至熟透，撈起立刻泡冰水（皮脆肉嫩嘅秘訣），瀝乾切條擺盤。", duration: 15 },
      { instruction: "調口水雞汁：紅油、生抽、花椒油、蒜泥、薑末、糖、香醋同少許雞湯攪勻。", duration: 5 },
      { instruction: "將調好嘅口水汁淋在雞髀肉表面。", duration: 2 },
      { instruction: "灑上炸花生碎、白芝麻同香菜碎即可，冷藏半小時食更佳。", duration: 30 },
    ],
    tags: ["港式", "香辣", "開胃", "送酒", "中等", "30 分鐘內"],
  },
  {
    name: "沙薑手撕雞",
    description: "傳統粵菜名物，雞肉煮熟放涼後手撕成條，拌入沙薑粉、熟芝麻同香油，沙薑香氣醇厚獨特。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮走地雞（或大雞髀）", quantity: "1/2", unit: "隻", category: "肉類" },
      { name: "優質沙薑粉", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "熟白芝麻", quantity: "1", unit: "湯匙", category: "乾貨" },
      { name: "香菜段/蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "鹽/雞粉/麻油", quantity: "適量", unit: "", category: "調味料" },
      { name: "花生油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "雞隻洗淨蒸熟或用薑蔥水浸熟。撈起泡冰水降溫，抹乾水分。", duration: 20 },
      { instruction: "用雙手順着肌肉紋理將雞肉撕成細條，剔除骨頭，裝大碗中。", duration: 10 },
      { instruction: "調沙薑油：沙薑粉加鹽、雞粉。燒熱花生油淋在沙薑粉上激發香氣，加入麻油。", duration: 3 },
      { instruction: "將沙薑油、熟芝麻、香菜段倒入雞絲中，戴上手套抓拌均勻即可裝盤。", duration: 2 },
    ],
    tags: ["港式", "經典", "香濃", "宴客", "中等"],
  },
  {
    name: "沙薑浸滑雞",
    description: "雞肉經微滾水慢火「浸熟」，保持極致滑嫩。淋上新鮮剁沙薑爆香嘅熱油醬汁，沙薑控最愛。",
    cookTime: 30,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮走地雞", quantity: "1/2", unit: "隻", category: "肉類" },
      { name: "新鮮沙薑（剁碎）", quantity: "50", unit: "克", category: "調味料" },
      { name: "生抽", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "花生油", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "半隻雞洗淨。大鍋加水燒開，手提雞頭三次「三提三浸」適應溫度，然後把整隻雞浸入水中，關火蓋蓋，用餘溫浸熟25分鐘。", duration: 25 },
      { instruction: "撈起沖冰水，切件擺盤。新鮮沙薑剁細碎放小碗中加少許鹽。", duration: 5 },
      { instruction: "燒熱3湯匙花生油至冒煙，澆在沙薑碎上，加入生抽調成沙薑沾醬。可直接淋在雞肉上或作沾醬。", duration: 3 },
    ],
    tags: ["港式", "經典", "滑嫩", "鮮味", "簡單", "30 分鐘內"],
  },
  {
    name: "白切雞",
    description: "粵菜嘅至高境界，不加花哨調味。以慢火浸熟保持肉質滑溜、皮脆肉嫩，蘸上薑蔥蓉，百吃不厭。",
    cookTime: 30,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮三黃雞", quantity: "1", unit: "隻", category: "肉類" },
      { name: "薑/小蔥", quantity: "大量", unit: "", category: "調味料" },
      { name: "鹽", quantity: "1.5", unit: "茶匙", category: "調味料" },
      { name: "花生油", quantity: "4", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "三黃雞洗淨抹乾。大鍋加水（沒過整隻雞）、薑片同蔥結燒開，轉極小火，將雞放入「三提三浸」後完全浸入，保持水微滾狀態低溫慢火浸25分鐘。", duration: 25 },
      { instruction: "撈起立刻放入冰水中冷卻10分鐘（形成雞皮與肉之間嘅皮凍，極致爽脆），撈出瀝乾，外皮刷上一層薄薄嘅香油，斬件擺盤。", duration: 15 },
      { instruction: "製作薑蔥蓉沾醬：薑、小蔥極細剁茸放碗中加鹽。燒熱花生油淋在薑蔥蓉上拌勻即成。", duration: 5 },
    ],
    tags: ["港式", "經典", "滑嫩", "薑蔥", "清淡", "宴客", "中等"],
  },
  {
    name: "豉油雞",
    description: "又稱醬油雞。用秘製豉油滷水汁慢火浸煮，雞肉吸飽豉油玫瑰露香氣，紅潤嫩滑，鹹甜適中。",
    cookTime: 40,
    servings: 4,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "三黃雞", quantity: "1/2", unit: "隻", category: "肉類" },
      { name: "優質生抽", quantity: "1", unit: "杯", category: "調味料" },
      { name: "老抽/玫瑰露酒", quantity: "適量", unit: "", category: "調味料" },
      { name: "冰糖", quantity: "50", unit: "克", category: "調味料" },
      { name: "薑片/蔥/八角/桂皮", quantity: "少許", unit: "", category: "調味料" },
      { name: "水", quantity: "1.5", unit: "杯", category: "其他" },
    ],
    steps: [
      { instruction: "半隻雞洗淨。鍋中倒入生抽、老抽、水、冰糖、八角、桂皮同薑蔥，煮滾製成豉油汁。", duration: 10 },
      { instruction: "將雞肉放入豉油汁中，大火燒開，轉小火，不斷將豉油汁澆淋在雞身外皮上。蓋蓋慢火浸煮20分鐘。", duration: 20 },
      { instruction: "期間翻面一次。關火前灒少許玫瑰露酒，關火後蓋蓋焗15分鐘使之入味。", duration: 15 },
      { instruction: "取出放涼，斬件盛盤，淋上豉油原汁即可。", duration: 5 },
    ],
    tags: ["港式", "經典", "家常菜", "滑嫩", "簡單", "30 分鐘以上"],
  },
  {
    name: "潮州滷水拼盤",
    description: "潮州菜代表作！精選老滷水慢火熬煮，包含滷大腸、滷雞翼同炸豆腐，鹹香透骨，滋味無窮。",
    cookTime: 60,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "豬大腸（已洗淨飛水）", quantity: "200", unit: "克", category: "肉類" },
      { name: "雞翼", quantity: "4", unit: "隻", category: "肉類" },
      { name: "炸豆腐/板豆腐", quantity: "1", unit: "磚", category: "豆腐" },
      { name: "潮州老滷水汁", quantity: "3", unit: "杯", category: "調味料" },
      { name: "薑片/蒜頭/紅椒", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "大腸、雞翼先飛水備用。板豆腐切厚件炸至微金黃（炸豆腐更易吸汁）。", duration: 15 },
      { instruction: "煲中倒入潮州老滷水汁，加入薑片、蒜頭、紅椒、炸豆腐同大腸慢火煮30分鐘。", duration: 30 },
      { instruction: "加入雞翼，再慢火煮20分鐘至所有食材完全入味、大腸軟輭。關火焗15分鐘更佳。", duration: 20 },
      { instruction: "大腸切片，與豆腐、雞翼整齊排好擺盤，淋少許原滷水汁即可。", duration: 5 },
    ],
    tags: ["港式", "經典", "鹹香", "中等", "60 分鐘以上"],
  },
  {
    name: "五香牛肉",
    description: "選用帶筋牛腱肉（牛展），加入八角、花椒、肉桂等五香料慢火熬煮至香濃爽脆，冷盤至尊。",
    cookTime: 120,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "牛展（牛腱肉）", quantity: "600", unit: "克", category: "肉類" },
      { name: "生抽/老抽/冰糖", quantity: "適量", unit: "", category: "調味料" },
      { name: "五香滷包（八角/花椒/桂皮/陳皮）", quantity: "1", unit: "包", category: "調味料" },
      { name: "薑片/料酒", quantity: "少許", unit: "", category: "調味料" },
      { name: "麻油/生抽（調味用）", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "牛展整條洗淨，冷水下鍋加料酒、薑片飛水8分鐘，撈起用冷水洗淨肉縮緊。", duration: 15 },
      { instruction: "煲中加足量水，放入五香滷包、生抽、老抽、冰糖同薑片煮滾，放入牛腱肉大火煮滾撇去浮沫。", duration: 15 },
      { instruction: "轉小火慢火燉煮90分鐘，直至用筷子能輕易穿透但仍帶彈彈口感。關火，讓牛腱在滷汁中泡過夜最入味。", duration: 90 },
      { instruction: "撈出晾乾，放入冰箱冷藏2小時。取出切薄片，淋上少許原汁同麻油即可享用。", duration: 10 },
    ],
    tags: ["港式", "經典", "香濃", "慢煮", "60 分鐘以上", "中等"],
  },
  {
    name: "花雕醉雞",
    description: "上海名盤，紹興花雕酒嘅醇厚香氣配上嫩滑雞卷，冷藏後皮凍彈牙，酒香馥郁，極盡尊貴。",
    cookTime: 40,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "無骨去皮大雞髀", quantity: "2", unit: "隻", category: "肉類" },
      { name: "三年或五年花雕酒", quantity: "1.5", unit: "杯", category: "調味料" },
      { name: "糟滷（可選）", quantity: "1/2", unit: "杯", category: "調味料" },
      { name: "杞子/當歸片/紅棗", quantity: "少許", unit: "", category: "其他" },
      { name: "鹽/糖", quantity: "適量", unit: "", category: "調味料" },
      { name: "雞湯", quantity: "1", unit: "杯", category: "其他" },
    ],
    steps: [
      { instruction: "雞髀肉兩面抹鹽，用錫紙緊緊捲成圓筒狀（雞卷），兩端擰緊防漏。大火蒸20分鐘至熟透，立刻投入冰水中冷卻15分鐘。", duration: 30 },
      { instruction: "調醉雞汁：將雞湯、花雕酒、糟滷、杞子、紅棗片、當歸同少許糖混合煮滾，放涼備用（酒要等湯放涼後加，防酒香蒸發）。", duration: 10 },
      { instruction: "撕開錫紙，將雞卷放入完全沒過嘅醉雞汁中，蓋好密封放入冰箱冷藏24小時。", duration: 10 },
      { instruction: "食用時取出切薄片，排盤，淋上少許醉雞汁即成。", duration: 5 },
    ],
    tags: ["港式", "經典", "宴客", "進階", "滋補"],
  },
  {
    name: "涼拌皮蛋豆腐",
    description: "極為清爽、快手嘅中式冷盤。嫩滑皮蛋同香軟豆腐淋上香辣酸甜嘅大蒜熟油汁，開胃消暑。",
    cookTime: 10,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "盒裝嫩豆腐", quantity: "1", unit: "盒", category: "豆腐" },
      { name: "優質皮蛋", quantity: "2", unit: "隻", category: "其他" },
      { name: "肉鬆/蔥花", quantity: "少許", unit: "", category: "其他" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "香醋", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "蒜泥/辣椒油/麻油", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "嫩豆腐切成厚片擺在盤正中（可先用微波爐加熱1分鐘去多餘豆水，再放涼）。皮蛋剝殼切小粒圍繞在豆腐兩側。", duration: 5 },
      { instruction: "調汁：生抽、香醋、蒜泥、辣椒油、麻油與少許糖攪勻，均勻淋在豆腐皮蛋上。", duration: 3 },
      { instruction: "撒上大量蔥花、肉鬆同香菜碎即可，冷藏後食風味更佳。", duration: 2 },
    ],
    tags: ["港式", "家常菜", "清淡", "15 分鐘內", "快手", "簡單", "新手"],
  },
  {
    name: "涼拌拍青瓜",
    description: "夏天必吃開胃小菜！青瓜用刀拍扁裂開，更容易吸收陳醋、大蒜、辣椒油嘅香氣，酸辣脆爽。",
    cookTime: 10,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "溫室小青瓜", quantity: "2", unit: "條", category: "蔬菜" },
      { name: "蒜頭", quantity: "4", unit: "瓣", category: "調味料" },
      { name: "陳醋/香醋", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "生抽/辣椒油/麻油", quantity: "各1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "青瓜洗淨，切掉兩頭。用大菜刀用力拍扁，使青瓜皮肉自然開裂，然後斜切成一口大小段。", duration: 5 },
      { instruction: "加入1/2茶匙鹽醃5分鐘，倒出多餘生水。蒜頭剁泥。", duration: 3 },
      { instruction: "調入陳醋、糖、生抽、辣椒油、麻油同蒜泥，用力抓拌均勻，放冰箱冷藏半小時後食用最為脆爽。", duration: 2 },
    ],
    tags: ["港式", "家常菜", "蔬菜", "15 分鐘內", "快手", "簡單"],
  },
  {
    name: "上湯浸莧菜",
    description: "以皮蛋、鹹蛋、大蒜與濃郁肉湯（上湯）熬成湯底，浸入鮮嫩嘅紅莧菜，湯色呈迷人粉紅，清甜無比。",
    cookTime: 15,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "莧菜", quantity: "300", unit: "克", category: "蔬菜" },
      { name: "皮蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "鹹鴨蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "蒜頭（整瓣炸香）", quantity: "4", unit: "瓣", category: "調味料" },
      { name: "高湯或水", quantity: "1.5", unit: "杯", category: "其他" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "莧菜洗淨，切段。皮蛋鹹蛋剝殼切小粒。蒜頭拍扁用油煎至表面金黃。", duration: 8 },
      { instruction: "鍋中倒入高湯、炸蒜頭、皮蛋鹹蛋粒煮滾，中小火滾3-4分鐘，直至高湯變白帶蛋油香。", duration: 4 },
      { instruction: "放入莧菜，大火浸煮1-2分鐘至菜軟身，加少許鹽調味即可整碗呈上。", duration: 3 },
    ],
    tags: ["港式", "家常菜", "蔬菜", "清甜", "簡單", "15 分鐘內"],
  },
  {
    name: "金銀蛋浸絲瓜",
    description: "清甜嘅絲瓜吸飽皮蛋、鹹蛋同高湯嘅精華，絲瓜軟糯多汁，金銀蛋油香十足，夏天極品養生菜。",
    cookTime: 15,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "勝瓜（角瓜或絲瓜）", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "皮蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "鹹鴨蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "蒜蓉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "高湯或水", quantity: "1.5", unit: "杯", category: "其他" },
    ],
    steps: [
      { instruction: "絲瓜去硬皮切滾刀塊。皮蛋鹹蛋切碎。熱鑊下油爆香蒜蓉、皮蛋鹹蛋粒。", duration: 8 },
      { instruction: "倒入高湯煮滾，中小火滾出奶白色湯汁。", duration: 3 },
      { instruction: "放入絲瓜塊，大火滾煮3-4分鐘至絲瓜變輭、半透明即可起碟。", duration: 4 },
    ],
    tags: ["港式", "家常菜", "蔬菜", "簡單", "15 分鐘內"],
  },
  {
    name: "鮮蝦蒸水蛋",
    description: "極致滑嫩嘅蒸蛋，面頭鋪上爽口肥美嘅鮮蝦仁，蛋羹如布丁般滑軟，兼具蛋香同鮮甜海鮮味。",
    cookTime: 20,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞蛋", quantity: "3", unit: "隻", category: "其他" },
      { name: "鮮蝦仁", quantity: "6", unit: "隻", category: "海鮮" },
      { name: "溫水", quantity: "180", unit: "毫升", category: "其他" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "鹽/生粉/麻油", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "蝦仁洗淨用鹽同生粉略醃。雞蛋打散，加入1.5倍雞蛋量嘅溫水，加少許鹽輕輕攪勻，過濾篩網去除氣泡倒入深盤。", duration: 10 },
      { instruction: "封上保鮮膜戳孔，水大滾，放入中大火蒸8分鐘至蛋液八成定型。", duration: 8 },
      { instruction: "開蓋，輕輕將鮮蝦仁排在蒸蛋表面，重新蓋蓋保鮮膜蒸2-3分鐘至蝦仁變紅熟透。出鍋淋生抽同麻油。", duration: 2 },
    ],
    tags: ["港式", "家常菜", "蒸", "海鮮", "滑嫩", "簡單", "30 分鐘內", "小朋友"],
  },
  {
    name: "魚湯勝瓜浸魚餅",
    description: "以奶白色鮮魚湯，配上滑軟嘅鯪魚肉餅同清甜勝瓜一同浸熟，鮮味加倍，湯汁令人一飲而盡。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "鯪魚肉（已調味起膠）", quantity: "150", unit: "克", category: "海鮮" },
      { name: "勝瓜（絲瓜）", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "新鮮奶白魚湯（或大鯽魚湯）", quantity: "2", unit: "杯", category: "湯" },
      { name: "薑絲/蔥花", quantity: "少許", unit: "", category: "調味料" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "勝瓜去硬皮切長段。鯪魚肉在平底鑊中兩面略煎至金黃，切條（魚餅條）。", duration: 10 },
      { instruction: "將鮮魚湯倒入煲中，加入薑絲煮滾。", duration: 5 },
      { instruction: "下勝瓜段同魚餅條，中火滾煮6-8分鐘至勝瓜變軟，加少許鹽調味，灑蔥花起鍋。", duration: 10 },
    ],
    tags: ["港式", "家常菜", "海鮮", "清淡", "滋補", "簡單", "30 分鐘內"],
  },
  {
    name: "港式辣子雞",
    description: "重慶辣子雞嘅港式溫和版！去骨雞脾丁炸至金黃酥脆，配乾辣椒同花椒爆炒，椒香十足而不燥辣。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞髀肉（切方塊）", quantity: "400", unit: "克", category: "肉類" },
      { name: "乾紅辣椒（剪段）", quantity: "1", unit: "碗", category: "調味料" },
      { name: "花椒粒", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "生抽/生粉/料酒", quantity: "適量", unit: "", category: "調味料" },
      { name: "熟白芝麻", quantity: "少許", unit: "", category: "調味料" },
      { name: "食油", quantity: "大量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "雞丁用生抽、料酒、生粉醃20分鐘。乾辣椒去籽剪段。", duration: 20 },
      { instruction: "大火熱油，下雞丁炸至金黃酥脆（約5分鐘），撈起。大火高溫重炸10秒逼油起酥。", duration: 5 },
      { instruction: "鍋留少許油，小火慢慢煸香花椒同乾辣椒段至微變色，倒入雞丁大火快速翻炒，撒入白芝麻即成。", duration: 5 },
    ],
    tags: ["港式", "經典", "大牌檔", "炸", "香辣", "送酒", "中等"],
  },
  {
    name: "酸甜咕嚕魚塊",
    description: "避開帶骨繁瑣，鮮嫩龍脷柳切塊沾炸粉炸至酥脆，掛上酸甜誘人嘅咕嚕醬，開胃無刺。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "龍脷柳或斑塊", quantity: "300", unit: "克", category: "海鮮" },
      { name: "青椒/紅椒/洋蔥", quantity: "各1/2", unit: "個", category: "蔬菜" },
      { name: "罐頭菠蘿", quantity: "3", unit: "片", category: "蔬菜" },
      { name: "茄汁", quantity: "2.5", unit: "湯匙", category: "調味料" },
      { name: "白醋/糖", quantity: "各1.5", unit: "湯匙", category: "調味料" },
      { name: "生粉/炸粉", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "魚柳切塊，用少許鹽和胡椒粉醃10分鐘，裹上厚麵粉炸漿。彩椒洋蔥切塊。", duration: 12 },
      { instruction: "中火下油鑊炸魚塊至兩面金黃硬脆（約4分鐘），撈起。", duration: 5 },
      { instruction: "調好咕嚕醬汁。爆香青紅椒洋蔥，倒入醬汁煮滾，下魚塊同菠蘿，大火極速翻炒兜勻即可。", duration: 8 },
    ],
    tags: ["港式", "家常菜", "炸", "海鮮", "酸甜", "開胃", "30 分鐘內", "簡單", "小朋友"],
  },
  {
    name: "粟米斑塊",
    description: "港式茶餐廳下午茶、晚市無敵經典！脆炸龍脷柳淋上香甜滑潤嘅忌廉粟米蛋花醬，極其美味。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "龍脷柳塊", quantity: "300", unit: "克", category: "海鮮" },
      { name: "忌廉粟米罐頭（粟米蓉）", quantity: "1", unit: "罐", category: "其他" },
      { name: "雞蛋液", quantity: "1", unit: "隻", category: "其他" },
      { name: "炸粉/生粉", quantity: "適量", unit: "", category: "調味料" },
      { name: "鹽/胡椒粉", quantity: "少許", unit: "", category: "調味料" },
      { name: "食油", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "魚塊用少許鹽胡椒醃製，裹上調水嘅炸粉脆漿。中大火炸至外皮香脆金黃，盛起排盤。", duration: 15 },
      { instruction: "另起鍋倒入忌廉粟米蓉加1/4杯水煮滾，落少許鹽，關小火淋入雞蛋液攪出均勻蛋花醬。", duration: 8 },
      { instruction: "將金黃滾燙嘅粟米蛋花醬均勻澆在炸魚柳（斑塊）表面即可，金黃酥香與甜滑相配。", duration: 2 },
    ],
    tags: ["港式", "經典", "炸", "海鮮", "簡單", "30 分鐘內", "小朋友"],
  },
  {
    name: "八寶豆腐",
    description: "板豆腐與蝦仁、肉粒、冬菇、筍片等八種豐富配料慢火同燴，豆腐滑溜，配料豐富多層次。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "板豆腐（切大方塊）", quantity: "2", unit: "盒", category: "豆腐" },
      { name: "鮮蝦仁/冬菇/叉燒粒", quantity: "各30", unit: "克", category: "其他" },
      { name: "青豆/胡蘿蔔丁/筍丁", quantity: "少許", unit: "", category: "蔬菜" },
      { name: "蠔油", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "生粉水", quantity: "1", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "豆腐切厚塊稍微飛水瀝乾。配料全部切細丁。蝦仁略醃。", duration: 10 },
      { instruction: "爆香蒜茸，下肉粒、冬菇、蝦仁等配料丁大火炒香，倒入一小杯高湯、蠔油煮滾。", duration: 5 },
      { instruction: "滑入豆腐塊，中火燴煮8-10分鐘使豆腐吸汁。最後倒入生粉水勾芡，出碟。", duration: 10 },
    ],
    tags: ["港式", "家常菜", "炆", "海鮮", "簡單", "30 分鐘內"],
  },
  {
    name: "賽螃蟹",
    description: "宮廷名菜，無蟹卻勝似蟹！以滑嫩蛋白模仿蟹肉，鹹蛋黃代替蟹黃，佐以陳醋與薑絲，鮮美無比。",
    cookTime: 20,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "蛋白", quantity: "4", unit: "隻", category: "其他" },
      { name: "鹹蛋黃（蒸熟）", quantity: "1", unit: "個", category: "其他" },
      { name: "鮮魚肉或蟹柳（切碎）", quantity: "50", unit: "克", category: "海鮮" },
      { name: "牛奶", quantity: "2", unit: "湯匙", category: "其他" },
      { name: "鹽/糖", quantity: "適量", unit: "", category: "調味料" },
      { name: "鎮江香醋/薑絲（伴碟）", quantity: "適量", unit: "", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "蛋白打散，與牛奶、魚肉碎同少許鹽攪勻（牛奶使蛋白更雪白滑嫩）。鹹蛋黃壓碎碎。", duration: 10 },
      { instruction: "燒熱油至中低溫，倒入蛋白液，用筷子快速朝一個方向滑炒，使蛋白呈半熟軟嫩片狀，立刻盛碟呈山狀。", duration: 5 },
      { instruction: "蛋白頂部放上熟鹹蛋黃碎（蟹黃）。食用時澆淋調好嘅香醋同薑絲，鮮甜似蟹肉。", duration: 5 },
    ],
    tags: ["港式", "經典", "炒", "海鮮", "鮮味", "清淡", "中等", "30 分鐘內"],
  },
  {
    name: "什錦炒雜菜",
    description: "大白菜、西蘭花、冬菇、胡蘿蔔、草菇等多種蔬菜大火爆炒，爽脆可口，營養滿分，清腸健康之選。",
    cookTime: 15,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "西蘭花/椰菜花/大白菜", quantity: "200", unit: "克", category: "蔬菜" },
      { name: "草菇/冬菇片", quantity: "50", unit: "克", category: "蔬菜" },
      { name: "胡蘿蔔片", quantity: "少許", unit: "", category: "蔬菜" },
      { name: "蒜片", quantity: "2", unit: "瓣", category: "調味料" },
      { name: "鹽/糖", quantity: "適量", unit: "", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "所有蔬菜洗淨，西蘭花切小朵、大白菜切段。西蘭花和胡蘿蔔片汆水30秒撈出。", duration: 8 },
      { instruction: "大火熱油，爆香蒜片，下所有雜菜同菇類片，猛火大火快炒2分鐘。", duration: 3 },
      { instruction: "加少許水，下鹽糖調味，蓋蓋焗1分鐘，開蓋快速炒勻即可出碟。", duration: 4 },
    ],
    tags: ["港式", "家常菜", "炒", "蔬菜", "健康", "低卡", "素食", "簡單", "15 分鐘內"],
  },
];
