export const CUSTOM_QUICK_RECIPES = [
  {
    name: "上湯枸杞浸菜心",
    description: "清甜健康嘅快手滾湯菜，枸杞明目，菜心爽脆，上湯鮮美。",
    cookTime: 12,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "菜心", quantity: "300", unit: "克", category: "蔬菜" },
      { name: "枸杞", quantity: "15", unit: "克", category: "蔬菜" },
      { name: "薑絲", quantity: "5", unit: "克", category: "調味料" },
      { name: "清雞湯", quantity: "500", unit: "毫升", category: "調味料" },
      { name: "鹽", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "菜心洗淨切段，枸杞洗淨浸泡，薑切絲。", duration: 4 },
      { instruction: "鍋中倒入清雞湯同薑絲，大火燒開。", duration: 3 },
      { instruction: "加入菜心同枸杞，煮至菜心變軟（約3-4分鐘）。", duration: 4 },
      { instruction: "加少許鹽調味即可上碟。", duration: 1 },
    ],
    tags: ["15 分鐘內", "快手", "簡單", "清淡", "健康"],
  },
  {
    name: "洋蔥炒豬肉片",
    description: "非常惹味下飯嘅家常小炒，洋蔥香甜，肉片滑嫩，簡單快捷。",
    cookTime: 15,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "豬肉片", quantity: "200", unit: "克", category: "肉類" },
      { name: "洋蔥", quantity: "1", unit: "個", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "老抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "洋蔥切絲；豬肉片加生抽、糖同生粉醃10分鐘。", duration: 5 },
      { instruction: "大火燒熱鑊落油，下肉片炒至八成熟，盛起備用。", duration: 3 },
      { instruction: "同一鑊下洋蔥絲翻炒至變軟出香味。", duration: 4 },
      { instruction: "倒回肉片，加老抽同少許水，大火快速翻炒均勻即可。", duration: 3 },
    ],
    tags: ["15 分鐘內", "快手", "簡單", "家常", "下飯"],
  },
  {
    name: "勝瓜炒蝦仁",
    description: "勝瓜（絲瓜）清甜多汁，蝦仁爽口彈牙，係一道清爽美味嘅快手家常菜。",
    cookTime: 12,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "勝瓜", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "蝦仁", quantity: "150", unit: "克", category: "海鮮" },
      { name: "蒜蓉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "薑片", quantity: "2", unit: "片", category: "調味料" },
      { name: "鹽", quantity: "適量", unit: "", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "勝瓜去硬皮切滾刀塊；蝦仁洗淨瀝乾加少許鹽同紹興酒醃5分鐘。", duration: 4 },
      { instruction: "大火熱鑊落油，爆香蒜蓉同薑片，下蝦仁炒至變色盛起。", duration: 3 },
      { instruction: "下勝瓜塊翻炒，加少許水，蓋上鍋蓋燜煮2分鐘至勝瓜變軟。", duration: 3 },
      { instruction: "倒回蝦仁，加鹽調味，快速炒勻即可上碟。", duration: 2 },
    ],
    tags: ["15 分鐘內", "快手", "簡單", "鮮味", "家常"],
  },
  {
    name: "薑蔥生蠔煲",
    description: "經典大牌檔風味，生蠔肥美滑嫩，薑蔥香濃惹味，用砂鍋保溫效果極佳。",
    cookTime: 25,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "生蠔", quantity: "8", unit: "隻", category: "海鮮" },
      { name: "薑片", quantity: "8", unit: "片", category: "調味料" },
      { name: "蔥段", quantity: "3", unit: "條", category: "蔬菜" },
      { name: "蒜頭", quantity: "4", unit: "瓣", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蠔油", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "生粉", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "生蠔用生粉洗淨粘液，汆水10秒鎖住水分，撈出瀝乾，拍上薄薄生粉。", duration: 8 },
      { instruction: "熱鑊下油，下生蠔煎至兩面金黃，盛起備用。", duration: 4 },
      { instruction: "砂鍋熱油，爆香薑片、蒜頭同蔥白段。", duration: 4 },
      { instruction: "放入生蠔，淋上生抽、蠔油調成嘅醬汁，灑入蔥綠段同紹興酒，蓋上蓋焗1分鐘即可。", duration: 4 },
    ],
    tags: ["30 分鐘內", "經典", "大牌檔", "煲仔", "海鮮", "送酒"],
  },
  {
    name: "金銀蛋浸莧菜",
    description: "傳統粵菜，莧菜吸收咗皮蛋同鹹蛋嘅鮮味，湯汁濃郁，菜葉軟滑。",
    cookTime: 15,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "莧菜", quantity: "300", unit: "克", category: "蔬菜" },
      { name: "皮蛋", quantity: "1", unit: "個", category: "其他" },
      { name: "鹹蛋黃", quantity: "1", unit: "個", category: "其他" },
      { name: "蒜頭", quantity: "3", unit: "瓣", category: "調味料" },
      { name: "清雞湯", quantity: "400", unit: "毫升", category: "調味料" },
    ],
    steps: [
      { instruction: "莧菜洗淨切段；皮蛋同鹹蛋黃蒸熟切丁；蒜頭拍扁。", duration: 5 },
      { instruction: "熱鍋落油，爆香蒜頭至金黃色。", duration: 2 },
      { instruction: "倒入清雞湯，下皮蛋同鹹蛋黃丁煮至湯汁微白。", duration: 4 },
      { instruction: "放入莧菜，煮至莧菜軟身（約3-4分鐘），加少許鹽調味即可。", duration: 4 },
    ],
    tags: ["15 分鐘內", "快手", "簡單", "鮮味", "家常"],
  },
  {
    name: "南乳煲仔齋",
    description: "香濃下飯嘅經典素食，南乳汁鹹香濃郁，多種食材吸滿湯汁，美味健康。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "大白菜", quantity: "200", unit: "克", category: "蔬菜" },
      { name: "冬菇", quantity: "6", unit: "朵", category: "蔬菜" },
      { name: "炸支竹", quantity: "50", unit: "克", category: "其他" },
      { name: "粉絲", quantity: "1", unit: "包", category: "麵類" },
      { name: "紅豆腐乳(南乳)", quantity: "1.5", unit: "塊", category: "調味料" },
      { name: "薑片", quantity: "3", unit: "片", category: "調味料" },
    ],
    steps: [
      { instruction: "冬菇、支竹同粉絲提前浸軟；大白菜切段；南乳加少許水壓碎成汁。", duration: 8 },
      { instruction: "熱鑊下油爆香薑片，下南乳汁炒香。", duration: 2 },
      { instruction: "加入大白菜、冬菇同支竹翻炒勻，加少許水煮開。", duration: 5 },
      { instruction: "轉至砂鍋中，蓋上蓋中火燜煮8分鐘，最後加入粉絲煮2分鐘吸汁即成。", duration: 10 },
    ],
    tags: ["30 分鐘內", "簡單", "素食", "家常", "煲仔"],
  },
  {
    name: "電飯煲豉油皇雞翼飯",
    description: "一煲熟嘅電飯煲懶人料理，雞翼滑嫩入味，米飯吸滿豉油皇醬汁，極之方便。",
    cookTime: 30,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "米", quantity: "2", unit: "杯", category: "麵類" },
      { name: "雞翼", quantity: "6", unit: "隻", category: "肉類" },
      { name: "生抽", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "老抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "薑片", quantity: "3", unit: "片", category: "調味料" },
    ],
    steps: [
      { instruction: "雞翼用生抽、老抽、糖同薑片醃15分鐘。", duration: 5 },
      { instruction: "米洗淨放入電飯煲，加入平時煮飯水量少2湯匙嘅水（因為醃料有水分）。", duration: 3 },
      { instruction: "將醃好嘅雞翼同醬汁平鋪喺米上面。", duration: 2 },
      { instruction: "按下煮飯掣，煮好後再保溫燜10分鐘，開蓋拌勻即可食用。", duration: 20 },
    ],
    tags: ["30 分鐘內", "簡單", "快手", "電飯煲料理"],
  },
  {
    name: "電飯煲香菇滑雞飯",
    description: "傳統茶餐廳滑雞飯嘅電飯煲改良版，雞肉滑嫩，冬菇香濃，飯粒晶瑩剔透。",
    cookTime: 30,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "米", quantity: "2", unit: "杯", category: "麵類" },
      { name: "雞肉", quantity: "250", unit: "克", category: "肉類" },
      { name: "冬菇", quantity: "4", unit: "朵", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蠔油", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "薑絲", quantity: "5", unit: "克", category: "調味料" },
    ],
    steps: [
      { instruction: "冬菇浸軟切條；雞肉切塊，加生抽、蠔油、薑絲同生粉醃15分鐘。", duration: 5 },
      { instruction: "米洗淨放入電飯煲，加入適量水。", duration: 3 },
      { instruction: "將冬菇條同醃好嘅雞肉平鋪喺米飯表面。", duration: 2 },
      { instruction: "啟動普通煮飯程式，跳掣後再燜10分鐘，淋上少許熟油同生抽即可。", duration: 20 },
    ],
    tags: ["30 分鐘內", "簡單", "快手", "電飯煲料理", "經典"],
  },
  {
    name: "電飯煲番茄牛肉燉飯",
    description: "網紅原隻番茄飯升級版，番茄酸甜多汁，肥牛滑嫩，芝士拉絲，大人細路都鍾意。",
    cookTime: 30,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "米", quantity: "2", unit: "杯", category: "麵類" },
      { name: "番茄", quantity: "1", unit: "個", category: "蔬菜" },
      { name: "肥牛肉片", quantity: "150", unit: "克", category: "肉類" },
      { name: "黑胡椒", quantity: "適量", unit: "", category: "調味料" },
      { name: "鹽", quantity: "適量", unit: "", category: "調味料" },
      { name: "橄欖油", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "芝士碎", quantity: "30", unit: "克", category: "其他" },
    ],
    steps: [
      { instruction: "米洗淨放入電飯煲，加水平時煮飯量略少（番茄會出水），加橄欖油、鹽同黑胡椒拌勻。", duration: 4 },
      { instruction: "番茄去蒂，頂部劃十字，平放喺電飯煲中間，肥牛鋪喺番茄周圍。", duration: 4 },
      { instruction: "按下煮飯掣。煮好後趁熱撒入芝士碎，將番茄用勺子壓碎，同米飯、肥牛、芝士一起拌勻即可。", duration: 22 },
    ],
    tags: ["30 分鐘內", "簡單", "快手", "電飯煲料理", "酸甜"],
  },
  {
    name: "電飯煲南瓜排骨燜飯",
    description: "南瓜香甜軟糯，排骨滑嫩多汁，一碗飯有齊肉有蔬菜，營養豐富又快手。",
    cookTime: 30,
    servings: 2,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "米", quantity: "2", unit: "杯", category: "麵類" },
      { name: "南瓜", quantity: "150", unit: "克", category: "蔬菜" },
      { name: "小排骨", quantity: "200", unit: "克", category: "肉類" },
      { name: "生抽", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "蠔油", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "薑末", quantity: "5", unit: "克", category: "調味料" },
    ],
    steps: [
      { instruction: "南瓜去籽切小塊；排骨切小段，加生抽、蠔油、薑末醃15分鐘。", duration: 5 },
      { instruction: "米洗淨入電飯煲加水，將醃好嘅排骨同南瓜塊鋪喺米上面。", duration: 3 },
      { instruction: "按下煮飯鍵正常煮飯。", duration: 20 },
      { instruction: "煮好後開蓋拌勻，可以撒少許蔥花增香。", duration: 2 },
    ],
    tags: ["30 分鐘內", "簡單", "快手", "電飯煲料理"],
  },
  {
    name: "電飯煲臘味糯米飯",
    description: "香噴噴嘅廣式臘味糯米飯，唔需要繁瑣嘅蒸鍋手續，用電飯煲就能做出糯口咸香、油潤誘人嘅味道。",
    cookTime: 35,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "糯米", quantity: "1.5", unit: "杯", category: "麵類" },
      { name: "白米", quantity: "0.5", unit: "杯", category: "麵類" },
      { name: "廣式臘腸", quantity: "1", unit: "條", category: "肉類" },
      { name: "臘肉", quantity: "50", unit: "克", category: "肉類" },
      { name: "冬菇", quantity: "3", unit: "朵", category: "蔬菜" },
      { name: "生抽", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "糯米同白米混合洗淨（混合米飯口感更好，唔易太黏）；臘腸、臘肉、浸軟嘅冬菇切小丁。", duration: 8 },
      { instruction: "米洗淨加入平時煮飯水量略少嘅水，加入生抽同糖拌勻。", duration: 3 },
      { instruction: "將臘腸、臘肉、冬菇丁均勻鋪喺米上面。", duration: 2 },
      { instruction: "啟動標準煮飯程序，煮好後燜10分鐘，開蓋拌勻，撒上蔥花即成。", duration: 22 },
    ],
    tags: ["30 分鐘內", "簡單", "快手", "電飯煲料理", "經典"],
  }
];
