export const HK_FRIED_RECIPES = [
  {
    name: "煎釀三寶",
    description: "香港街頭小食傳奇！鯪魚肉釀入青椒、茄子同豆腐，煎至金黃，淋上甜豉油，香口無比。",
    cookTime: 30,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "鯪魚肉（已調味起膠）", quantity: "250", unit: "克", category: "海鮮" },
      { name: "矮瓜（茄子）", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "青椒", quantity: "2", unit: "個", category: "蔬菜" },
      { name: "板豆腐", quantity: "1", unit: "磚", category: "豆腐" },
      { name: "生粉", quantity: "適量", unit: "", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "3", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "青椒切塊去籽；茄子斜切厚片（中間劃一刀不切斷）；豆腐切厚塊。所有食材表面抹上一層薄薄嘅生粉（方便黏住魚肉）。", duration: 15 },
      { instruction: "用抹刀將鯪魚肉結實地釀入青椒、茄子夾同豆腐面上，壓實抹平。", duration: 10 },
      { instruction: "燒熱油，魚肉面朝下，中小火慢煎至魚肉金黃熟透，再翻面煎香外皮。", duration: 10 },
      { instruction: "將生抽、糖同少許水調勻煮滾，淋在煎好嘅三寶上即可。", duration: 2 },
    ],
    tags: ["中菜", "港式", "經典", "小食", "煎", "海鮮", "豆腐", "蔬菜", "街頭小食", "宴客", "進階"],
  },
  {
    name: "香煎紅衫魚",
    description: "老一輩最愛嘅家常煎魚，紅衫魚肉質細嫩，煎到外皮金黃香脆，點少許生抽極之惹味。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮紅衫魚", quantity: "1", unit: "條", category: "海鮮" },
      { name: "薑片", quantity: "3", unit: "片", category: "調味料" },
      { name: "鹽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "紅衫魚洗淨，用廚房紙徹底抹乾魚身內外（煎魚唔彈油、唔黏底嘅關鍵）。", duration: 5 },
      { instruction: "魚身抹上薄薄嘅鹽，醃15分鐘。", duration: 15 },
      { instruction: "大火燒熱鑊，落2湯匙油，爆香薑片，轉中火，放入魚。", duration: 3 },
      { instruction: "中火煎約5-6分鐘，唔好亂動，搖動鑊見魚能滑動時再翻面，煎另一面5分鐘至金黃熟透。", duration: 6 },
    ],
    tags: ["中菜", "港式", "家常菜", "煎", "海鮮", "魚", "香脆", "30 分鐘內", "簡單", "晚餐", "新手"],
  },
  {
    name: "香煎黃花魚",
    description: "黃花魚肉質呈蒜瓣狀，極為鮮嫩，經慢火煎至外酥內嫩，油潤甘香。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "黃花魚", quantity: "1", unit: "條", category: "海鮮" },
      { name: "鹽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "薑絲", quantity: "適量", unit: "", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "黃花魚去鱗去內臟清洗乾淨，用廚房紙完全抹乾，魚身切兩刀，均勻抹上鹽醃製15分鐘。", duration: 10 },
      { instruction: "燒熱鑊，落油爆香薑絲後撈起。轉中火放入黃花魚。", duration: 3 },
      { instruction: "煎至一金黃再翻面，兩面各煎約5-6分鐘至魚皮金黃香脆即可。", duration: 12 },
    ],
    tags: ["中菜", "港式", "家常菜", "煎", "海鮮", "魚", "鮮味", "香脆", "簡單", "30 分鐘內"],
  },
  {
    name: "香煎馬友魚",
    description: "「一鯧二馬友」，馬友魚油脂豐富，煎煮時魚油四溢，魚肉鹹香結實，味道冠絕家常魚。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "馬友魚件或全魚", quantity: "1", unit: "條", category: "海鮮" },
      { name: "粗鹽", quantity: "1.5", unit: "茶匙", category: "調味料" },
      { name: "檸檬（切角）", quantity: "1/4", unit: "個", category: "其他" },
      { name: "食油", quantity: "1.5", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "馬友魚洗淨並徹底抹乾水分。用粗鹽均勻塗抹魚身內外，醃製至少20分鐘（醃透肉質會更結實香濃）。", duration: 20 },
      { instruction: "熱鑊下油，將魚件或全魚放入，中火慢煎至兩面呈誘人嘅金黃色，約需時8-10分鐘。", duration: 10 },
      { instruction: "上碟後擠上少許檸檬汁，更顯魚肉鮮美。", duration: 1 },
    ],
    tags: ["中菜", "港式", "經典", "煎", "海鮮", "魚", "香濃", "鹹香", "送酒", "簡單", "30 分鐘內"],
  },
  {
    name: "香煎肉餅",
    description: "比蒸肉餅多了一層焦脆嘅外皮，外酥內軟，啖啖肉汁，係小朋友最難抗拒嘅下飯神器。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "半肥瘦免治豬肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "麻油", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "水", quantity: "2", unit: "湯匙", category: "其他" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "豬肉加入生抽、糖、生粉、麻油，分次落水，順時針方向強力攪拌至有黏性。", duration: 8 },
      { instruction: "將肉泥分成數個小球，用手掌壓成圓餅狀。", duration: 3 },
      { instruction: "燒熱油，中小火放入肉餅，慢火煎3分鐘至一面金黃，翻面再煎3分鐘，至兩面香脆、熟透即可。", duration: 8 },
    ],
    tags: ["中菜", "港式", "家常菜", "煎", "香脆", "豬肉", "30 分鐘內", "小朋友", "簡單", "新手", "下飯"],
  },
  {
    name: "香煎蓮藕餅",
    description: "蓮藕切碎拌入肉餅中，慢火煎香。藕碎爽脆，肉餅香濃，口感豐富，百吃不厭。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "免治豬肉", quantity: "250", unit: "克", category: "肉類" },
      { name: "蓮藕", quantity: "150", unit: "克", category: "蔬菜" },
      { name: "蝦米", quantity: "10", unit: "克", category: "乾貨" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "蓮藕去皮切極細碎。蝦米浸軟切碎。豬肉加生抽、糖、生粉攪勻，加入蓮藕碎同蝦米碎用力拌勻。", duration: 12 },
      { instruction: "把肉泥分成圓餅狀。熱鑊下油，中小火下肉餅煎至兩面金黃熟透（約8-10分鐘）。", duration: 10 },
    ],
    tags: ["中菜", "港式", "家常菜", "煎", "豬肉", "蔬菜", "爽脆", "30 分鐘內", "簡單", "長者", "營養"],
  },
  {
    name: "煎釀蓮藕夾",
    description: "兩片蓮藕夾住鮮美肉餡，外層掛上薄粉煎炸至金黃。咬下去既有蓮藕嘅爽脆，又有肉香。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "蓮藕", quantity: "250", unit: "克", category: "蔬菜" },
      { name: "免治豬肉", quantity: "150", unit: "克", category: "肉類" },
      { name: "生粉", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "麵粉（炸漿）", quantity: "4", unit: "湯匙", category: "其他" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "免治豬肉用生抽、糖同少許生粉醃15分鐘。蓮藕去皮，切薄片（每兩片一組，中間不切斷形成夾子）。", duration: 15 },
      { instruction: "蓮藕內側抹上少許生粉，釀入適量肉餡，輕輕壓緊。", duration: 8 },
      { instruction: "麵粉與少許水調成薄炸漿，將蓮藕夾裹上一層薄漿。", duration: 3 },
      { instruction: "熱油中火煎炸蓮藕夾至兩面金黃香脆（約8分鐘），盛起瀝油即可。", duration: 8 },
    ],
    tags: ["中菜", "港式", "經典", "煎", "蔬菜", "豬肉", "香脆", "爽脆", "宴客", "進階"],
  },
  {
    name: "香煎生薯仔餅",
    description: "懷舊老香港家庭菜，薯仔切絲加上少許臘肉或肉碎煎至兩面焦黃，薯香撲鼻，酥脆無比。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "薯仔（土豆）", quantity: "2", unit: "個", category: "蔬菜" },
      { name: "免治豬肉或臘肉碎", quantity: "50", unit: "克", category: "肉類" },
      { name: "雞蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "生粉", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "胡椒粉", quantity: "少許", unit: "", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "薯仔去皮切成極細絲，用水洗掉表面澱粉，徹底瀝乾。", duration: 10 },
      { instruction: "薯絲加入肉碎、雞蛋、生粉、鹽同胡椒粉用力拌勻。", duration: 5 },
      { instruction: "熱鑊落油，將薯絲混合物倒入鑊中攤平，壓成大圓餅。", duration: 2 },
      { instruction: "中小火慢煎至兩面金黃香脆（每面約5分鐘），切塊即可享用。", duration: 10 },
    ],
    tags: ["中菜", "港式", "家常菜", "煎", "蔬菜", "豬肉", "香脆", "30 分鐘內", "簡單", "開胃", "新手"],
  },
  {
    name: "生煎肉餅",
    description: "傳統粵式生煎法，不經蒸煮，直接將新鮮肉餅落油鑊生煎，肉汁完全封鎖在內，脆口多汁。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "半肥瘦免治豬肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "老抽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "豬肉加入生抽、老抽、糖、生粉及2湯匙水，用力攪拌至肉泥黏稠。", duration: 5 },
      { instruction: "用手分出小肉團，拍打塑形，捏成圓餅。", duration: 3 },
      { instruction: "熱鑊下油，將肉餅平鋪，中小火煎至一面定型微黃（約3分鐘）。", duration: 3 },
      { instruction: "翻面，蓋上鑊蓋，利用內部蒸氣焗熟肉餅（約4分鐘），最後開蓋大火煎香兩面。", duration: 5 },
    ],
    tags: ["中菜", "港式", "家常菜", "煎", "豬肉", "香脆", "滑嫩", "30 分鐘內", "簡單", "下飯"],
  },
  {
    name: "香煎蛋餃",
    description: "用金黃蛋皮包裹鮮美肉餡捏成餃子狀，煎至焦香，口感柔軟，帶有濃厚蛋香。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞蛋", quantity: "4", unit: "隻", category: "其他" },
      { name: "免治豬肉", quantity: "150", unit: "克", category: "肉類" },
      { name: "蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "豬肉加蔥花、生抽、鹽、生粉醃15分鐘。雞蛋打散成均勻蛋液。", duration: 15 },
      { instruction: "大圓勺子或平底鍋抹薄油，燒熱。勺入一湯匙蛋液，迅速搖成圓形薄蛋皮。", duration: 3 },
      { instruction: "趁蛋液未乾，在半邊蛋皮放上適量肉餡，將另一半蛋皮翻過來蓋住，輕壓邊緣使之黏合呈餃子狀。", duration: 3 },
      { instruction: "將做好嘅蛋餃雙面略煎至金黃，最後可加少許水燜煮3分鐘至肉餡熟透。", duration: 5 },
    ],
    tags: ["中菜", "港式", "經典", "煎", "雞蛋", "豬肉", "香濃", "宴客", "進階", "一家大細"],
  },
  {
    name: "韭菜煎蛋角",
    description: "傳統順德家庭小菜，雞蛋拌入韭菜煎成金黃蛋角，外焦裡嫩，韭香撲鼻。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞蛋", quantity: "4", unit: "隻", category: "其他" },
      { name: "韭菜", quantity: "80", unit: "克", category: "蔬菜" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "胡椒粉", quantity: "少許", unit: "", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "韭菜洗淨徹底瀝乾，切成細碎。雞蛋打散。", duration: 8 },
      { instruction: "蛋液中加入韭菜碎、鹽同胡椒粉用力攪勻。", duration: 2 },
      { instruction: "燒熱鑊落油，用勺子分批倒入蛋液，中小火慢煎成數個半月形蛋角，兩面煎至微焦黃熟透即可。", duration: 10 },
    ],
    tags: ["中菜", "港式", "家常菜", "煎", "雞蛋", "蔬菜", "香濃", "30 分鐘內", "簡單", "新手", "快手"],
  },
  {
    name: "椒鹽豬扒",
    description: "大牌檔惹味之最！豬扒經醃製油炸，撒上香辣嘅椒鹽與避風塘蒜酥，酥脆爽口。",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "帶骨或無骨豬扒", quantity: "350", unit: "克", category: "肉類" },
      { name: "蒜蓉", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "紅椒粒/蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "椒鹽粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油（炸油）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "豬扒洗淨用刀背拍鬆，切大塊，用生抽、糖、酒同少許生粉醃15分鐘。蒜頭剁碎，用小火炸成焦黃金蒜酥。", duration: 15 },
      { instruction: "醃好嘅豬扒均勻沾上一層薄生粉。大火燒熱油鑊，將豬扒放入中火炸至金黃熟透（約5分鐘），撈起瀝乾油分。", duration: 5 },
      { instruction: "鑊留底油，爆香少許新鮮蒜蓉、紅椒粒同蔥花，倒入豬扒，撒入椒鹽粉同金蒜酥，快速大火翻炒均勻即可。", duration: 3 },
    ],
    tags: ["中菜", "港式", "經典", "大牌檔", "炸", "豬肉", "香辣", "惹味", "避風塘", "送酒", "進階"],
  },
  {
    name: "椒鹽九吐魚",
    description: "九吐魚肉質滑嫩如豆腐，裹上脆皮炸漿炸透，撒上椒鹽，外脆內化，極品惹味下酒菜。",
    cookTime: 25,
    servings: 3,
    difficulty: "困難",
    recipeCategory: "中菜",
    ingredients: [
      { name: "九吐魚（龍頭魚）", quantity: "400", unit: "克", category: "海鮮" },
      { name: "脆炸粉", quantity: "5", unit: "湯匙", category: "其他" },
      { name: "椒鹽粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "紅椒粒/蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "胡椒粉", quantity: "少許", unit: "", category: "調味料" },
      { name: "食油（炸油）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "九吐魚去頭去內臟清洗，切段。用鹽同胡椒粉醃10分鐘，用廚房紙徹底印乾水分（極其關鍵，九吐魚水分極多）。", duration: 15 },
      { instruction: "脆炸粉加少許水同1茶匙油調成濃稠脆漿，將魚肉裹滿脆漿。", duration: 3 },
      { instruction: "熱油燒至高溫，逐件落九吐魚，大火炸至表面金黃硬身（約3-4分鐘），撈起瀝油（動作要輕防魚肉碎裂）。", duration: 5 },
      { instruction: "鑊留少許油爆香紅椒粒、蔥花，倒回九吐魚，撒上椒鹽粉快速顛鑊拌勻即可。", duration: 2 },
    ],
    tags: ["中菜", "港式", "大牌檔", "炸", "海鮮", "魚", "滑嫩", "香辣", "送酒", "廚神挑戰"],
  },
  {
    name: "椒鹽鮮魷",
    description: "鑊氣四溢嘅椒鹽魷魚，表皮酥脆，魷魚爽口彈牙，鹹辣適中，避風塘代表作。",
    cookTime: 20,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮鮮魷（魷魚）", quantity: "300", unit: "克", category: "海鮮" },
      { name: "生粉", quantity: "4", unit: "湯匙", category: "調味料" },
      { name: "椒鹽粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "紅辣椒粒/蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "食油（炸油）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "鮮魷去內臟剝皮清洗，切圈或劃十字花刀切塊，飛水5秒鐘，撈出立刻用冰水過涼，再徹底抹乾水分。", duration: 10 },
      { instruction: "鮮魷均勻裹上一層厚厚嘅生粉。熱油高溫下鍋炸至金黃硬身（約1-2分鐘），迅速撈起瀝油。", duration: 3 },
      { instruction: "鑊留底油，煸香紅椒粒同蔥花，倒入炸好嘅魷魚，撒椒鹽粉，大火快速翻炒幾秒即成。", duration: 2 },
    ],
    tags: ["中菜", "港式", "經典", "大牌檔", "炸", "海鮮", "魷魚", "彈牙", "香辣", "送酒", "進階"],
  },
  {
    name: "椒鹽豆腐",
    description: "外層金黃香口，內裡豆腐依然保持軟嫩，撒上椒鹽粉，簡單食材蒸發出極限滋味。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "板豆腐或豆腐乾", quantity: "2", unit: "盒", category: "豆腐" },
      { name: "生粉", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "椒鹽粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "蒜茸/蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "食油", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "豆腐切成一口大小嘅方塊，用廚房紙稍微吸乾表面水分。均勻沾上一層薄生粉。", duration: 10 },
      { instruction: "大火燒熱半鑊油，中火將豆腐煎炸至六面金黃、硬身（約5-6分鐘），盛起瀝油。", duration: 6 },
      { instruction: "留底油炒香蒜茸同蔥花，倒入豆腐，均勻撒上椒鹽粉快速拌勻即可。", duration: 2 },
    ],
    tags: ["中菜", "港式", "大牌檔", "煎", "豆腐", "香辣", "素食", "簡單", "30 分鐘內", "快手", "開胃"],
  },
  {
    name: "脆皮炸大腸",
    description: "傳統懷舊港式大牌檔大菜，大腸經過多重清洗滷煮，串起炸至外皮極其焦脆，點甜醬極具滋味。",
    cookTime: 60,
    servings: 4,
    difficulty: "困難",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮豬大腸", quantity: "500", unit: "克", category: "肉類" },
      { name: "滷水汁", quantity: "2", unit: "杯", category: "調味料" },
      { name: "生粉（清洗用）", quantity: "4", unit: "湯匙", category: "其他" },
      { name: "白醋", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "麥芽糖水", quantity: "適量", unit: "", category: "調味料" },
      { name: "食油（炸油）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "大腸內外用生粉、白醋反覆搓洗去異味，洗淨。放進滾水中飛水5分鐘。", duration: 20 },
      { instruction: "將大腸放入滷水汁中慢火滷煮45分鐘至輭身，撈起晾乾。用筷子或鐵籤穿起大腸，表面塗上一層麥芽糖水風乾。", duration: 15 },
      { instruction: "燒熱大量油，大火將大腸炸至外皮紅潤、極其焦脆（約5分鐘），盛起切片即可。", duration: 8 },
    ],
    tags: ["中菜", "港式", "經典", "大牌檔", "炸", "豬肉", "香脆", "特色", "送酒", "廚神挑戰"],
  },
  {
    name: "生炸雞翼",
    description: "茶餐廳下午茶必點！雞翼不經煮熟，生身醃製直接下鑊生炸，外皮酥脆無比，入肉爆汁。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞翼", quantity: "8", unit: "隻", category: "肉類" },
      { name: "生抽", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "五香粉", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "食油（炸油）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "雞翼洗淨吸乾。用生抽、五香粉、糖、生粉及1茶匙油醃製至少2小時或過夜。", duration: 10 },
      { instruction: "熱油燒至160度，下雞翼中小火生炸，慢火炸8分鐘至熟透，撈起瀝油。", duration: 8 },
      { instruction: "大火將油溫燒至高溫，將雞翼重炸30秒（逼出油分且表皮極其酥脆），撈起盛盤。", duration: 2 },
    ],
    tags: ["中菜", "港式", "茶餐廳", "炸", "雞肉", "香脆", "多汁", "簡單", "下午茶", "小朋友"],
  },
  {
    name: "南乳炸雞翼",
    description: "融入濃郁玫瑰腐乳（南乳）香氣，炸出嘅雞翼呈現絕美絳紅色，酥脆中帶有獨特鹹甜風味。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞翼", quantity: "8", unit: "隻", category: "肉類" },
      { name: "紅南乳", quantity: "1", unit: "塊", category: "調味料" },
      { name: "南乳汁", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "食油（炸油）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "南乳壓碎，與南乳汁、糖、紹興酒調勻。雞翼洗淨抹乾，加入調味醃製1小時。", duration: 10 },
      { instruction: "加入生粉拌勻，使每隻雞翼表面掛上薄薄糊狀。", duration: 2 },
      { instruction: "中火落鑊慢炸7-8分鐘至熟。大火高溫重炸15秒至表面酥脆紅潤即可。", duration: 10 },
    ],
    tags: ["中菜", "港式", "家常菜", "炸", "雞肉", "鹹香", "特色", "簡單", "30 分鐘內", "小朋友"],
  },
  {
    name: "吉列豬扒",
    description: "港式茶餐廳神級焗飯搭檔，厚切豬扒裹上麵包糠炸至鬆脆外皮，肉質嫩滑多汁。",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "厚切無骨豬扒", quantity: "3", unit: "塊", category: "肉類" },
      { name: "雞蛋（打散）", quantity: "1", unit: "隻", category: "其他" },
      { name: "麵粉", quantity: "3", unit: "湯匙", category: "其他" },
      { name: "日式麵包糠", quantity: "1", unit: "杯", category: "其他" },
      { name: "鹽/黑胡椒", quantity: "少許", unit: "", category: "調味料" },
      { name: "食油（炸油）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "豬扒洗淨，用肉槌或刀背拍鬆，邊緣切幾刀防收縮。撒鹽、黑胡椒醃15分鐘。", duration: 10 },
      { instruction: "豬扒依次序裹上：薄麵粉、蛋液、厚麵包糠，用手壓緊（防脫糠）。", duration: 5 },
      { instruction: "熱油中小火放入豬扒，炸4-5分鐘至兩面金黃。撈出稍放涼，切塊享用。", duration: 6 },
    ],
    tags: ["中菜", "港式", "茶餐廳", "炸", "豬肉", "香脆", "經典", "30 分鐘內", "小朋友", "進階"],
  },
  {
    name: "咕嚕肉",
    description: "享譽國際嘅港式經典！肥美五花肉炸至外酥裡嫩，裹上濃郁酸甜嘅糖醋汁，酸爽開胃。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "豬五花肉或梅頭肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "青椒/紅椒/洋蔥", quantity: "各1/2", unit: "個", category: "蔬菜" },
      { name: "罐頭菠蘿塊", quantity: "4", unit: "片", category: "蔬菜" },
      { name: "雞蛋黃", quantity: "1", unit: "隻", category: "其他" },
      { name: "生粉", quantity: "適量", unit: "", category: "調味料" },
      { name: "茄汁", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "白醋", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "豬肉切塊，用少許生抽、蛋黃醃15分鐘。青紅椒、洋蔥切塊。", duration: 15 },
      { instruction: "醃好嘅肉塊厚厚裹上一層生粉。熱油高溫，中大火將肉炸至表面金黃硬身（約4分鐘），撈起。大火高溫重炸15秒至極其酥脆。", duration: 5 },
      { instruction: "調甜酸汁：茄汁、醋、糖、2湯匙水拌勻。鑊落少許油爆香青紅椒洋蔥，倒入甜酸汁煮至滾。", duration: 3 },
      { instruction: "倒入炸肉同菠蘿塊，大火快速翻炒幾下，使醬汁均勻裹滿肉塊表面即可出碟。", duration: 2 },
    ],
    tags: ["中菜", "港式", "經典", "炸", "豬肉", "菠蘿", "酸甜", "開胃", "宴客", "進階", "下飯"],
  },
];
