export const HK_BRAISED_RECIPES = [
  {
    name: "柱侯蘿蔔牛腩煲",
    description: "茶餐廳同大牌檔經典！柱侯醬與多種香料慢火燜煮牛腩，配上吸滿肉汁嘅清甜白蘿蔔，濃郁無比。",
    cookTime: 120,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "牛腩", quantity: "600", unit: "克", category: "肉類" },
      { name: "白蘿蔔", quantity: "400", unit: "克", category: "蔬菜" },
      { name: "柱侯醬", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "薑片/蒜頭", quantity: "適量", unit: "", category: "調味料" },
      { name: "八角/桂皮", quantity: "少許", unit: "", category: "調味料" },
      { name: "冰糖", quantity: "20", unit: "克", category: "調味料" },
      { name: "生抽/老抽", quantity: "各1", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "牛腩切大塊，飛水5分鐘去血水，撈起洗淨。蘿蔔去皮切大滾刀塊。", duration: 15 },
      { instruction: "熱鑊下油，爆香薑片、蒜頭，下柱侯醬小火炒香，倒入牛腩大火翻炒均勻。", duration: 5 },
      { instruction: "灒紹興酒，加入八角、桂皮、冰糖、生抽、老抽同沒過牛腩嘅熱水，大火燒開轉小火慢火炆90分鐘。", duration: 90 },
      { instruction: "放入白蘿蔔塊，繼續小火炆30分鐘至蘿蔔軟爛入味，大火收稠醬汁即可裝煲。", duration: 30 },
    ],
    tags: ["港式", "經典", "炆", "香濃", "慢煮", "60 分鐘以上", "中等"],
  },
  {
    name: "清湯蘿蔔牛腩",
    description: "源自中環名牌大牌檔，不加重色醬油，僅用牛骨、香料同蘿蔔熬出清甜鮮美嘅湯底，襯托牛腩清香。",
    cookTime: 120,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "牛坑腩或牛爽腩", quantity: "600", unit: "克", category: "肉類" },
      { name: "白蘿蔔", quantity: "400", unit: "克", category: "蔬菜" },
      { name: "八角", quantity: "2", unit: "粒", category: "調味料" },
      { name: "花椒/陳皮", quantity: "少許", unit: "", category: "調味料" },
      { name: "薑片", quantity: "4", unit: "片", category: "調味料" },
      { name: "鹽", quantity: "2", unit: "茶匙", category: "調味料" },
      { name: "白胡椒粒（拍碎）", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "牛腩飛水洗淨。蘿蔔去皮切厚塊。", duration: 10 },
      { instruction: "大煲加入大量水，放入牛腩、薑片、八角、花椒、陳皮、白胡椒粒，大火燒開，撇去浮沫。", duration: 10 },
      { instruction: "轉小火蓋蓋燉煮90分鐘至牛腩軟輭。", duration: 90 },
      { instruction: "下蘿蔔塊同鹽，繼續慢火煮30分鐘。將牛腩撈出切厚片，與蘿蔔一齊盛入大碗，倒入過濾後嘅鮮牛湯即可。", duration: 30 },
    ],
    tags: ["港式", "經典", "炆", "清淡", "鮮味", "慢煮", "60 分鐘以上", "中等"],
  },
  {
    name: "港式咖喱牛腩煲",
    description: "融合南洋與英式咖喱風味，加入椰奶、花奶和黃薑調配，微辣椰香，牛腩酥軟，配烤餅或飯絕配。",
    cookTime: 120,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "牛腩", quantity: "500", unit: "克", category: "肉類" },
      { name: "薯仔", quantity: "2", unit: "個", category: "蔬菜" },
      { name: "洋蔥", quantity: "1", unit: "個", category: "蔬菜" },
      { name: "港式咖喱膏/粉", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "椰奶", quantity: "100", unit: "毫升", category: "其他" },
      { name: "淡奶（花奶）", quantity: "2", unit: "湯匙", category: "其他" },
      { name: "薑/蒜/冰糖", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "牛腩切塊飛水。薯仔去皮切塊炸至表面金黃（防止煮爛）。洋蔥切塊。", duration: 15 },
      { instruction: "爆香洋蔥、薑蒜，下咖喱膏慢火炒香，倒入牛腩大火翻炒上色。", duration: 5 },
      { instruction: "加入足量熱水同少許冰糖，大火燒開轉小火慢炆90分鐘。", duration: 90 },
      { instruction: "加入薯仔一齊炆20分鐘。最後倒入椰奶同淡奶攪勻，大火收汁裝煲。", duration: 20 },
    ],
    tags: ["港式", "經典", "炆", "香濃", "慢煮", "60 分鐘以上", "中等"],
  },
  {
    name: "港式咖喱雞煲",
    description: "濃郁椰香咖喱與嫩滑雞髀肉嘅完美組合，薯仔吸滿咖喱汁，微辣開胃，老少皆宜。",
    cookTime: 35,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞脾肉件", quantity: "400", unit: "克", category: "肉類" },
      { name: "薯仔", quantity: "1.5", unit: "個", category: "蔬菜" },
      { name: "洋蔥", quantity: "1/2", unit: "個", category: "蔬菜" },
      { name: "咖喱醬", quantity: "2.5", unit: "湯匙", category: "調味料" },
      { name: "椰奶", quantity: "80", unit: "毫升", category: "其他" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "雞件用生抽醃15分鐘。薯仔切塊，洋蔥切絲。", duration: 15 },
      { instruction: "薯仔塊落鍋煎炒至表面微黃定型，盛起。", duration: 5 },
      { instruction: "爆香洋蔥，下咖喱醬炒香，倒入雞件大火炒至變色。", duration: 3 },
      { instruction: "倒入薯仔與適量水，蓋蓋中火煮15分鐘至熟透，最後倒入椰奶炒勻收汁。", duration: 15 },
    ],
    tags: ["港式", "家常菜", "炆", "香濃", "簡單", "30 分鐘以上"],
  },
  {
    name: "啫啫滑雞煲",
    description: "大牌檔名餸！瓦煲燒至極高溫，生雞件、乾蔥同薑蒜在煲中高溫「啫啫」爆響，酒香四溢，鑊氣沖天。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮走地雞或雞髀肉", quantity: "500", unit: "克", category: "肉類" },
      { name: "乾蔥頭（紅蔥頭）", quantity: "8", unit: "粒", category: "蔬菜" },
      { name: "蒜頭/薑片", quantity: "大量", unit: "", category: "調味料" },
      { name: "柱侯醬/海鮮醬", quantity: "各1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "紹興酒", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "雞切件洗淨徹底抹乾，用柱侯醬、海鮮醬、糖、生粉醃20分鐘。", duration: 20 },
      { instruction: "瓦煲燒熱落油，爆香乾蔥頭、薑片、蒜頭至呈焦黃色。", duration: 5 },
      { instruction: "將醃好嘅雞件平鋪入煲中，蓋蓋，大火「啫」5分鐘。翻動雞件，再蓋蓋大火「啫」5分鐘至熟透。", duration: 10 },
      { instruction: "沿着煲蓋邊淋入2湯匙紹興酒（激發強烈酒香），開蓋撒上蔥段即可上桌。", duration: 2 },
    ],
    tags: ["港式", "經典", "大牌檔", "香濃", "送酒", "中等"],
  },
  {
    name: "三杯雞",
    description: "台式經典在港演變。一杯麻油、一杯生抽、一杯米酒，配上香氣濃郁嘅九層塔，汁濃肉滑。",
    cookTime: 30,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞髀肉件", quantity: "450", unit: "克", category: "肉類" },
      { name: "黑麻油", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "生抽/老抽", quantity: "各1.5", unit: "湯匙", category: "調味料" },
      { name: "米酒或紹興酒", quantity: "3", unit: "湯匙", category: "調味料" },
      { name: "九層塔（羅勒）", quantity: "1", unit: "大束", category: "蔬菜" },
      { name: "冰糖", quantity: "15", unit: "克", category: "調味料" },
      { name: "薑片/蒜頭", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "雞件用生粉生抽略醃。熱鍋落黑麻油，煸香大量薑片同拍扁蒜頭至微焦。", duration: 8 },
      { instruction: "下雞件大火煎炒至表面金黃。加入生抽、老抽、米酒同冰糖，大火燒開轉中火蓋蓋煮15分鐘。", duration: 15 },
      { instruction: "開蓋大火收汁至濃稠焦糖色，關火前下大把九層塔葉，蓋蓋焗10秒即可起鍋。", duration: 2 },
    ],
    tags: ["港式", "經典", "炆", "香草", "香濃", "鹹香", "下飯", "簡單", "30 分鐘內"],
  },
  {
    name: "栗子炆雞",
    description: "秋天必食溫補菜！粉糯香甜嘅新鮮栗子與嫩滑雞髀肉慢火同炆，湯汁微甜黏稠，滋補養生。",
    cookTime: 40,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞肉件", quantity: "400", unit: "克", category: "肉類" },
      { name: "去殼新鮮栗子", quantity: "150", unit: "克", category: "蔬菜" },
      { name: "蠔油", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "薑/蒜/生粉", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "栗子浸熱水去內皮。雞件用生抽生粉醃15分鐘。", duration: 15 },
      { instruction: "爆香薑蒜，下雞件大火炒至表面金黃。下栗子同蠔油、糖翻炒。", duration: 5 },
      { instruction: "加入熱水沒過一半食材，蓋上蓋中火炆20-25分鐘，至栗子粉糯、雞肉熟透，最後大火收汁。", duration: 25 },
    ],
    tags: ["港式", "家常菜", "炆", "清甜", "滋補", "簡單", "30 分鐘以上"],
  },
  {
    name: "鮑汁冬菇炆花膠",
    description: "傳統高檔粵式大菜！高規格花菇與骨膠原滿滿嘅花膠，以香濃鮑汁慢火細炆，湯汁黏口，極致矜貴。",
    cookTime: 90,
    servings: 4,
    difficulty: "困難",
    recipeCategory: "中菜",
    ingredients: [
      { name: "已發泡花膠", quantity: "4", unit: "隻", category: "海鮮" },
      { name: "優質花菇/冬菇", quantity: "8", unit: "朵", category: "乾貨" },
      { name: "高檔鮑汁", quantity: "4", unit: "湯匙", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "冰糖", quantity: "10", unit: "克", category: "調味料" },
      { name: "高湯或雞湯", quantity: "500", unit: "毫升", category: "其他" },
      { name: "薑片/蔥段", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "花菇浸泡軟化去蒂。花膠切大件。花膠、花菇先放進有薑蔥酒嘅水中飛水去腥。", duration: 15 },
      { instruction: "熱鑊下油爆香薑蔥，倒入雞湯、鮑汁、生抽同少許冰糖，放入花菇小火先炆煮40分鐘。", duration: 40 },
      { instruction: "放入花膠件，繼續蓋蓋小火慢炆30分鐘（花膠不宜過早放，易融化流失），至花膠輭糯入味。", duration: 30 },
      { instruction: "大火收汁至濃稠，呈天然黏口膠質即可大方上碟。", duration: 5 },
    ],
    tags: ["港式", "經典", "炆", "香濃", "滋補", "宴客"],
  },
  {
    name: "北菇炆海參",
    description: "海參口感Q彈富膠質，北菇香氣醇厚，蠔油鮑汁慢燉，滋補養生，傳統婚宴壓軸名餸。",
    cookTime: 60,
    servings: 4,
    difficulty: "困難",
    recipeCategory: "中菜",
    ingredients: [
      { name: "已發發泡刺參或海參", quantity: "2", unit: "條", category: "海鮮" },
      { name: "北菇/冬菇", quantity: "6", unit: "朵", category: "乾貨" },
      { name: "蠔油", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "老抽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "冰糖", quantity: "10", unit: "克", category: "調味料" },
      { name: "雞湯", quantity: "300", unit: "毫升", category: "其他" },
      { name: "薑片/蔥段", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "海參洗淨切厚斜段，花菇浸軟。海參放薑蔥水飛水3分鐘撈起。", duration: 15 },
      { instruction: "爆香薑蔥，下花菇、雞湯、蠔油、老抽、冰糖煮滾，小火先炆20分鐘。", duration: 20 },
      { instruction: "下海參段，繼續小火慢炆20分鐘至海參入味吸汁，最後大火收汁至濃稠即可。", duration: 20 },
    ],
    tags: ["港式", "經典", "炆", "海鮮", "滋補", "宴客"],
  },
  {
    name: "紅燒豆腐煲",
    description: "經典港式煲仔菜！豆腐油炸至金黃，與香菇、肉片、筍片慢火炆煮至滾燙，豆香肉香四溢。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "板豆腐", quantity: "2", unit: "磚", category: "豆腐" },
      { name: "豬肉片", quantity: "80", unit: "克", category: "肉類" },
      { name: "冬菇/筍片/胡蘿蔔片", quantity: "少許", unit: "", category: "蔬菜" },
      { name: "蠔油", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "生粉水", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "豆腐切厚塊，用油炸至六面金黃硬身（紅燒豆腐），盛起。肉片用少許生粉生抽略醃。", duration: 15 },
      { instruction: "爆香薑蒜、肉片同冬菇，下高湯、蠔油、生抽同豆腐塊，大火燒開轉小火炆10分鐘至入味。", duration: 10 },
      { instruction: "倒入生粉水勾芡，盛入燒熱嘅瓦煲中，蓋蓋上桌。", duration: 3 },
    ],
    tags: ["港式", "家常菜", "炆", "香濃", "簡單", "30 分鐘內"],
  },
  {
    name: "琵琶豆腐",
    description: "豆腐混合魚肉、蝦米，塑造成琵琶狀（湯匙狀）煎至金黃，再淋上香濃鮑汁，外層焦香，內裡細嫩。",
    cookTime: 35,
    servings: 3,
    difficulty: "困難",
    recipeCategory: "中菜",
    ingredients: [
      { name: "板豆腐", quantity: "1.5", unit: "磚", category: "豆腐" },
      { name: "鯪魚肉或免治蝦肉", quantity: "100", unit: "克", category: "海鮮" },
      { name: "雞蛋液", quantity: "1/2", unit: "隻", category: "其他" },
      { name: "香菜碎/蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "鮑汁/蠔油", quantity: "各1", unit: "湯匙", category: "調味料" },
      { name: "鹽/生粉", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "豆腐用紗布包住壓乾水分，壓爛成泥。加入魚肉、蛋液、香菜、鹽同生粉用力攪勻。", duration: 15 },
      { instruction: "用中式湯匙抹油，填入豆腐泥抹平塑形（琵琶狀），大火蒸5分鐘定型後取出。", duration: 10 },
      { instruction: "熱鑊下油，將蒸好嘅豆腐塊滑入鑊中，中小火煎至兩面金黃。撈出排好在碟上。", duration: 8 },
      { instruction: "用鮑汁、蠔油加少許水煮滾勾芡，均勻澆在豆腐上即可。", duration: 2 },
    ],
    tags: ["港式", "經典", "煎", "海鮮", "宴客", "特色"],
  },
  {
    name: "鹹魚雞粒豆腐煲",
    description: "鹹魚（梅香馬友）嘅濃烈鹹香，與鮮嫩雞粒、滑豆腐慢火滾煲。鹹魚融化在汁中，極致落飯！",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "板豆腐或嫩豆腐（切方塊）", quantity: "2", unit: "盒", category: "豆腐" },
      { name: "梅香鹹魚（去骨切極細粒）", quantity: "20", unit: "克", category: "海鮮" },
      { name: "雞胸肉粒", quantity: "100", unit: "克", category: "肉類" },
      { name: "薑末/蒜茸/蔥花", quantity: "適量", unit: "", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉水", quantity: "1", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "豆腐切小塊飛水備用。雞粒用少許生粉生抽醃製。", duration: 10 },
      { instruction: "熱油小火下鹹魚粒煎炒至完全焦黃、溶化散發出濃烈鹹魚香。", duration: 3 },
      { instruction: "下薑蒜茸、雞粒爆炒，加入豆腐塊、雞湯（或水）、生抽同糖，大火燒開小火炆8分鐘。", duration: 10 },
      { instruction: "落生粉水勾芡，倒入燒熱嘅瓦煲中，撒大量蔥花即可。", duration: 2 },
    ],
    tags: ["港式", "經典", "鹹香", "下飯", "中等", "30 分鐘內"],
  },
  {
    name: "海鮮豆腐煲",
    description: "鮮蝦仁、帶子與魷魚片配上滑豆腐一齊慢火滾熱，湯汁充滿海鮮嘅清甜，清淡鮮美。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "嫩豆腐（切塊）", quantity: "2", unit: "盒", category: "豆腐" },
      { name: "鮮蝦仁", quantity: "80", unit: "克", category: "海鮮" },
      { name: "鮮魷魚片", quantity: "80", unit: "克", category: "海鮮" },
      { name: "鮮帶子", quantity: "4", unit: "隻", category: "海鮮" },
      { name: "蠔油", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "鹽/生粉水", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "海鮮洗淨醃過。豆腐切塊。瓦煲加水或雞湯煮滾，放入豆腐。", duration: 12 },
      { instruction: "大火加入海鮮滾2分鐘至熟，加入蠔油和少許鹽調味。", duration: 3 },
      { instruction: "生粉水勾薄芡，使海鮮與豆腐黏合在一起，淋熟油上桌。", duration: 5 },
    ],
    tags: ["港式", "家常菜", "海鮮", "鮮味", "清淡", "簡單"],
  },
  {
    name: "溫公南乳齋煲",
    description: "傳統初一十五齋菜！南乳、腐乳為底，慢火炆煮粉絲、腐竹、雲耳、冬菇等十幾種素料，鹹香入味。",
    cookTime: 35,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "炸腐竹/大白菜/冬菇", quantity: "各100", unit: "克", category: "蔬菜" },
      { name: "粉絲", quantity: "1", unit: "包", category: "乾貨" },
      { name: "雲耳/木耳", quantity: "適量", unit: "", category: "乾貨" },
      { name: "紅南乳/白腐乳", quantity: "各1", unit: "塊", category: "調味料" },
      { name: "糖", quantity: "1.5", unit: "茶匙", category: "調味料" },
      { name: "薑片", quantity: "3", unit: "片", category: "調味料" },
    ],
    steps: [
      { instruction: "粉絲冬菇雲耳浸軟。白菜切大段。南乳腐乳壓碎調勻。", duration: 15 },
      { instruction: "爆香薑片，下南乳醬炒香，下大白菜、冬菇、雲耳、腐竹大火翻炒勻。", duration: 5 },
      { instruction: "加水沒過食材，加糖，蓋冚中火炆15分鐘至白菜軟輭。最後下粉絲煮2分鐘吸乾汁水即可。", duration: 15 },
    ],
    tags: ["港式", "經典", "素食", "蔬菜", "健康", "中等"],
  },
  {
    name: "雙冬支竹羊腩煲",
    description: "香港冬天終極禦寒大菜！冬菇、冬筍（雙冬）同炸支竹，與新鮮羊腩、南乳、柱侯醬慢火熱滾，暖身一流。",
    cookTime: 120,
    servings: 4,
    difficulty: "困難",
    recipeCategory: "中菜",
    ingredients: [
      { name: "帶皮羊腩", quantity: "800", unit: "克", category: "肉類" },
      { name: "炸支竹", quantity: "100", unit: "克", category: "乾貨" },
      { name: "冬菇/冬筍", quantity: "各80", unit: "克", category: "蔬菜" },
      { name: "紅南乳/柱侯醬", quantity: "各2", unit: "湯匙", category: "調味料" },
      { name: "陳皮/馬蹄/竹蔗", quantity: "適量", unit: "", category: "其他" },
      { name: "冰糖", quantity: "20", unit: "克", category: "調味料" },
    ],
    steps: [
      { instruction: "羊腩切大塊，放進有大量薑蔥酒嘅水中飛水10分鐘，撈起洗淨瀝乾。", duration: 20 },
      { instruction: "熱油鑊下羊腩，大火乾炒至羊皮緊縮、油脂逼出，盛起。爆香南乳同柱侯醬，倒入羊腩炒勻。", duration: 10 },
      { instruction: "加入熱水、馬蹄、竹蔗（清熱去羶）、陳皮、冬菇、冬筍、冰糖，大火燒開轉小火慢炆90分鐘。", duration: 90 },
      { instruction: "最後20分鐘加入浸軟嘅支竹一齊炆。出鍋可佐以生菜，蘸腐乳醬食用。", duration: 20 },
    ],
    tags: ["港式", "經典", "滋補", "慢煮", "60 分鐘以上"],
  },
  {
    name: "支竹炆豬腩肉",
    description: "炸支竹吸收咗五花腩極致香濃嘅肉汁，支竹軟滑爆汁，豬腩肉肥而不膩，家常下飯經典。",
    cookTime: 45,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "五花豬腩肉", quantity: "400", unit: "克", category: "肉類" },
      { name: "炸支竹", quantity: "80", unit: "克", category: "乾貨" },
      { name: "生抽/老抽/蠔油", quantity: "各1", unit: "湯匙", category: "調味料" },
      { name: "冰糖", quantity: "15", unit: "克", category: "調味料" },
      { name: "薑片/蒜頭", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "豬腩肉切塊飛水。支竹浸軟切段。", duration: 10 },
      { instruction: "爆香薑蒜，下五花肉塊慢火煎出多餘油脂，至表面金黃。加入生抽、老抽、蠔油、冰糖炒勻。", duration: 10 },
      { instruction: "加水沒過食材，中火炆20分鐘。加入支竹段，繼續炆15分鐘至肉軟、支竹入味，大火收乾汁水。", duration: 25 },
    ],
    tags: ["港式", "家常菜", "炆", "香濃", "簡單", "30 分鐘以上", "下飯"],
  },
  {
    name: "芋頭扣肉",
    description: "芋頭切厚片與五花腩相間排列，隔水蒸透。芋頭粉糯吸油，肉質軟爛入口即化，帶有強烈南乳香。",
    cookTime: 120,
    servings: 4,
    difficulty: "困難",
    recipeCategory: "中菜",
    ingredients: [
      { name: "五花肉（整塊）", quantity: "500", unit: "克", category: "肉類" },
      { name: "荔浦芋頭", quantity: "300", unit: "克", category: "蔬菜" },
      { name: "紅南乳", quantity: "2", unit: "塊", category: "調味料" },
      { name: "五香粉/糖", quantity: "各1", unit: "茶匙", category: "調味料" },
      { name: "生抽/老抽", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "五花肉水煮30分鐘熟透，抹乾，皮刺小孔塗老抽。下熱油鑊炸至皮金黃起泡，撈起立刻泡冷水，切厚片。芋頭去皮切同等厚片，用油略煎表面定型。", duration: 40 },
      { instruction: "南乳壓碎與生抽、五香粉、糖、老抽混合，塗抹在肉片和芋頭片上。", duration: 10 },
      { instruction: "大碗中，一片肉（皮朝下）夾一片芋頭，整齊排列好，鋪上多餘醬汁。大火隔水蒸90分鐘至極其軟爛。", duration: 90 },
      { instruction: "蒸好後，倒出肉汁，將碗倒扣在深碟中，肉汁加生粉水煮濃稠淋在表面即可。", duration: 10 },
    ],
    tags: ["港式", "經典", "蒸", "香濃", "慢煮", "60 分鐘以上"],
  },
  {
    name: "欖菜肉碎四季豆",
    description: "潮州橄欖菜嘅獨特鹹香、豬肉碎嘅甘香，與爆炒至乾身爽脆嘅四季豆結合，超級開胃下飯菜。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "四季豆", quantity: "300", unit: "克", category: "蔬菜" },
      { name: "免治豬肉", quantity: "100", unit: "克", category: "肉類" },
      { name: "潮州橄欖菜", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "蒜茸/生抽/糖", quantity: "適量", unit: "", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "四季豆撕去老筋，切小丁。肉碎用少許生抽醃。蒜頭切茸。", duration: 10 },
      { instruction: "熱鑊下油，下四季豆丁中火翻炒至表面微起皺（煸乾水分），盛起。", duration: 5 },
      { instruction: "爆香蒜茸同肉碎，炒至變色。下橄欖菜炒香，倒回四季豆丁。", duration: 3 },
      { instruction: "落少許糖同生抽，大火爆炒均勻1分鐘即可。", duration: 2 },
    ],
    tags: ["港式", "家常菜", "炒", "蔬菜", "鹹香", "簡單", "30 分鐘內"],
  },
  {
    name: "魚香茄子煲",
    description: "香濃梅香鹹魚與茄子、肉碎同炆，茄子軟糯吸飽鹹魚香味，在滾燙嘅瓦煲中滋滋作響，經典大牌檔風。",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "茄子", quantity: "2", unit: "條", category: "蔬菜" },
      { name: "免治豬肉", quantity: "100", unit: "克", category: "肉類" },
      { name: "梅香鹹魚粒", quantity: "15", unit: "克", category: "海鮮" },
      { name: "豆瓣醬", quantity: "1/2", unit: "湯匙", category: "調味料" },
      { name: "生抽/糖/生粉水", quantity: "適量", unit: "", category: "調味料" },
      { name: "薑末/蒜茸/蔥花", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "茄子切條，用鹽醃10分鐘洗淨。用油略煎茄子至軟定型。肉碎醃好。", duration: 12 },
      { instruction: "小火下鹹魚粒煎香散發強烈香氣，下薑蒜茸同肉碎、豆瓣醬爆炒均勻。", duration: 3 },
      { instruction: "倒入茄子、少許水、生抽、糖，大火燒開轉小火慢炆8分鐘至茄子軟爛。", duration: 8 },
      { instruction: "倒入生粉水勾芡，盛入燒紅嘅瓦煲中，灑蔥花即可。", duration: 2 },
    ],
    tags: ["港式", "經典", "蔬菜", "中等", "30 分鐘內"],
  },
  {
    name: "鮑汁海參花菇大鴨",
    description: "逢年過節壓軸大菜！整隻大鴨經炸後慢火油炆，配上海參同頂級花菇，湯汁鮑香濃口，盡顯豪氣。",
    cookTime: 150,
    servings: 6,
    difficulty: "困難",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮大整鴨", quantity: "1", unit: "隻", category: "肉類" },
      { name: "已發海參", quantity: "2", unit: "條", category: "海鮮" },
      { name: "優質花菇", quantity: "6", unit: "朵", category: "乾貨" },
      { name: "鮑汁/蠔油", quantity: "各3", unit: "湯匙", category: "調味料" },
      { name: "老抽/五香粉", quantity: "適量", unit: "", category: "調味料" },
      { name: "冰糖", quantity: "30", unit: "克", category: "調味料" },
      { name: "食油（炸鴨用）", quantity: "大量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "大鴨洗淨掏空抹乾，表皮塗老抽。下熱油中將整隻鴨炸至表皮金黃酥脆，撈起瀝油。花菇海參處理好。", duration: 30 },
      { instruction: "大煲中，爆香大量薑蔥，放入整隻鴨、花菇、雞湯、鮑汁、蠔油、五香粉、冰糖，大火燒開小火慢燉90分鐘。", duration: 90 },
      { instruction: "放入海參段，繼續慢燉25分鐘至海參軟Q、鴨肉軟爛。將大鴨整隻撈出擺大盤正中，海參花菇排在兩側。", duration: 25 },
      { instruction: "煲中湯汁大火收稠，勾芡澆在整隻鴨與海參表面即可霸氣上桌。", duration: 5 },
    ],
    tags: ["港式", "經典", "炆", "鮑汁", "慢煮"],
  },
];
