export const HK_STEAMED_RECIPES = [
  {
    name: "原味蒸肉餅",
    description: "地道港式家常菜，肉質鬆軟多汁，做法簡單，係最受歡迎嘅落飯餸。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "半肥瘦免治豬肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "麻油", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "水", quantity: "2", unit: "湯匙", category: "其他" },
      { name: "胡椒粉", quantity: "少許", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "免治豬肉加入生抽、糖、胡椒粉、生粉同麻油攪勻。", duration: 5 },
      { instruction: "分次加入2湯匙水，順時針方向大力攪拌至肉質起膠。", duration: 3 },
      { instruction: "將肉泥平鋪喺碟上，用手指輕輕壓平（中間微凹，熟得均勻啲）。", duration: 2 },
      { instruction: "水滾後放入蒸鍋，大火蒸10-12分鐘即可。", duration: 10 },
    ],
    tags: ["港式", "家常菜", "蒸", "簡單", "快手", "30 分鐘內", "小朋友", "下飯", "鮮味"],
  },
  {
    name: "咸蛋蒸肉餅",
    description: "鹹蛋嘅油香滲入嫩滑嘅肉餅之中，鹹香開胃，係茶餐廳同家常飯桌嘅經典。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "半肥瘦免治豬肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "鹹蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "麻油", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "水", quantity: "2", unit: "湯匙", category: "其他" },
    ],
    steps: [
      { instruction: "將鹹蛋嘅蛋白同蛋黃分開。蛋白倒入免治豬肉中。", duration: 3 },
      { instruction: "豬肉加入生抽、糖、生粉、麻油同蛋白，分次加水，順時針攪至起膠。", duration: 5 },
      { instruction: "肉泥鋪在碟上，將鹹蛋黃放喺肉餅正中間。", duration: 2 },
      { instruction: "水滾後放入蒸籠，大火蒸12分鐘即可。", duration: 12 },
    ],
    tags: ["港式", "家常菜", "蒸", "鹹香", "經典", "30 分鐘內", "下飯"],
  },
  {
    name: "梅菜蒸肉餅",
    description: "甜梅菜同鹹梅菜嘅完美結合，釋放獨特嘅鹹甜香氣，完美融入肉餅中。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "半肥瘦免治豬肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "甜梅菜", quantity: "50", unit: "克", category: "蔬菜" },
      { name: "鹹梅菜", quantity: "20", unit: "克", category: "蔬菜" },
      { name: "生抽", quantity: "1/2", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "蒜頭", quantity: "2", unit: "瓣", category: "調味料" },
      { name: "食油", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "梅菜反覆洗淨浸泡，瀝乾水分切碎。蒜頭切茸。", duration: 10 },
      { instruction: "燒熱油爆香蒜茸，加入梅菜碎同糖略炒，盛起放涼。", duration: 5 },
      { instruction: "豬肉加入生抽、生粉同炒好嘅梅菜拌勻，輕輕攪拌平鋪喺碟上。", duration: 3 },
      { instruction: "大火隔水蒸12分鐘即成。", duration: 12 },
    ],
    tags: ["港式", "家常菜", "蒸", "經典", "30 分鐘內", "下飯", "開胃", "酸甜", "鹹香"],
  },
  {
    name: "魷魚絲蒸肉餅",
    description: "傳統大牌檔風味，用上乾乾地嘅魷魚絲，蒸出嚟極具海洋鮮味同嚼勁。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "半肥瘦免治豬肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "吊片魷魚乾", quantity: "1", unit: "隻", category: "乾貨" },
      { name: "薑絲", quantity: "適量", unit: "", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "麻油", quantity: "1/2", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "魷魚乾用溫水浸軟，撕去外膜，洗淨切細絲或細粒。", duration: 10 },
      { instruction: "免治豬肉加入生抽、糖、生粉、麻油攪拌，放入大部分魷魚絲拌勻。", duration: 5 },
      { instruction: "將肉泥平鋪喺碟上，面頭鋪上餘下嘅魷魚絲同薑絲。", duration: 2 },
      { instruction: "大火隔水蒸12分鐘至熟透即可。", duration: 12 },
    ],
    tags: ["港式", "家常菜", "蒸", "鮮味", "30 分鐘內", "下飯", "經典"],
  },
  {
    name: "馬蹄土魷蒸肉餅",
    description: "用切碎嘅土魷（乾魷魚）同手剁肉餅，煙韌多汁，口感層次極其豐富。",
    cookTime: 30,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "豬梅頭肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "土魷（乾魷魚）", quantity: "1", unit: "隻", category: "乾貨" },
      { name: "馬蹄", quantity: "4", unit: "個", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "麻油", quantity: "1/2", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "土魷浸軟切細粒。馬蹄去皮切碎。梅頭肉用刀親自剁碎至有彈性。", duration: 15 },
      { instruction: "肉碎加入土魷粒、馬蹄碎，以及生抽、生粉、糖、麻油攪勻起膠。", duration: 5 },
      { instruction: "將肉餅整成圓餅狀鋪在碟上，大火蒸12-15分鐘即可。", duration: 15 },
    ],
    tags: ["港式", "家常菜", "蒸", "鮮味", "30 分鐘內", "下飯", "進階", "經典"],
  },
  {
    name: "冬菇蒸雞",
    description: "香氣撲鼻嘅冬菇，配上嫩滑嘅雞肉，湯汁精華拌飯一流，健康滋補。",
    cookTime: 30,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞髀肉或半隻雞", quantity: "400", unit: "克", category: "肉類" },
      { name: "乾冬菇", quantity: "6", unit: "朵", category: "乾貨" },
      { name: "薑絲", quantity: "適量", unit: "", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蠔油", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "冬菇用溫水浸軟去蒂，切厚片。雞斬件洗淨瀝乾。", duration: 15 },
      { instruction: "雞件用生抽、蠔油、糖、生粉、紹興酒醃15分鐘。", duration: 15 },
      { instruction: "加入冬菇片、薑絲拌勻，鋪平喺碟上。", duration: 2 },
      { instruction: "水滾後用大火蒸15-18分鐘至熟透即可。", duration: 18 },
    ],
    tags: ["港式", "家常菜", "蒸", "鮮味", "健康", "滋補", "下飯"],
  },
  {
    name: "雲耳勝瓜蒸雞",
    description: "勝瓜清甜，雲耳爽脆，配搭滑嫩雞肉一齊蒸，清淡少油又滋潤。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞肉（雞髀肉件）", quantity: "300", unit: "克", category: "肉類" },
      { name: "勝瓜（絲瓜）", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "雲耳", quantity: "10", unit: "克", category: "乾貨" },
      { name: "薑絲", quantity: "適量", unit: "", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "麻油", quantity: "1/2", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "雲耳浸軟去硬蒂撕小朵。勝瓜去硬皮切滾刀塊。雞肉切塊。", duration: 10 },
      { instruction: "雞肉用生抽、糖、生粉、麻油醃15分鐘。", duration: 15 },
      { instruction: "碟底鋪上勝瓜同雲耳，放上雞肉及薑絲。", duration: 3 },
      { instruction: "大火隔水蒸15分鐘即成。", duration: 15 },
    ],
    tags: ["港式", "家常菜", "蒸", "清淡", "健康", "30 分鐘內", "低卡", "蔬菜"],
  },
  {
    name: "蟲草花蒸雞",
    description: "蟲草花具有滋肺補腎功效，蒸煮後釋放金黃湯汁，味道香甜芳香，養生一流。",
    cookTime: 30,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞件（或雞髀肉）", quantity: "400", unit: "克", category: "肉類" },
      { name: "蟲草花", quantity: "15", unit: "克", category: "乾貨" },
      { name: "紅棗（去核）", quantity: "3", unit: "粒", category: "其他" },
      { name: "薑絲", quantity: "適量", unit: "", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "蟲草花洗淨稍微浸泡10分鐘。紅棗切條。雞件洗淨瀝乾。", duration: 10 },
      { instruction: "雞件用生抽、鹽、糖、生粉、紹興酒醃20分鐘。", duration: 20 },
      { instruction: "拌入蟲草花、紅棗同薑絲，鋪平在盤上。", duration: 2 },
      { instruction: "大火蒸15-18分鐘即可。", duration: 18 },
    ],
    tags: ["港式", "家常菜", "蒸", "健康", "滋補", "經典"],
  },
  {
    name: "豉汁蒸排骨",
    description: "大牌檔經典！用豆豉同蒜蓉調配醬汁，排骨蒸到爽滑脫骨，豉香極濃。",
    cookTime: 25,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "排骨（一字排/腩排）", quantity: "350", unit: "克", category: "肉類" },
      { name: "陽江豆豉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蒜頭", quantity: "3", unit: "瓣", category: "調味料" },
      { name: "辣椒（切圈）", quantity: "1", unit: "條", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1.5", unit: "茶匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "食油", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "排骨用清水洗淨吸乾。豆豉蒜頭拍碎剁蓉。", duration: 10 },
      { instruction: "排骨加蒜蓉豆豉、生抽、糖、紹興酒、生粉攪勻，最後落油鎖水分，醃15分鐘。", duration: 15 },
      { instruction: "鋪平盤上，放上辣椒圈（不辣可免）。", duration: 2 },
      { instruction: "大火隔水蒸10-12分鐘即可。", duration: 12 },
    ],
    tags: ["港式", "家常菜", "蒸", "鹹香", "開胃", "30 分鐘內", "下飯", "經典"],
  },
  {
    name: "南瓜蒸排骨",
    description: "南瓜吸收咗排骨嘅肉汁，清甜多汁，排骨滑嫩，營養均衡嘅一道蒸餸。",
    cookTime: 30,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "排骨", quantity: "300", unit: "克", category: "肉類" },
      { name: "南瓜", quantity: "200", unit: "克", category: "蔬菜" },
      { name: "蒜蓉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "麻油", quantity: "1/2", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "南瓜去籽切塊。排骨洗淨抹乾，加蒜蓉、生抽、糖、生粉、麻油醃15分鐘。", duration: 15 },
      { instruction: "將南瓜塊鋪在盤底，上面整齊鋪上醃好嘅排骨。", duration: 3 },
      { instruction: "大火隔水蒸15-18分鐘，至南瓜軟熟、排骨熟透。", duration: 18 },
    ],
    tags: ["港式", "家常菜", "蒸", "清甜", "健康", "小朋友", "下飯", "電飯煲料理"],
  },
  {
    name: "榨菜蒸牛肉",
    description: "脆爽嘅榨菜片加上極滑嘅手切牛肉，鹹香爽口，老一輩最愛嘅開胃家常餸。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "牛脊肉或牛柳肉", quantity: "250", unit: "克", category: "肉類" },
      { name: "鹹榨菜", quantity: "50", unit: "克", category: "乾貨" },
      { name: "薑絲", quantity: "適量", unit: "", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "水", quantity: "1", unit: "湯匙", category: "其他" },
      { name: "食油", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "牛肉逆紋切薄片。榨菜洗淨切細絲浸泡5分鐘去部分鹹味。", duration: 10 },
      { instruction: "牛肉先落生抽、糖、生粉同水攪勻醃15分鐘，最後加食油拌勻。", duration: 15 },
      { instruction: "將牛肉鋪在盤上，面鋪榨菜絲同薑絲。", duration: 2 },
      { instruction: "大火蒸7-8分鐘至剛好熟，保持牛肉滑嫩。", duration: 8 },
    ],
    tags: ["港式", "家常菜", "蒸", "鹹香", "開胃", "30 分鐘內", "快手", "簡單", "滑嫩"],
  },
  {
    name: "陳皮蒸牛肉球",
    description: "經典港式點心，陳皮芳香撲鼻，配上爽滑有彈性嘅牛肉，令人回味無窮。",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "免治牛肉", quantity: "300", unit: "克", category: "肉類" },
      { name: "老陳皮", quantity: "1/4", unit: "個", category: "調味料" },
      { name: "馬蹄", quantity: "3", unit: "個", category: "蔬菜" },
      { name: "香菜", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "生粉", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "小蘇打粉（選用）", quantity: "1/4", unit: "茶匙", category: "調味料" },
      { name: "喼汁（伴碟）", quantity: "適量", unit: "", category: "調味料" },
    ],
    steps: [
      { instruction: "陳皮浸軟去內外白囊切極細茸。馬蹄去皮切碎，香菜切碎。", duration: 15 },
      { instruction: "免治牛肉加入生抽、鹽、糖、生粉、小蘇打同陳皮茸，順時針方向大力攪拌上勁，摔打20次至起膠，最後加入馬蹄同香菜拌勻。", duration: 10 },
      { instruction: "手抹少許油，將牛肉泥捏成數個圓球狀，排在碟上（碟底可鋪腐皮）。", duration: 5 },
      { instruction: "大火隔水蒸8-10分鐘。食時可蘸喼汁。", duration: 10 },
    ],
    tags: ["港式", "經典", "蒸", "宴客", "進階"],
  },
  {
    name: "清蒸海上鮮",
    description: "以最簡單嘅蔥絲同熟油淋在鮮魚上，保留海鮮最極致嘅鮮味，皮脆肉嫩。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "鮮魚（如石斑或鱸魚）", quantity: "1", unit: "條", category: "海鮮" },
      { name: "薑絲", quantity: "適量", unit: "", category: "調味料" },
      { name: "蔥絲", quantity: "大量", unit: "", category: "蔬菜" },
      { name: "蒸魚豉油", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "鮮魚去鱗去內臟清洗乾淨，用廚房紙完全抹乾，魚身劃兩刀，淋紹興酒，鋪上部分薑絲。", duration: 8 },
      { instruction: "水大滾，放入鮮魚大火蒸8-10分鐘（視大小而定）。", duration: 10 },
      { instruction: "取出，倒掉碟中蒸魚嘅水份（有魚腥味）。", duration: 1 },
      { instruction: "鋪上蔥絲及剩餘薑絲。燒熱2湯匙食油至冒煙，淋喺魚身激發蔥香，最後在魚側淋蒸魚豉油。", duration: 3 },
    ],
    tags: ["港式", "家常菜", "蒸", "海鮮", "鮮味", "健康", "宴客", "經典", "清淡"],
  },
  {
    name: "豉汁蒸鯇魚",
    description: "鯇魚肉質結實，加上醇厚鹹香嘅豉汁同蒸，油而不膩，地道漁家風味。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "鯇魚腩件", quantity: "350", unit: "克", category: "海鮮" },
      { name: "豆豉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蒜蓉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "薑絲", quantity: "適量", unit: "", category: "調味料" },
      { name: "蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "鯇魚腩洗淨瀝乾。豆豉和蒜蓉拍碎剁勻。", duration: 5 },
      { instruction: "將豆豉蒜蓉、生抽、糖同紹興酒調成醬汁，塗勻在魚腩上，鋪上薑絲。", duration: 5 },
      { instruction: "放入蒸鍋，大火隔水蒸10分鐘。", duration: 10 },
      { instruction: "出鍋灑蔥花，淋少許熟油即可。", duration: 2 },
    ],
    tags: ["港式", "家常菜", "蒸", "海鮮", "鹹香", "下飯", "簡單", "30 分鐘內"],
  },
  {
    name: "薑蔥蒸魚雲",
    description: "大牌檔特色菜，魚頭（魚雲）嫩滑如豆腐，薑蔥爆出極致香氣，吸食汁液絕美。",
    cookTime: 25,
    servings: 2,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "大魚頭（切件）", quantity: "1", unit: "個", category: "海鮮" },
      { name: "薑片", quantity: "4", unit: "片", category: "調味料" },
      { name: "蔥段", quantity: "3", unit: "條", category: "蔬菜" },
      { name: "蒜頭", quantity: "2", unit: "瓣", category: "調味料" },
      { name: "生抽", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "老抽", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "紹興酒", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "生粉", quantity: "1", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "魚頭洗淨去除黑膜（腥味來源），斬件吸乾水分。", duration: 10 },
      { instruction: "魚頭件加入生抽、老抽、糖、紹興酒、生粉同拍扁薑蒜拌勻，醃10分鐘。", duration: 10 },
      { instruction: "擺在碟中，上面鋪滿蔥段。", duration: 2 },
      { instruction: "水滾大火蒸10分鐘。淋上滾油即可。", duration: 10 },
    ],
    tags: ["港式", "家常菜", "蒸", "海鮮", "滑嫩", "進階", "送酒", "鮮味"],
  },
  {
    name: "豉汁蒸生蠔",
    description: "港式海鮮酒家經典，肥美肥嫩嘅鮮蠔配上金蒜豆豉，入口爆汁，鮮美無比。",
    cookTime: 20,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮生蠔肉", quantity: "8", unit: "隻", category: "海鮮" },
      { name: "豆豉", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "蒜蓉", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "紅辣椒絲", quantity: "少許", unit: "", category: "蔬菜" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "糖", quantity: "1/2", unit: "茶匙", category: "調味料" },
      { name: "生粉（洗蠔用）", quantity: "2", unit: "湯匙", category: "其他" },
    ],
    steps: [
      { instruction: "生蠔肉加生粉輕輕抓洗，去除黏液，用清水沖洗乾淨，瀝乾水分並用廚房紙印乾。", duration: 10 },
      { instruction: "豆豉蒜頭剁碎，用熱油小火炒香，加生抽糖調成豉汁。", duration: 5 },
      { instruction: "生蠔鋪平在盤上，每隻鋪上一勺豉汁，放上辣椒絲。", duration: 3 },
      { instruction: "大火快速蒸5分鐘至剛剛熟即可，過火會縮水。", duration: 5 },
    ],
    tags: ["港式", "經典", "蒸", "海鮮", "生蠔", "鮮味", "宴客", "進階"],
  },
  {
    name: "蒜蓉粉絲蒸生蠔",
    description: "鋪底嘅粉絲完全吸收咗生蠔嘅鮮甜同蒜香熟油嘅精華，甚至比生蠔更加美味。",
    cookTime: 25,
    servings: 3,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮生蠔肉", quantity: "8", unit: "隻", category: "海鮮" },
      { name: "粉絲", quantity: "1", unit: "包", category: "乾貨" },
      { name: "蒜頭", quantity: "1", unit: "整個", category: "調味料" },
      { name: "蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "蒸魚豉油", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "生粉（洗蠔用）", quantity: "2", unit: "湯匙", category: "其他" },
    ],
    steps: [
      { instruction: "粉絲用溫水浸軟切段鋪在盤底。生蠔用生粉輕洗乾淨，抹乾鋪在粉絲上。", duration: 12 },
      { instruction: "蒜頭全部剁蓉，一半用油炒至金黃，混合剩餘生蒜（金銀蒜），均勻鋪在生蠔上。", duration: 5 },
      { instruction: "大火隔水蒸6-7分鐘。", duration: 7 },
      { instruction: "出鍋淋上蒸魚豉油，灑蔥花，澆上少許熱油即可。", duration: 3 },
    ],
    tags: ["港式", "經典", "蒸", "海鮮", "生蠔", "蒜蓉", "鮮味", "宴客", "進階"],
  },
  {
    name: "蒜蓉粉絲蒸大蝦",
    description: "大排檔同婚宴必備嘅硬菜！開邊大蝦視覺效果震撼，蝦肉爽口，蒜香濃郁。",
    cookTime: 25,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "新鮮大蝦（如海蝦或虎蝦）", quantity: "8", unit: "隻", category: "海鮮" },
      { name: "粉絲", quantity: "1", unit: "包", category: "乾貨" },
      { name: "蒜頭", quantity: "1", unit: "整個", category: "調味料" },
      { name: "蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "蒸魚豉油", quantity: "1.5", unit: "湯匙", category: "調味料" },
      { name: "食油", quantity: "2", unit: "湯匙", category: "調味料" },
    ],
    steps: [
      { instruction: "粉絲溫水浸軟鋪盤底。大蝦剪去槍鬚，從背部開邊（不切斷），剔除蝦線，輕壓鋪在粉絲上。", duration: 15 },
      { instruction: "蒜頭剁碎，一半用油炸香，混入生蒜與少許鹽，塞在蝦背肉上。", duration: 5 },
      { instruction: "大火隔水蒸6-8分鐘至蝦肉變紅熟透。", duration: 8 },
      { instruction: "出鍋灑蔥花，淋蒸魚豉油，淋上滾油即可。", duration: 2 },
    ],
    tags: ["港式", "經典", "蒸", "海鮮", "蒜蓉", "鮮味", "宴客", "進階"],
  },
  {
    name: "蒜蓉粉絲蒸帶子",
    description: "極為鮮甜嘅帶子與爽脆粉絲、濃郁蒜蓉熟油完美結合，係粵式海鮮料理嘅巔峰代表。",
    cookTime: 20,
    servings: 4,
    difficulty: "中等",
    recipeCategory: "中菜",
    ingredients: [
      { name: "鮮帶子（連殼）", quantity: "4", unit: "隻", category: "海鮮" },
      { name: "粉絲", quantity: "1/2", unit: "包", category: "乾貨" },
      { name: "蒜頭", quantity: "6", unit: "瓣", category: "調味料" },
      { name: "蔥花", quantity: "適量", unit: "", category: "蔬菜" },
      { name: "蒸魚豉油", quantity: "1", unit: "湯匙", category: "調味料" },
      { name: "鹽", quantity: "1/2", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "帶子洗淨去除內臟，抹乾，用半邊殼盛載。粉絲浸軟盤成小團鋪在帶子上。", duration: 10 },
      { instruction: "蒜頭剁碎，一半炒香，混合生蒜與鹽，鋪在粉絲帶子上。", duration: 5 },
      { instruction: "大火隔水蒸5-6分鐘。", duration: 6 },
      { instruction: "出鍋灑蔥花，淋蒸魚豉油和熱熟油即可。", duration: 2 },
    ],
    tags: ["港式", "經典", "蒸", "海鮮", "蒜蓉", "鮮味", "宴客", "進階", "清淡"],
  },
  {
    name: "蒸三色蛋",
    description: "雞蛋、皮蛋、鹹蛋三者融合，色彩奪目，口感豐富有層次，清淡而味道濃郁。",
    cookTime: 20,
    servings: 3,
    difficulty: "簡單",
    recipeCategory: "中菜",
    ingredients: [
      { name: "雞蛋", quantity: "3", unit: "隻", category: "其他" },
      { name: "皮蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "鹹鴨蛋", quantity: "1", unit: "隻", category: "其他" },
      { name: "水", quantity: "150", unit: "毫升", category: "其他" },
      { name: "生抽", quantity: "1", unit: "茶匙", category: "調味料" },
      { name: "麻油", quantity: "1/2", unit: "茶匙", category: "調味料" },
    ],
    steps: [
      { instruction: "皮蛋和鹹蛋煮熟，去殼切小粒，鋪在深盤底。", duration: 5 },
      { instruction: "雞蛋打散，加入水同少許鹽，順時針方向輕輕攪勻，用濾網過濾倒入盛裝皮蛋鹹蛋粒嘅盤中。", duration: 5 },
      { instruction: "盤面用保鮮膜封好，戳幾個氣孔。", duration: 2 },
      { instruction: "中火蒸12-15分鐘至凝固。出鍋淋生抽和麻油。", duration: 15 },
    ],
    tags: ["港式", "家常菜", "蒸", "清淡", "30 分鐘內", "小朋友", "簡單", "新手"],
  },
];
